# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUi3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1027, 610)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-60, -80, 991, 681))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgba(85, 98, 112, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
"    color: rgba(131, 96, 53, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(91, 88, 53, 255);\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.backdrop_holder_label = QtWidgets.QLabel(self.widget)
        self.backdrop_holder_label.setGeometry(QtCore.QRect(100, 210, 531, 481))
        self.backdrop_holder_label.setStyleSheet("border-image: url(:/images/background.gif);\n"
"border-top-left-radius: 50px;")
        self.backdrop_holder_label.setText("")
        self.backdrop_holder_label.setObjectName("backdrop_holder_label")
        self.backdrop_holder = QtWidgets.QLabel(self.widget)
        self.backdrop_holder.setGeometry(QtCore.QRect(100, 70, 531, 611))
        self.backdrop_holder.setStyleSheet("background-color:rgba(0, 0, 0, 80);\n"
"border-top-left-radius: 50px;")
        self.backdrop_holder.setText("")
        self.backdrop_holder.setObjectName("backdrop_holder")
        self.program_backdrop = QtWidgets.QLabel(self.widget)
        self.program_backdrop.setGeometry(QtCore.QRect(110, 80, 521, 130))
        self.program_backdrop.setStyleSheet("background-color:rgba(0, 0, 0, 75);")
        self.program_backdrop.setText("")
        self.program_backdrop.setObjectName("program_backdrop")
        self.program_title = QtWidgets.QLabel(self.widget)
        self.program_title.setGeometry(QtCore.QRect(380, 90, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.program_title.setFont(font)
        self.program_title.setStyleSheet("color:rgba(255, 255, 255, 200);")
        self.program_title.setObjectName("program_title")
        self.program_description = QtWidgets.QLabel(self.widget)
        self.program_description.setGeometry(QtCore.QRect(119, 140, 241, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.program_description.setFont(font)
        self.program_description.setStyleSheet("color:rgba(255, 255, 255, 170);")
        self.program_description.setObjectName("program_description")
        self.system_updates = QtWidgets.QFrame(self.widget)
        self.system_updates.setGeometry(QtCore.QRect(110, 220, 511, 381))
        self.system_updates.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.system_updates.setFrameShadow(QtWidgets.QFrame.Raised)
        self.system_updates.setObjectName("system_updates")
        self.updates_label = QtWidgets.QLabel(self.system_updates)
        self.updates_label.setGeometry(QtCore.QRect(200, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("HACKED")
        font.setPointSize(22)
        self.updates_label.setFont(font)
        self.updates_label.setObjectName("updates_label")
        self.update_1_label = QtWidgets.QLabel(self.system_updates)
        self.update_1_label.setGeometry(QtCore.QRect(10, 60, 241, 91))
        self.update_1_label.setObjectName("update_1_label")
        self.update_2_label = QtWidgets.QLabel(self.system_updates)
        self.update_2_label.setGeometry(QtCore.QRect(10, 140, 241, 91))
        self.update_2_label.setObjectName("update_2_label")
        self.update_3_label = QtWidgets.QLabel(self.system_updates)
        self.update_3_label.setGeometry(QtCore.QRect(10, 230, 241, 91))
        self.update_3_label.setObjectName("update_3_label")
        self.update_1_label_2 = QtWidgets.QLabel(self.system_updates)
        self.update_1_label_2.setGeometry(QtCore.QRect(270, 60, 241, 91))
        self.update_1_label_2.setObjectName("update_1_label_2")
        self.update_1_label_3 = QtWidgets.QLabel(self.system_updates)
        self.update_1_label_3.setGeometry(QtCore.QRect(260, 150, 241, 91))
        self.update_1_label_3.setObjectName("update_1_label_3")
        self.update_1_label_4 = QtWidgets.QLabel(self.system_updates)
        self.update_1_label_4.setGeometry(QtCore.QRect(270, 250, 241, 91))
        self.update_1_label_4.setObjectName("update_1_label_4")
        self.program_stats_frame = QtWidgets.QFrame(self.widget)
        self.program_stats_frame.setGeometry(QtCore.QRect(110, 620, 511, 51))
        self.program_stats_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.program_stats_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.program_stats_frame.setObjectName("program_stats_frame")
        self.login_tab_widget = QtWidgets.QTabWidget(Form)
        self.login_tab_widget.setGeometry(QtCore.QRect(570, 0, 451, 611))
        self.login_tab_widget.setTabPosition(QtWidgets.QTabWidget.East)
        self.login_tab_widget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.login_tab_widget.setTabsClosable(True)
        self.login_tab_widget.setTabBarAutoHide(True)
        self.login_tab_widget.setObjectName("login_tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.login_backdrop = QtWidgets.QLabel(self.tab)
        self.login_backdrop.setGeometry(QtCore.QRect(-30, 0, 441, 591))
        self.login_backdrop.setStyleSheet("QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QTreeView,\n"
"QListView,\n"
"QLineEdit,\n"
"QComboBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.login_backdrop.setText("")
        self.login_backdrop.setObjectName("login_backdrop")
        self.username_lineedit = QtWidgets.QLineEdit(self.tab)
        self.username_lineedit.setGeometry(QtCore.QRect(95, 180, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_lineedit.setFont(font)
        self.username_lineedit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.username_lineedit.setObjectName("username_lineedit")
        self.password_lineedit = QtWidgets.QLineEdit(self.tab)
        self.password_lineedit.setGeometry(QtCore.QRect(95, 245, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_lineedit.setFont(font)
        self.password_lineedit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineedit.setObjectName("password_lineedit")
        self.c_label_button = QtWidgets.QPushButton(self.tab)
        self.c_label_button.setGeometry(QtCore.QRect(230, 500, 30, 30))
        self.c_label_button.setMaximumSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.c_label_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.c_label_button.setFont(font)
        self.c_label_button.setMouseTracking(True)
        self.c_label_button.setCheckable(False)
        self.c_label_button.setObjectName("c_label_button")
        self.u_label_button = QtWidgets.QPushButton(self.tab)
        self.u_label_button.setGeometry(QtCore.QRect(130, 500, 30, 30))
        self.u_label_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.u_label_button.setFont(font)
        self.u_label_button.setCheckable(False)
        self.u_label_button.setChecked(False)
        self.u_label_button.setObjectName("u_label_button")
        self.o_label_button = QtWidgets.QPushButton(self.tab)
        self.o_label_button.setGeometry(QtCore.QRect(80, 500, 30, 30))
        self.o_label_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.o_label_button.setFont(font)
        self.o_label_button.setObjectName("o_label_button")
        self.login_button = QtWidgets.QPushButton(self.tab)
        self.login_button.setGeometry(QtCore.QRect(95, 325, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.login_label = QtWidgets.QLabel(self.tab)
        self.login_label.setGeometry(QtCore.QRect(140, 110, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.login_label.setFont(font)
        self.login_label.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.login_label.setObjectName("login_label")
        self.S_label_button = QtWidgets.QPushButton(self.tab)
        self.S_label_button.setGeometry(QtCore.QRect(30, 500, 30, 30))
        self.S_label_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.S_label_button.setFont(font)
        self.S_label_button.setObjectName("S_label_button")
        self.r_label_button = QtWidgets.QPushButton(self.tab)
        self.r_label_button.setGeometry(QtCore.QRect(180, 500, 30, 30))
        self.r_label_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.r_label_button.setFont(font)
        self.r_label_button.setObjectName("r_label_button")
        self.Forgot_username_label = QtWidgets.QLabel(self.tab)
        self.Forgot_username_label.setGeometry(QtCore.QRect(101, 375, 201, 16))
        self.Forgot_username_label.setStyleSheet("color:rgba(0, 0, 0, 210);")
        self.Forgot_username_label.setObjectName("Forgot_username_label")
        self.e_label_button = QtWidgets.QPushButton(self.tab)
        self.e_label_button.setGeometry(QtCore.QRect(280, 500, 30, 30))
        self.e_label_button.setMaximumSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.e_label_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.e_label_button.setFont(font)
        self.e_label_button.setMouseTracking(True)
        self.e_label_button.setCheckable(False)
        self.e_label_button.setObjectName("e_label_button")
        self.want_to_register_button = QtWidgets.QLabel(self.tab)
        self.want_to_register_button.setGeometry(QtCore.QRect(140, 400, 101, 16))
        self.want_to_register_button.setStyleSheet("color:rgba(0, 0, 0, 210);")
        self.want_to_register_button.setObjectName("want_to_register_button")
        self.d_label_button = QtWidgets.QPushButton(self.tab)
        self.d_label_button.setGeometry(QtCore.QRect(330, 500, 30, 30))
        self.d_label_button.setMaximumSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.d_label_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.d_label_button.setFont(font)
        self.d_label_button.setMouseTracking(True)
        self.d_label_button.setCheckable(False)
        self.d_label_button.setObjectName("d_label_button")
        self.o_label_button_2 = QtWidgets.QPushButton(self.tab)
        self.o_label_button_2.setGeometry(QtCore.QRect(100, 440, 30, 30))
        self.o_label_button_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.o_label_button_2.setFont(font)
        self.o_label_button_2.setObjectName("o_label_button_2")
        self.P_label_button = QtWidgets.QPushButton(self.tab)
        self.P_label_button.setGeometry(QtCore.QRect(150, 440, 30, 30))
        self.P_label_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.P_label_button.setFont(font)
        self.P_label_button.setObjectName("P_label_button")
        self.E_label_button = QtWidgets.QPushButton(self.tab)
        self.E_label_button.setGeometry(QtCore.QRect(200, 440, 30, 30))
        self.E_label_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.E_label_button.setFont(font)
        self.E_label_button.setObjectName("E_label_button")
        self.N_label_button = QtWidgets.QPushButton(self.tab)
        self.N_label_button.setGeometry(QtCore.QRect(250, 440, 30, 30))
        self.N_label_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.N_label_button.setFont(font)
        self.N_label_button.setObjectName("N_label_button")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../OneDrive/Documents/New Structure/icons/exit-to-app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_tab_widget.addTab(self.tab, icon, "")
        self.information_tab2 = QtWidgets.QWidget()
        self.information_tab2.setObjectName("information_tab2")
        self.tab_2_widget_holder = QAxContainer.QAxWidget(self.information_tab2)
        self.tab_2_widget_holder.setProperty("geometry", QtCore.QRect(10, 170, 391, 391))
        self.tab_2_widget_holder.setObjectName("tab_2_widget_holder")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../OneDrive/Documents/New Structure/icons/go-back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_tab_widget.addTab(self.information_tab2, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.login_tab_widget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.login_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.program_title.setText(_translate("Form", "Diamond💎\n"
"               Sorter"))
        self.program_description.setText(_translate("Form", "Hi,\n"
"Welcome to Diamond Sorter channel.\n"
"Don\'t forget to subscribe."))
        self.updates_label.setText(_translate("Form", "Updates"))
        self.update_1_label.setText(_translate("Form", "1/12/24\n"
"-Launched to Pre-Release of DIamond Sorter\n"
"-Configured Licensing System\n"
"-Developed Login GUI"))
        self.update_2_label.setText(_translate("Form", "1/14/24\n"
"- Developed Telegram Licensing Bot\n"
"- Added the 5 Feature Extensions\n"
"- Updated Anti Detect Browser\n"
"- Added Telegram Bot Forwarding Snatcher"))
        self.update_3_label.setText(_translate("Form", "T.B.A"))
        self.update_1_label_2.setText(_translate("Form", "1/12/24\n"
"-Launched to Pre-Release of DIamond Sorter\n"
"-Configured Licensing System\n"
"-Developed Login GUI"))
        self.update_1_label_3.setText(_translate("Form", "1/12/24\n"
"-Launched to Pre-Release of DIamond Sorter\n"
"-Configured Licensing System\n"
"-Developed Login GUI"))
        self.update_1_label_4.setText(_translate("Form", "1/12/24\n"
"-Launched to Pre-Release of DIamond Sorter\n"
"-Configured Licensing System\n"
"-Developed Login GUI"))
        self.username_lineedit.setPlaceholderText(_translate("Form", "  User Name"))
        self.password_lineedit.setPlaceholderText(_translate("Form", "  Password"))
        self.c_label_button.setText(_translate("Form", "C"))
        self.u_label_button.setText(_translate("Form", "U"))
        self.o_label_button.setText(_translate("Form", "O"))
        self.login_button.setText(_translate("Form", "L o g  I n"))
        self.login_label.setText(_translate("Form", "Log In"))
        self.S_label_button.setText(_translate("Form", "S"))
        self.r_label_button.setText(_translate("Form", "R"))
        self.Forgot_username_label.setText(_translate("Form", "Forgot your User Name or password?"))
        self.e_label_button.setText(_translate("Form", "E"))
        self.want_to_register_button.setText(_translate("Form", "Want to Register?"))
        self.d_label_button.setText(_translate("Form", "D"))
        self.o_label_button_2.setText(_translate("Form", "O"))
        self.P_label_button.setText(_translate("Form", "P"))
        self.E_label_button.setText(_translate("Form", "E"))
        self.N_label_button.setText(_translate("Form", "N"))
        self.login_tab_widget.setTabText(self.login_tab_widget.indexOf(self.tab), _translate("Form", "Login"))
        self.login_tab_widget.setTabText(self.login_tab_widget.indexOf(self.information_tab2), _translate("Form", "Information"))
        self.login_tab_widget.setTabText(self.login_tab_widget.indexOf(self.tab_2), _translate("Form", "Project Information + Updates"))
from PyQt5 import QAxContainer
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
