# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 715)
        MainWindow.setMinimumSize(QtCore.QSize(801, 677))
        MainWindow.setMaximumSize(QtCore.QSize(801, 999))
        MainWindow.setSizeIncrement(QtCore.QSize(801, 677))
        MainWindow.setBaseSize(QtCore.QSize(801, 677))
        MainWindow.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dir.setGeometry(QtCore.QRect(10, 280, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Furore")
        font.setPointSize(10)
        self.lineEdit_dir.setFont(font)
        self.lineEdit_dir.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.lineEdit_dir.setObjectName("lineEdit_dir")
        self.lineEdit_proxy = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_proxy.setGeometry(QtCore.QRect(10, 320, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Furore")
        font.setPointSize(10)
        self.lineEdit_proxy.setFont(font)
        self.lineEdit_proxy.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.lineEdit_proxy.setObjectName("lineEdit_proxy")
        self.lineEdit_ua = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ua.setGeometry(QtCore.QRect(10, 360, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Furore")
        font.setPointSize(10)
        self.lineEdit_ua.setFont(font)
        self.lineEdit_ua.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.lineEdit_ua.setObjectName("lineEdit_ua")
        self.checkBox_ua = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ua.setGeometry(QtCore.QRect(440, 360, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        self.checkBox_ua.setFont(font)
        self.checkBox_ua.setStyleSheet("color: #c8c8c8")
        self.checkBox_ua.setObjectName("checkBox_ua")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 630, 601, 51))
        self.label_2.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(620, 630, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Furore")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(180, 640, 421, 31))
        self.progressBar.setStyleSheet("background-color: #181818;\n"
"border: 3px solid #363636;\n"
"color: #c8c8c8")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_dir_logs = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dir_logs.setGeometry(QtCore.QRect(430, 280, 91, 31))
        self.pushButton_dir_logs.setStyleSheet("")
        self.pushButton_dir_logs.setObjectName("pushButton_dir_logs")
        self.pushButton_proxies_files = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_proxies_files.setGeometry(QtCore.QRect(340, 320, 91, 31))
        self.pushButton_proxies_files.setStyleSheet("")
        self.pushButton_proxies_files.setObjectName("Choose a path")
        self.pushButton_useragents_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_useragents_file.setGeometry(QtCore.QRect(340, 360, 91, 31))
        self.pushButton_useragents_file.setStyleSheet("")
        self.pushButton_useragents_file.setObjectName("Choose a path")
        self.textEdit_console = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_console.setGeometry(QtCore.QRect(10, 20, 781, 251))
        self.textEdit_console.setStyleSheet("background-color: #181818;\n"
"border: 3px solid #363636;\n"
"color: #c8c8c8")
        self.textEdit_console.setObjectName("textEdit_console")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 630, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Furore")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.spinBox_thr = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_thr.setGeometry(QtCore.QRect(90, 640, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.spinBox_thr.setFont(font)
        self.spinBox_thr.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.spinBox_thr.setObjectName("spinBox_thr")
        self.label_lgbt = QtWidgets.QLabel(self.centralwidget)
        self.label_lgbt.setGeometry(QtCore.QRect(0, 0, 801, 5))
        self.label_lgbt.setText("")
        self.label_lgbt.setScaledContents(True)
        self.label_lgbt.setObjectName("label_lgbt")
        self.comboBox_proxy = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_proxy.setGeometry(QtCore.QRect(440, 320, 71, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.comboBox_proxy.setFont(font)
        self.comboBox_proxy.setStyleSheet("")
        self.comboBox_proxy.setObjectName("comboBox_proxy")
        self.comboBox_proxy.addItem("")
        self.comboBox_proxy.addItem("")
        self.comboBox_proxy.addItem("")
        self.comboBox_proxy.addItem("")
        self.stats_box = QtWidgets.QLabel(self.centralwidget)
        self.stats_box.setGeometry(QtCore.QRect(530, 280, 261, 141))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.stats_box.setFont(font)
        self.stats_box.setStyleSheet("")
        self.stats_box.setText("")
        self.stats_box.setObjectName("stats_box")
        self.inbox_tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.inbox_tab_widget.setGeometry(QtCore.QRect(10, 410, 781, 281))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.inbox_tab_widget.setFont(font)
        self.inbox_tab_widget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.inbox_tab_widget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.inbox_tab_widget.setAutoFillBackground(False)
        self.inbox_tab_widget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #000000;\n"
"    position: absolute;\n"
"    top: -0.5em;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #000000, stop: 0.4 #000000,\n"
"                                stop: 0.5 #000000, stop: 1.0 #000000);\n"
"    border: 2px solid ;\n"
"    selection-color: rgb(15, 255, 167);\n"
"    border-bottom-color: #000000; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #000000, stop: 0.4 #000000,\n"
"                                stop: 0.5 #000000, stop: 1.0 #000000);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #00def2;\n"
"    border-bottom-color: #00def2; /* same as pane color */\n"
"}")
        self.inbox_tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.inbox_tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.inbox_tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.inbox_tab_widget.setMovable(False)
        self.inbox_tab_widget.setTabBarAutoHide(False)
        self.inbox_tab_widget.setObjectName("inbox_tab_widget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox_71 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_71.setEnabled(False)
        self.checkBox_71.setGeometry(QtCore.QRect(120, 100, 81, 41))
        self.checkBox_71.setObjectName("checkBox_71")
        self.checkBox_67 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_67.setEnabled(False)
        self.checkBox_67.setGeometry(QtCore.QRect(9, 100, 81, 31))
        self.checkBox_67.setObjectName("checkBox_67")
        self.checkBox_69 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_69.setEnabled(False)
        self.checkBox_69.setGeometry(QtCore.QRect(9, 132, 71, 31))
        self.checkBox_69.setObjectName("checkBox_69")
        self.checkBox_72 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_72.setEnabled(False)
        self.checkBox_72.setGeometry(QtCore.QRect(120, 10, 65, 31))
        self.checkBox_72.setObjectName("checkBox_72")
        self.checkBox_66 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_66.setEnabled(False)
        self.checkBox_66.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.checkBox_66.setObjectName("checkBox_66")
        self.checkBox_74 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_74.setEnabled(False)
        self.checkBox_74.setGeometry(QtCore.QRect(120, 130, 81, 41))
        self.checkBox_74.setObjectName("checkBox_74")
        self.checkBox_73 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_73.setEnabled(False)
        self.checkBox_73.setGeometry(QtCore.QRect(10, 40, 71, 31))
        self.checkBox_73.setObjectName("checkBox_73")
        self.checkBox_68 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_68.setEnabled(False)
        self.checkBox_68.setGeometry(QtCore.QRect(120, 40, 91, 41))
        self.checkBox_68.setObjectName("checkBox_68")
        self.inbox_tab_widget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.reddit_ads__checkbox = QtWidgets.QCheckBox(self.tab_5)
        self.reddit_ads__checkbox.setEnabled(False)
        self.reddit_ads__checkbox.setGeometry(QtCore.QRect(130, 10, 119, 31))
        self.reddit_ads__checkbox.setObjectName("reddit_ads__checkbox")
        self.craigslist_ads_checkbox = QtWidgets.QCheckBox(self.tab_5)
        self.craigslist_ads_checkbox.setEnabled(False)
        self.craigslist_ads_checkbox.setGeometry(QtCore.QRect(10, 120, 119, 31))
        self.craigslist_ads_checkbox.setObjectName("craigslist_ads_checkbox")
        self.tinder_ads_checkbox = QtWidgets.QCheckBox(self.tab_5)
        self.tinder_ads_checkbox.setEnabled(False)
        self.tinder_ads_checkbox.setGeometry(QtCore.QRect(130, 50, 119, 31))
        self.tinder_ads_checkbox.setObjectName("tinder_ads_checkbox")
        self.microsoft_ads_checkbox = QtWidgets.QCheckBox(self.tab_5)
        self.microsoft_ads_checkbox.setEnabled(False)
        self.microsoft_ads_checkbox.setGeometry(QtCore.QRect(130, 90, 119, 31))
        self.microsoft_ads_checkbox.setObjectName("microsoft_ads_checkbox")
        self.sem_rush_checkbox = QtWidgets.QCheckBox(self.tab_5)
        self.sem_rush_checkbox.setEnabled(False)
        self.sem_rush_checkbox.setGeometry(QtCore.QRect(10, 80, 119, 41))
        self.sem_rush_checkbox.setObjectName("sem_rush_checkbox")
        self.snapchat_ads_checkbox = QtWidgets.QCheckBox(self.tab_5)
        self.snapchat_ads_checkbox.setEnabled(False)
        self.snapchat_ads_checkbox.setGeometry(QtCore.QRect(10, 40, 119, 41))
        self.snapchat_ads_checkbox.setObjectName("snapchat_ads_checkbox")
        self.facebookads__checkbox = QtWidgets.QCheckBox(self.tab_5)
        self.facebookads__checkbox.setGeometry(QtCore.QRect(130, 120, 111, 31))
        self.facebookads__checkbox.setObjectName("facebookads__checkbox")
        self.bing_ads_checkbox = QtWidgets.QCheckBox(self.tab_5)
        self.bing_ads_checkbox.setEnabled(False)
        self.bing_ads_checkbox.setGeometry(QtCore.QRect(10, 10, 119, 31))
        self.bing_ads_checkbox.setObjectName("bing_ads_checkbox")
        self.ahref_checkbox = QtWidgets.QCheckBox(self.tab_5)
        self.ahref_checkbox.setEnabled(False)
        self.ahref_checkbox.setGeometry(QtCore.QRect(250, 10, 119, 31))
        self.ahref_checkbox.setObjectName("ahref_checkbox")
        self.twitter_ads_checkbox = QtWidgets.QCheckBox(self.tab_5)
        self.twitter_ads_checkbox.setEnabled(False)
        self.twitter_ads_checkbox.setGeometry(QtCore.QRect(250, 50, 119, 31))
        self.twitter_ads_checkbox.setObjectName("twitter_ads_checkbox")
        self.inbox_tab_widget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.checkBox_steam = QtWidgets.QCheckBox(self.tab)
        self.checkBox_steam.setGeometry(QtCore.QRect(10, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_steam.setFont(font)
        self.checkBox_steam.setStyleSheet("")
        self.checkBox_steam.setObjectName("checkBox_steam")
        self.checkBox_roblox = QtWidgets.QCheckBox(self.tab)
        self.checkBox_roblox.setGeometry(QtCore.QRect(10, 60, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_roblox.setFont(font)
        self.checkBox_roblox.setStyleSheet("")
        self.checkBox_roblox.setObjectName("checkBox_roblox")
        self.checkBox_battlenet = QtWidgets.QCheckBox(self.tab)
        self.checkBox_battlenet.setGeometry(QtCore.QRect(10, 110, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_battlenet.setFont(font)
        self.checkBox_battlenet.setStyleSheet("")
        self.checkBox_battlenet.setObjectName("checkBox_battlenet")
        self.checkBox_pathofexile = QtWidgets.QCheckBox(self.tab)
        self.checkBox_pathofexile.setGeometry(QtCore.QRect(140, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_pathofexile.setFont(font)
        self.checkBox_pathofexile.setStyleSheet("")
        self.checkBox_pathofexile.setObjectName("checkBox_pathofexile")
        self.inbox_tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox_instagram = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_instagram.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_instagram.setFont(font)
        self.checkBox_instagram.setStyleSheet("")
        self.checkBox_instagram.setObjectName("checkBox_instagram")
        self.checkBox_tiktok = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_tiktok.setGeometry(QtCore.QRect(10, 60, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_tiktok.setFont(font)
        self.checkBox_tiktok.setStyleSheet("")
        self.checkBox_tiktok.setObjectName("checkBox_tiktok")
        self.checkBox_vk = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_vk.setGeometry(QtCore.QRect(10, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_vk.setFont(font)
        self.checkBox_vk.setStyleSheet("")
        self.checkBox_vk.setObjectName("checkBox_vk")
        self.checkBox_youtube = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_youtube.setGeometry(QtCore.QRect(110, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_youtube.setFont(font)
        self.checkBox_youtube.setStyleSheet("")
        self.checkBox_youtube.setObjectName("checkBox_youtube")
        self.checkBox_discord = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_discord.setGeometry(QtCore.QRect(110, 60, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_discord.setFont(font)
        self.checkBox_discord.setStyleSheet("")
        self.checkBox_discord.setObjectName("checkBox_discord")
        self.checkBox_netflix = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_netflix.setGeometry(QtCore.QRect(110, 110, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_netflix.setFont(font)
        self.checkBox_netflix.setStyleSheet("")
        self.checkBox_netflix.setObjectName("checkBox_netflix")
        self.checkBox_facebook_ads = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_facebook_ads.setGeometry(QtCore.QRect(210, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_facebook_ads.setFont(font)
        self.checkBox_facebook_ads.setStyleSheet("")
        self.checkBox_facebook_ads.setObjectName("checkBox_facebook_ads")
        self.linkedin_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.linkedin_checkbox.setEnabled(False)
        self.linkedin_checkbox.setGeometry(QtCore.QRect(310, 60, 89, 31))
        self.linkedin_checkbox.setObjectName("linkedin_checkbox")
        self.localsapp_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.localsapp_checkbox.setEnabled(False)
        self.localsapp_checkbox.setGeometry(QtCore.QRect(210, 160, 89, 31))
        self.localsapp_checkbox.setObjectName("localsapp_checkbox")
        self.reddit_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.reddit_checkbox.setEnabled(False)
        self.reddit_checkbox.setGeometry(QtCore.QRect(310, 150, 89, 41))
        self.reddit_checkbox.setObjectName("reddit_checkbox")
        self.rumble_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.rumble_checkbox.setEnabled(False)
        self.rumble_checkbox.setGeometry(QtCore.QRect(210, 110, 89, 31))
        self.rumble_checkbox.setObjectName("rumble_checkbox")
        self.twitch_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.twitch_checkbox.setEnabled(False)
        self.twitch_checkbox.setGeometry(QtCore.QRect(310, 10, 89, 31))
        self.twitch_checkbox.setObjectName("twitch_checkbox")
        self.kick_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.kick_checkbox.setGeometry(QtCore.QRect(10, 160, 89, 31))
        self.kick_checkbox.setObjectName("kick_checkbox")
        self.myspace_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.myspace_checkbox.setEnabled(False)
        self.myspace_checkbox.setGeometry(QtCore.QRect(210, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.myspace_checkbox.setFont(font)
        self.myspace_checkbox.setObjectName("myspace_checkbox")
        self.snapchat_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.snapchat_checkbox.setEnabled(False)
        self.snapchat_checkbox.setGeometry(QtCore.QRect(310, 110, 109, 31))
        self.snapchat_checkbox.setObjectName("snapchat_checkbox")
        self.vimeo_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.vimeo_checkbox.setGeometry(QtCore.QRect(110, 160, 89, 31))
        self.vimeo_checkbox.setObjectName("vimeo_checkbox")
        self.pintrest_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.pintrest_checkbox.setEnabled(False)
        self.pintrest_checkbox.setGeometry(QtCore.QRect(400, 10, 89, 31))
        self.pintrest_checkbox.setObjectName("pintrest_checkbox")
        self.patreon_checkbox = QtWidgets.QCheckBox(self.tab_2)
        self.patreon_checkbox.setEnabled(False)
        self.patreon_checkbox.setGeometry(QtCore.QRect(400, 60, 111, 41))
        self.patreon_checkbox.setObjectName("patreon_checkbox")
        self.inbox_tab_widget.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.checkBox_coinbase = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_coinbase.setGeometry(QtCore.QRect(10, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_coinbase.setFont(font)
        self.checkBox_coinbase.setStyleSheet("")
        self.checkBox_coinbase.setObjectName("checkBox_coinbase")
        self.checkBox_hitbtc = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_hitbtc.setGeometry(QtCore.QRect(10, 60, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_hitbtc.setFont(font)
        self.checkBox_hitbtc.setStyleSheet("")
        self.checkBox_hitbtc.setObjectName("checkBox_hitbtc")
        self.checkBox_freebitcoin = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_freebitcoin.setGeometry(QtCore.QRect(10, 110, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_freebitcoin.setFont(font)
        self.checkBox_freebitcoin.setStyleSheet("")
        self.checkBox_freebitcoin.setObjectName("checkBox_freebitcoin")
        self.checkBox_kryptex = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_kryptex.setGeometry(QtCore.QRect(140, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_kryptex.setFont(font)
        self.checkBox_kryptex.setStyleSheet("")
        self.checkBox_kryptex.setObjectName("checkBox_kryptex")
        self.inbox_tab_widget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.checkBox_amazon = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_amazon.setGeometry(QtCore.QRect(10, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_amazon.setFont(font)
        self.checkBox_amazon.setStyleSheet("")
        self.checkBox_amazon.setObjectName("checkBox_amazon")
        self.checkBox_funpay = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_funpay.setGeometry(QtCore.QRect(10, 60, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_funpay.setFont(font)
        self.checkBox_funpay.setStyleSheet("")
        self.checkBox_funpay.setObjectName("checkBox_funpay")
        self.checkBox_humble = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_humble.setGeometry(QtCore.QRect(10, 110, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_humble.setFont(font)
        self.checkBox_humble.setStyleSheet("")
        self.checkBox_humble.setObjectName("checkBox_humble")
        self.temu_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.temu_checkbox.setEnabled(False)
        self.temu_checkbox.setGeometry(QtCore.QRect(140, 110, 129, 41))
        self.temu_checkbox.setObjectName("temu_checkbox")
        self.kleinanzeigen_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.kleinanzeigen_checkbox.setEnabled(False)
        self.kleinanzeigen_checkbox.setGeometry(QtCore.QRect(140, 60, 129, 41))
        self.kleinanzeigen_checkbox.setObjectName("kleinanzeigen_checkbox")
        self.google_play_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.google_play_checkbox.setGeometry(QtCore.QRect(10, 160, 129, 41))
        self.google_play_checkbox.setObjectName("google_play_checkbox")
        self.ebay_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.ebay_checkbox.setEnabled(False)
        self.ebay_checkbox.setGeometry(QtCore.QRect(140, 10, 129, 41))
        self.ebay_checkbox.setObjectName("ebay_checkbox")
        self.vinted_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.vinted_checkbox.setEnabled(False)
        self.vinted_checkbox.setGeometry(QtCore.QRect(140, 160, 129, 41))
        self.vinted_checkbox.setObjectName("vinted_checkbox")
        self.airbnb_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.airbnb_checkbox.setEnabled(False)
        self.airbnb_checkbox.setGeometry(QtCore.QRect(250, 10, 129, 41))
        self.airbnb_checkbox.setObjectName("airbnb_checkbox")
        self.booking_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.booking_checkbox.setEnabled(False)
        self.booking_checkbox.setGeometry(QtCore.QRect(250, 60, 129, 41))
        self.booking_checkbox.setObjectName("booking_checkbox")
        self.fiverr_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.fiverr_checkbox.setEnabled(False)
        self.fiverr_checkbox.setGeometry(QtCore.QRect(250, 110, 129, 41))
        self.fiverr_checkbox.setObjectName("fiverr_checkbox")
        self.walmart_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.walmart_checkbox.setEnabled(False)
        self.walmart_checkbox.setGeometry(QtCore.QRect(250, 160, 129, 41))
        self.walmart_checkbox.setObjectName("walmart_checkbox")
        self.enavto_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.enavto_checkbox.setEnabled(False)
        self.enavto_checkbox.setGeometry(QtCore.QRect(360, 10, 129, 41))
        self.enavto_checkbox.setObjectName("enavto_checkbox")
        self.uber_eats_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.uber_eats_checkbox.setEnabled(False)
        self.uber_eats_checkbox.setGeometry(QtCore.QRect(360, 60, 129, 41))
        self.uber_eats_checkbox.setObjectName("uber_eats_checkbox")
        self.zillow_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.zillow_checkbox.setEnabled(False)
        self.zillow_checkbox.setGeometry(QtCore.QRect(360, 110, 129, 41))
        self.zillow_checkbox.setObjectName("zillow_checkbox")
        self.flipkart_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.flipkart_checkbox.setEnabled(False)
        self.flipkart_checkbox.setGeometry(QtCore.QRect(490, 10, 129, 41))
        self.flipkart_checkbox.setObjectName("flipkart_checkbox")
        self.dh_gate_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.dh_gate_checkbox.setEnabled(False)
        self.dh_gate_checkbox.setGeometry(QtCore.QRect(490, 60, 129, 41))
        self.dh_gate_checkbox.setObjectName("dh_gate_checkbox")
        self.instacart_checkbox = QtWidgets.QCheckBox(self.tab_8)
        self.instacart_checkbox.setEnabled(False)
        self.instacart_checkbox.setGeometry(QtCore.QRect(490, 110, 129, 41))
        self.instacart_checkbox.setObjectName("instacart_checkbox")
        self.inbox_tab_widget.addTab(self.tab_8, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.eharmony_checkbox = QtWidgets.QCheckBox(self.tab_4)
        self.eharmony_checkbox.setEnabled(False)
        self.eharmony_checkbox.setGeometry(QtCore.QRect(20, 44, 129, 31))
        self.eharmony_checkbox.setObjectName("eharmony_checkbox")
        self.ashley_madison_checkbox = QtWidgets.QCheckBox(self.tab_4)
        self.ashley_madison_checkbox.setEnabled(False)
        self.ashley_madison_checkbox.setGeometry(QtCore.QRect(20, 10, 121, 20))
        self.ashley_madison_checkbox.setObjectName("ashley_madison_checkbox")
        self.meetme_checkbox = QtWidgets.QCheckBox(self.tab_4)
        self.meetme_checkbox.setEnabled(False)
        self.meetme_checkbox.setGeometry(QtCore.QRect(310, 10, 129, 20))
        self.meetme_checkbox.setObjectName("meetme_checkbox")
        self.zoosk_checkbox = QtWidgets.QCheckBox(self.tab_4)
        self.zoosk_checkbox.setEnabled(False)
        self.zoosk_checkbox.setGeometry(QtCore.QRect(160, 0, 81, 41))
        self.zoosk_checkbox.setObjectName("zoosk_checkbox")
        self.christan_mingle_checkbox = QtWidgets.QCheckBox(self.tab_4)
        self.christan_mingle_checkbox.setEnabled(False)
        self.christan_mingle_checkbox.setGeometry(QtCore.QRect(310, 40, 129, 31))
        self.christan_mingle_checkbox.setObjectName("christan_mingle_checkbox")
        self.tinder_checkbox = QtWidgets.QCheckBox(self.tab_4)
        self.tinder_checkbox.setEnabled(False)
        self.tinder_checkbox.setGeometry(QtCore.QRect(160, 50, 129, 20))
        self.tinder_checkbox.setObjectName("tinder_checkbox")
        self.inbox_tab_widget.addTab(self.tab_4, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 290, 71, 21))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 320, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 350, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(540, 380, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(700, 290, 81, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(700, 320, 71, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(700, 350, 71, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(700, 380, 71, 21))
        self.label_10.setObjectName("label_10")
        self.stats_box.raise_()
        self.lineEdit_dir.raise_()
        self.lineEdit_proxy.raise_()
        self.lineEdit_ua.raise_()
        self.checkBox_ua.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.progressBar.raise_()
        self.pushButton_dir_logs.raise_()
        self.pushButton_proxies_files.raise_()
        self.pushButton_useragents_file.raise_()
        self.textEdit_console.raise_()
        self.label_3.raise_()
        self.spinBox_thr.raise_()
        self.label_lgbt.raise_()
        self.comboBox_proxy.raise_()
        self.inbox_tab_widget.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.inbox_tab_widget.setCurrentIndex(0)
        self.pushButton_proxies_files.clicked.connect(MainWindow.proxies_file) # type: ignore
        self.pushButton_dir_logs.clicked.connect(MainWindow.dir_logs) # type: ignore
        self.pushButton_useragents_file.clicked.connect(MainWindow.useragents_file) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_dir.setText(_translate("MainWindow", "The path to the logs"))
        self.lineEdit_proxy.setText(_translate("MainWindow", "The path to the proxy"))
        self.lineEdit_ua.setText(_translate("MainWindow", "The path to user agents"))
        self.checkBox_ua.setText(_translate("MainWindow", "Enable"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_dir_logs.setText(_translate("MainWindow", "Choose a path"))
        self.pushButton_proxies_files.setText(_translate("MainWindow", "Choose a path"))
        self.pushButton_useragents_file.setText(_translate("MainWindow", "Choose a path"))
        self.textEdit_console.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Threads"))
        self.comboBox_proxy.setItemText(0, _translate("MainWindow", "off"))
        self.comboBox_proxy.setItemText(1, _translate("MainWindow", "socks4"))
        self.comboBox_proxy.setItemText(2, _translate("MainWindow", "socks5"))
        self.comboBox_proxy.setItemText(3, _translate("MainWindow", "http"))
        self.checkBox_71.setText(_translate("MainWindow", "Mail.Ru"))
        self.checkBox_67.setText(_translate("MainWindow", "Webmail"))
        self.checkBox_69.setText(_translate("MainWindow", "Cpanel"))
        self.checkBox_72.setText(_translate("MainWindow", "Yandex"))
        self.checkBox_66.setText(_translate("MainWindow", "Gmail"))
        self.checkBox_74.setText(_translate("MainWindow", "Office"))
        self.checkBox_73.setText(_translate("MainWindow", "Yahoo"))
        self.checkBox_68.setText(_translate("MainWindow", "Outlook"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.tab_3), _translate("MainWindow", "Inbox"))
        self.reddit_ads__checkbox.setText(_translate("MainWindow", "Reddit Ads"))
        self.craigslist_ads_checkbox.setText(_translate("MainWindow", "Craigslist Ads"))
        self.tinder_ads_checkbox.setText(_translate("MainWindow", "Tinder Ads"))
        self.microsoft_ads_checkbox.setText(_translate("MainWindow", "Microsoft Ads"))
        self.sem_rush_checkbox.setText(_translate("MainWindow", "SEM Rush"))
        self.snapchat_ads_checkbox.setText(_translate("MainWindow", "Snapchat Ads"))
        self.facebookads__checkbox.setText(_translate("MainWindow", "Facebook Ads"))
        self.bing_ads_checkbox.setText(_translate("MainWindow", "Bing Ads"))
        self.ahref_checkbox.setText(_translate("MainWindow", "AHref SEO"))
        self.twitter_ads_checkbox.setText(_translate("MainWindow", "Twitter Ads"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.tab_5), _translate("MainWindow", "Ads"))
        self.checkBox_steam.setText(_translate("MainWindow", "Steam"))
        self.checkBox_roblox.setText(_translate("MainWindow", "Roblox"))
        self.checkBox_battlenet.setText(_translate("MainWindow", "BattleNet"))
        self.checkBox_pathofexile.setText(_translate("MainWindow", "PathofExile"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.tab), _translate("MainWindow", "Games"))
        self.checkBox_instagram.setText(_translate("MainWindow", "Instagram"))
        self.checkBox_tiktok.setText(_translate("MainWindow", "TikTok"))
        self.checkBox_vk.setText(_translate("MainWindow", "VK"))
        self.checkBox_youtube.setText(_translate("MainWindow", "YouTube"))
        self.checkBox_discord.setText(_translate("MainWindow", "Discord"))
        self.checkBox_netflix.setText(_translate("MainWindow", "Netflix"))
        self.checkBox_facebook_ads.setText(_translate("MainWindow", "Facebook"))
        self.linkedin_checkbox.setText(_translate("MainWindow", "LinkedIn"))
        self.localsapp_checkbox.setText(_translate("MainWindow", "Locals"))
        self.reddit_checkbox.setText(_translate("MainWindow", "Reddit"))
        self.rumble_checkbox.setText(_translate("MainWindow", "Rumble"))
        self.twitch_checkbox.setText(_translate("MainWindow", "Twitch"))
        self.kick_checkbox.setText(_translate("MainWindow", "Kick"))
        self.myspace_checkbox.setText(_translate("MainWindow", "Myspace"))
        self.snapchat_checkbox.setText(_translate("MainWindow", "Snapchat"))
        self.vimeo_checkbox.setText(_translate("MainWindow", "Vimeo"))
        self.pintrest_checkbox.setText(_translate("MainWindow", "Pintrest"))
        self.patreon_checkbox.setText(_translate("MainWindow", "Patreon"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.tab_2), _translate("MainWindow", "Social network"))
        self.checkBox_coinbase.setText(_translate("MainWindow", "CoinBase"))
        self.checkBox_hitbtc.setText(_translate("MainWindow", "HitBTC"))
        self.checkBox_freebitcoin.setText(_translate("MainWindow", "FreeBitcoin"))
        self.checkBox_kryptex.setText(_translate("MainWindow", "Kryptex"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.tab_7), _translate("MainWindow", "Crypto wallet"))
        self.checkBox_amazon.setText(_translate("MainWindow", "Amazon"))
        self.checkBox_funpay.setText(_translate("MainWindow", "FunPay"))
        self.checkBox_humble.setText(_translate("MainWindow", "Humble"))
        self.temu_checkbox.setText(_translate("MainWindow", "Temu"))
        self.kleinanzeigen_checkbox.setText(_translate("MainWindow", "Kleinanzeigen"))
        self.google_play_checkbox.setText(_translate("MainWindow", "Google Play"))
        self.ebay_checkbox.setText(_translate("MainWindow", "Ebay"))
        self.vinted_checkbox.setText(_translate("MainWindow", "Vinted"))
        self.airbnb_checkbox.setText(_translate("MainWindow", "AirBNB"))
        self.booking_checkbox.setText(_translate("MainWindow", "Booking.com"))
        self.fiverr_checkbox.setText(_translate("MainWindow", "Fiverr"))
        self.walmart_checkbox.setText(_translate("MainWindow", "Walmart"))
        self.enavto_checkbox.setText(_translate("MainWindow", "Envato Elements"))
        self.uber_eats_checkbox.setText(_translate("MainWindow", "Uber Eats"))
        self.zillow_checkbox.setText(_translate("MainWindow", "Zillow"))
        self.flipkart_checkbox.setText(_translate("MainWindow", "Flipkart"))
        self.dh_gate_checkbox.setText(_translate("MainWindow", "DH Gate"))
        self.instacart_checkbox.setText(_translate("MainWindow", "Instacart"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.tab_8), _translate("MainWindow", "Shop"))
        self.eharmony_checkbox.setText(_translate("MainWindow", "EHarmony"))
        self.ashley_madison_checkbox.setText(_translate("MainWindow", "AshleyMaddison"))
        self.meetme_checkbox.setText(_translate("MainWindow", "MeetMe"))
        self.zoosk_checkbox.setText(_translate("MainWindow", "Zoosk"))
        self.christan_mingle_checkbox.setText(_translate("MainWindow", "ChristanMingle"))
        self.tinder_checkbox.setText(_translate("MainWindow", "Tinder"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.tab_4), _translate("MainWindow", "Daiting"))
        self.label.setText(_translate("MainWindow", "Number of"))
        self.label_4.setText(_translate("MainWindow", "Files:"))
        self.label_5.setText(_translate("MainWindow", "Folders:"))
        self.label_6.setText(_translate("MainWindow", "Cookies:"))
        self.label_7.setText(_translate("MainWindow", "Cookie Stats"))
        self.label_8.setText(_translate("MainWindow", "Live:"))
        self.label_9.setText(_translate("MainWindow", "Dead:"))
        self.label_10.setText(_translate("MainWindow", "Errors:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
