# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 820)
        MainWindow.setMinimumSize(QtCore.QSize(801, 677))
        MainWindow.setMaximumSize(QtCore.QSize(801, 999))
        MainWindow.setSizeIncrement(QtCore.QSize(801, 677))
        MainWindow.setBaseSize(QtCore.QSize(801, 677))
        MainWindow.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dir.setGeometry(QtCore.QRect(10, 280, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Furore")
        font.setPointSize(10)
        self.lineEdit_dir.setFont(font)
        self.lineEdit_dir.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.lineEdit_dir.setObjectName("lineEdit_dir")
        self.lineEdit_proxy = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_proxy.setGeometry(QtCore.QRect(10, 320, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Furore")
        font.setPointSize(10)
        self.lineEdit_proxy.setFont(font)
        self.lineEdit_proxy.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.lineEdit_proxy.setObjectName("lineEdit_proxy")
        self.lineEdit_ua = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ua.setGeometry(QtCore.QRect(10, 360, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Furore")
        font.setPointSize(10)
        self.lineEdit_ua.setFont(font)
        self.lineEdit_ua.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.lineEdit_ua.setObjectName("lineEdit_ua")
        self.checkBox_ua = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ua.setGeometry(QtCore.QRect(440, 360, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        self.checkBox_ua.setFont(font)
        self.checkBox_ua.setStyleSheet("color: #c8c8c8")
        self.checkBox_ua.setObjectName("checkBox_ua")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 740, 601, 51))
        self.label_2.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(620, 740, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Furore")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(180, 750, 421, 31))
        self.progressBar.setStyleSheet("background-color: #181818;\n"
"border: 3px solid #363636;\n"
"color: #c8c8c8")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_dir_logs = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dir_logs.setGeometry(QtCore.QRect(430, 280, 91, 31))
        self.pushButton_dir_logs.setStyleSheet("")
        self.pushButton_dir_logs.setObjectName("pushButton_dir_logs")
        self.pushButton_proxies_files = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_proxies_files.setGeometry(QtCore.QRect(340, 320, 91, 31))
        self.pushButton_proxies_files.setStyleSheet("")
        self.pushButton_proxies_files.setObjectName("pushButton_proxies_files")
        self.pushButton_useragents_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_useragents_file.setGeometry(QtCore.QRect(340, 360, 91, 31))
        self.pushButton_useragents_file.setStyleSheet("")
        self.pushButton_useragents_file.setObjectName("pushButton_useragents_file")
        self.textEdit_console = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_console.setGeometry(QtCore.QRect(10, 20, 781, 251))
        self.textEdit_console.setStyleSheet("background-color: #181818;\n"
"border: 3px solid #363636;\n"
"color: #c8c8c8")
        self.textEdit_console.setObjectName("textEdit_console")
        self.social_network_label = QtWidgets.QLabel(self.centralwidget)
        self.social_network_label.setGeometry(QtCore.QRect(10, 740, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Furore")
        font.setPointSize(10)
        self.social_network_label.setFont(font)
        self.social_network_label.setStyleSheet("")
        self.social_network_label.setObjectName("social_network_label")
        self.spinBox_thr = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_thr.setGeometry(QtCore.QRect(90, 750, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.spinBox_thr.setFont(font)
        self.spinBox_thr.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.spinBox_thr.setObjectName("spinBox_thr")
        self.label_lgbt = QtWidgets.QLabel(self.centralwidget)
        self.label_lgbt.setGeometry(QtCore.QRect(0, 0, 801, 5))
        self.label_lgbt.setText("")
        self.label_lgbt.setScaledContents(True)
        self.label_lgbt.setObjectName("label_lgbt")
        self.comboBox_proxy = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_proxy.setGeometry(QtCore.QRect(440, 320, 71, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.comboBox_proxy.setFont(font)
        self.comboBox_proxy.setStyleSheet("")
        self.comboBox_proxy.setObjectName("comboBox_proxy")
        self.comboBox_proxy.addItem("")
        self.comboBox_proxy.addItem("")
        self.comboBox_proxy.addItem("")
        self.comboBox_proxy.addItem("")
        self.stats_box = QtWidgets.QLabel(self.centralwidget)
        self.stats_box.setGeometry(QtCore.QRect(530, 280, 261, 131))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.stats_box.setFont(font)
        self.stats_box.setStyleSheet("")
        self.stats_box.setText("")
        self.stats_box.setObjectName("stats_box")
        self.inbox_tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.inbox_tab_widget.setGeometry(QtCore.QRect(10, 430, 781, 281))
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.inbox_tab_widget.setFont(font)
        self.inbox_tab_widget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.inbox_tab_widget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.inbox_tab_widget.setAutoFillBackground(False)
        self.inbox_tab_widget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #000000;\n"
"    position: absolute;\n"
"    top: -0.5em;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #000000, stop: 0.4 #000000,\n"
"                                stop: 0.5 #000000, stop: 1.0 #000000);\n"
"    border: 2px solid ;\n"
"    selection-color: rgb(15, 255, 167);\n"
"    border-bottom-color: #000000; /* same as the pane color */\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"    min-width: 8ex;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #000000, stop: 0.4 #000000,\n"
"                                stop: 0.5 #000000, stop: 1.0 #000000);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #00def2;\n"
"    border-bottom-color: #00def2; /* same as pane color */\n"
"}")
        self.inbox_tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.inbox_tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.inbox_tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.inbox_tab_widget.setMovable(False)
        self.inbox_tab_widget.setTabBarAutoHide(False)
        self.inbox_tab_widget.setObjectName("inbox_tab_widget")
        self.inbox_tab = QtWidgets.QWidget()
        self.inbox_tab.setObjectName("inbox_tab")
        self.widget = QtWidgets.QWidget(self.inbox_tab)
        self.widget.setGeometry(QtCore.QRect(9, 10, 761, 221))
        self.widget.setObjectName("widget")
        self.inbox_checkbox_gridlayout = QtWidgets.QGridLayout(self.widget)
        self.inbox_checkbox_gridlayout.setContentsMargins(0, 0, 0, 0)
        self.inbox_checkbox_gridlayout.setObjectName("inbox_checkbox_gridlayout")
        self.gmail_inbox_checkbox = QtWidgets.QCheckBox(self.widget)
        self.gmail_inbox_checkbox.setEnabled(False)
        self.gmail_inbox_checkbox.setObjectName("gmail_inbox_checkbox")
        self.inbox_checkbox_gridlayout.addWidget(self.gmail_inbox_checkbox, 0, 0, 1, 1)
        self.yandex_checkbox = QtWidgets.QCheckBox(self.widget)
        self.yandex_checkbox.setEnabled(False)
        self.yandex_checkbox.setObjectName("yandex_checkbox")
        self.inbox_checkbox_gridlayout.addWidget(self.yandex_checkbox, 0, 1, 1, 1)
        self.yahoo_checkbox = QtWidgets.QCheckBox(self.widget)
        self.yahoo_checkbox.setEnabled(False)
        self.yahoo_checkbox.setObjectName("yahoo_checkbox")
        self.inbox_checkbox_gridlayout.addWidget(self.yahoo_checkbox, 1, 0, 1, 1)
        self.outlook_checkbox = QtWidgets.QCheckBox(self.widget)
        self.outlook_checkbox.setEnabled(False)
        self.outlook_checkbox.setObjectName("outlook_checkbox")
        self.inbox_checkbox_gridlayout.addWidget(self.outlook_checkbox, 1, 1, 1, 1)
        self.webmail_checkbox = QtWidgets.QCheckBox(self.widget)
        self.webmail_checkbox.setEnabled(False)
        self.webmail_checkbox.setObjectName("webmail_checkbox")
        self.inbox_checkbox_gridlayout.addWidget(self.webmail_checkbox, 2, 0, 1, 1)
        self.mailru_checkbox = QtWidgets.QCheckBox(self.widget)
        self.mailru_checkbox.setEnabled(False)
        self.mailru_checkbox.setObjectName("mailru_checkbox")
        self.inbox_checkbox_gridlayout.addWidget(self.mailru_checkbox, 2, 1, 1, 1)
        self.cpanel_checkbox = QtWidgets.QCheckBox(self.widget)
        self.cpanel_checkbox.setEnabled(False)
        self.cpanel_checkbox.setObjectName("cpanel_checkbox")
        self.inbox_checkbox_gridlayout.addWidget(self.cpanel_checkbox, 3, 0, 1, 1)
        self.office_checkbox = QtWidgets.QCheckBox(self.widget)
        self.office_checkbox.setEnabled(False)
        self.office_checkbox.setObjectName("office_checkbox")
        self.inbox_checkbox_gridlayout.addWidget(self.office_checkbox, 3, 1, 1, 1)
        self.inbox_tab_widget.addTab(self.inbox_tab, "")
        self.ads_tab = QtWidgets.QWidget()
        self.ads_tab.setObjectName("ads_tab")
        self.widget1 = QtWidgets.QWidget(self.ads_tab)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 761, 211))
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bing_ads_checkbox = QtWidgets.QCheckBox(self.widget1)
        self.bing_ads_checkbox.setEnabled(False)
        self.bing_ads_checkbox.setObjectName("bing_ads_checkbox")
        self.gridLayout_3.addWidget(self.bing_ads_checkbox, 0, 0, 1, 1)
        self.reddit_ads__checkbox = QtWidgets.QCheckBox(self.widget1)
        self.reddit_ads__checkbox.setEnabled(False)
        self.reddit_ads__checkbox.setObjectName("reddit_ads__checkbox")
        self.gridLayout_3.addWidget(self.reddit_ads__checkbox, 0, 1, 1, 1)
        self.ahref_checkbox = QtWidgets.QCheckBox(self.widget1)
        self.ahref_checkbox.setEnabled(False)
        self.ahref_checkbox.setObjectName("ahref_checkbox")
        self.gridLayout_3.addWidget(self.ahref_checkbox, 0, 2, 1, 1)
        self.snapchat_ads_checkbox = QtWidgets.QCheckBox(self.widget1)
        self.snapchat_ads_checkbox.setEnabled(False)
        self.snapchat_ads_checkbox.setObjectName("snapchat_ads_checkbox")
        self.gridLayout_3.addWidget(self.snapchat_ads_checkbox, 1, 0, 1, 1)
        self.tinder_ads_checkbox = QtWidgets.QCheckBox(self.widget1)
        self.tinder_ads_checkbox.setEnabled(False)
        self.tinder_ads_checkbox.setObjectName("tinder_ads_checkbox")
        self.gridLayout_3.addWidget(self.tinder_ads_checkbox, 1, 1, 1, 1)
        self.twitter_ads_checkbox = QtWidgets.QCheckBox(self.widget1)
        self.twitter_ads_checkbox.setEnabled(False)
        self.twitter_ads_checkbox.setObjectName("twitter_ads_checkbox")
        self.gridLayout_3.addWidget(self.twitter_ads_checkbox, 1, 2, 1, 1)
        self.sem_rush_checkbox = QtWidgets.QCheckBox(self.widget1)
        self.sem_rush_checkbox.setEnabled(False)
        self.sem_rush_checkbox.setObjectName("sem_rush_checkbox")
        self.gridLayout_3.addWidget(self.sem_rush_checkbox, 2, 0, 1, 1)
        self.craigslist_ads_checkbox = QtWidgets.QCheckBox(self.widget1)
        self.craigslist_ads_checkbox.setEnabled(False)
        self.craigslist_ads_checkbox.setObjectName("craigslist_ads_checkbox")
        self.gridLayout_3.addWidget(self.craigslist_ads_checkbox, 3, 0, 1, 1)
        self.facebookads__checkbox = QtWidgets.QCheckBox(self.widget1)
        self.facebookads__checkbox.setObjectName("facebookads__checkbox")
        self.gridLayout_3.addWidget(self.facebookads__checkbox, 3, 1, 1, 1)
        self.microsoft_ads_checkbox = QtWidgets.QCheckBox(self.widget1)
        self.microsoft_ads_checkbox.setEnabled(False)
        self.microsoft_ads_checkbox.setObjectName("microsoft_ads_checkbox")
        self.gridLayout_3.addWidget(self.microsoft_ads_checkbox, 2, 2, 1, 1)
        self.inbox_tab_widget.addTab(self.ads_tab, "")
        self.game_tab = QtWidgets.QWidget()
        self.game_tab.setObjectName("game_tab")
        self.widget2 = QtWidgets.QWidget(self.game_tab)
        self.widget2.setGeometry(QtCore.QRect(10, 10, 761, 201))
        self.widget2.setObjectName("widget2")
        self.game_checkbox_gridlayout = QtWidgets.QGridLayout(self.widget2)
        self.game_checkbox_gridlayout.setContentsMargins(0, 0, 0, 0)
        self.game_checkbox_gridlayout.setObjectName("game_checkbox_gridlayout")
        self.checkBox_steam = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_steam.setFont(font)
        self.checkBox_steam.setStyleSheet("")
        self.checkBox_steam.setObjectName("checkBox_steam")
        self.game_checkbox_gridlayout.addWidget(self.checkBox_steam, 0, 0, 1, 1)
        self.checkBox_pathofexile = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_pathofexile.setFont(font)
        self.checkBox_pathofexile.setStyleSheet("")
        self.checkBox_pathofexile.setObjectName("checkBox_pathofexile")
        self.game_checkbox_gridlayout.addWidget(self.checkBox_pathofexile, 0, 1, 1, 1)
        self.checkBox_roblox = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_roblox.setFont(font)
        self.checkBox_roblox.setStyleSheet("")
        self.checkBox_roblox.setObjectName("checkBox_roblox")
        self.game_checkbox_gridlayout.addWidget(self.checkBox_roblox, 1, 0, 1, 1)
        self.checkBox_battlenet = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_battlenet.setFont(font)
        self.checkBox_battlenet.setStyleSheet("")
        self.checkBox_battlenet.setObjectName("checkBox_battlenet")
        self.game_checkbox_gridlayout.addWidget(self.checkBox_battlenet, 2, 0, 1, 1)
        self.inbox_tab_widget.addTab(self.game_tab, "")
        self.social_network_tab = QtWidgets.QWidget()
        self.social_network_tab.setObjectName("social_network_tab")
        self.layoutWidget = QtWidgets.QWidget(self.social_network_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_instagram = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_instagram.setFont(font)
        self.checkBox_instagram.setStyleSheet("")
        self.checkBox_instagram.setObjectName("checkBox_instagram")
        self.gridLayout.addWidget(self.checkBox_instagram, 0, 0, 1, 1)
        self.myspace_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.myspace_checkbox.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.myspace_checkbox.setFont(font)
        self.myspace_checkbox.setObjectName("myspace_checkbox")
        self.gridLayout.addWidget(self.myspace_checkbox, 2, 2, 1, 1)
        self.reddit_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.reddit_checkbox.setEnabled(False)
        self.reddit_checkbox.setObjectName("reddit_checkbox")
        self.gridLayout.addWidget(self.reddit_checkbox, 1, 2, 1, 1)
        self.checkBox_discord = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_discord.setFont(font)
        self.checkBox_discord.setStyleSheet("")
        self.checkBox_discord.setObjectName("checkBox_discord")
        self.gridLayout.addWidget(self.checkBox_discord, 2, 1, 1, 1)
        self.kick_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.kick_checkbox.setObjectName("kick_checkbox")
        self.gridLayout.addWidget(self.kick_checkbox, 5, 0, 1, 1)
        self.checkBox_facebook_ads = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_facebook_ads.setFont(font)
        self.checkBox_facebook_ads.setStyleSheet("")
        self.checkBox_facebook_ads.setObjectName("checkBox_facebook_ads")
        self.gridLayout.addWidget(self.checkBox_facebook_ads, 0, 2, 1, 1)
        self.checkBox_tiktok = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_tiktok.setFont(font)
        self.checkBox_tiktok.setStyleSheet("")
        self.checkBox_tiktok.setObjectName("checkBox_tiktok")
        self.gridLayout.addWidget(self.checkBox_tiktok, 2, 0, 1, 1)
        self.pintrest_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.pintrest_checkbox.setEnabled(False)
        self.pintrest_checkbox.setObjectName("pintrest_checkbox")
        self.gridLayout.addWidget(self.pintrest_checkbox, 1, 0, 1, 1)
        self.checkBox_youtube = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_youtube.setFont(font)
        self.checkBox_youtube.setStyleSheet("")
        self.checkBox_youtube.setObjectName("checkBox_youtube")
        self.gridLayout.addWidget(self.checkBox_youtube, 0, 1, 1, 1)
        self.vimeo_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.vimeo_checkbox.setObjectName("vimeo_checkbox")
        self.gridLayout.addWidget(self.vimeo_checkbox, 5, 1, 1, 1)
        self.rumble_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.rumble_checkbox.setEnabled(False)
        self.rumble_checkbox.setObjectName("rumble_checkbox")
        self.gridLayout.addWidget(self.rumble_checkbox, 5, 2, 1, 1)
        self.localsapp_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.localsapp_checkbox.setEnabled(False)
        self.localsapp_checkbox.setObjectName("localsapp_checkbox")
        self.gridLayout.addWidget(self.localsapp_checkbox, 5, 3, 1, 1)
        self.snapchat_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.snapchat_checkbox.setEnabled(False)
        self.snapchat_checkbox.setObjectName("snapchat_checkbox")
        self.gridLayout.addWidget(self.snapchat_checkbox, 1, 3, 1, 1)
        self.patreon_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.patreon_checkbox.setEnabled(False)
        self.patreon_checkbox.setObjectName("patreon_checkbox")
        self.gridLayout.addWidget(self.patreon_checkbox, 5, 4, 1, 1)
        self.checkBox_netflix = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_netflix.setFont(font)
        self.checkBox_netflix.setStyleSheet("")
        self.checkBox_netflix.setObjectName("checkBox_netflix")
        self.gridLayout.addWidget(self.checkBox_netflix, 1, 1, 1, 1)
        self.checkBox_vk = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_vk.setFont(font)
        self.checkBox_vk.setStyleSheet("")
        self.checkBox_vk.setObjectName("checkBox_vk")
        self.gridLayout.addWidget(self.checkBox_vk, 1, 4, 1, 1)
        self.twitch_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.twitch_checkbox.setEnabled(False)
        self.twitch_checkbox.setObjectName("twitch_checkbox")
        self.gridLayout.addWidget(self.twitch_checkbox, 0, 3, 1, 1)
        self.linkedin_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.linkedin_checkbox.setEnabled(False)
        self.linkedin_checkbox.setObjectName("linkedin_checkbox")
        self.gridLayout.addWidget(self.linkedin_checkbox, 2, 3, 1, 1)
        self.inbox_tab_widget.addTab(self.social_network_tab, "")
        self.crypto_wallets_tab = QtWidgets.QWidget()
        self.crypto_wallets_tab.setObjectName("crypto_wallets_tab")
        self.widget3 = QtWidgets.QWidget(self.crypto_wallets_tab)
        self.widget3.setGeometry(QtCore.QRect(10, 10, 761, 221))
        self.widget3.setObjectName("widget3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_coinbase = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_coinbase.setFont(font)
        self.checkBox_coinbase.setStyleSheet("")
        self.checkBox_coinbase.setObjectName("checkBox_coinbase")
        self.gridLayout_6.addWidget(self.checkBox_coinbase, 0, 0, 1, 1)
        self.checkBox_kryptex = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_kryptex.setFont(font)
        self.checkBox_kryptex.setStyleSheet("")
        self.checkBox_kryptex.setObjectName("checkBox_kryptex")
        self.gridLayout_6.addWidget(self.checkBox_kryptex, 0, 1, 1, 1)
        self.checkBox_hitbtc = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_hitbtc.setFont(font)
        self.checkBox_hitbtc.setStyleSheet("")
        self.checkBox_hitbtc.setObjectName("checkBox_hitbtc")
        self.gridLayout_6.addWidget(self.checkBox_hitbtc, 1, 0, 1, 1)
        self.checkBox_freebitcoin = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_freebitcoin.setFont(font)
        self.checkBox_freebitcoin.setStyleSheet("")
        self.checkBox_freebitcoin.setObjectName("checkBox_freebitcoin")
        self.gridLayout_6.addWidget(self.checkBox_freebitcoin, 2, 0, 1, 1)
        self.inbox_tab_widget.addTab(self.crypto_wallets_tab, "")
        self.shopping_tab = QtWidgets.QWidget()
        self.shopping_tab.setObjectName("shopping_tab")
        self.layoutWidget1 = QtWidgets.QWidget(self.shopping_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 731, 211))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_amazon = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_amazon.setFont(font)
        self.checkBox_amazon.setStyleSheet("")
        self.checkBox_amazon.setObjectName("checkBox_amazon")
        self.gridLayout_2.addWidget(self.checkBox_amazon, 0, 0, 1, 1)
        self.ebay_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ebay_checkbox.setEnabled(False)
        self.ebay_checkbox.setObjectName("ebay_checkbox")
        self.gridLayout_2.addWidget(self.ebay_checkbox, 0, 1, 1, 1)
        self.airbnb_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.airbnb_checkbox.setEnabled(False)
        self.airbnb_checkbox.setObjectName("airbnb_checkbox")
        self.gridLayout_2.addWidget(self.airbnb_checkbox, 0, 2, 1, 1)
        self.envato_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.envato_checkbox.setEnabled(False)
        self.envato_checkbox.setObjectName("envato_checkbox")
        self.gridLayout_2.addWidget(self.envato_checkbox, 0, 3, 1, 1)
        self.flipkart_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.flipkart_checkbox.setEnabled(False)
        self.flipkart_checkbox.setObjectName("flipkart_checkbox")
        self.gridLayout_2.addWidget(self.flipkart_checkbox, 0, 4, 1, 1)
        self.checkBox_funpay = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_funpay.setFont(font)
        self.checkBox_funpay.setStyleSheet("")
        self.checkBox_funpay.setObjectName("checkBox_funpay")
        self.gridLayout_2.addWidget(self.checkBox_funpay, 1, 0, 1, 1)
        self.kleinanzeigen_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.kleinanzeigen_checkbox.setEnabled(False)
        self.kleinanzeigen_checkbox.setObjectName("kleinanzeigen_checkbox")
        self.gridLayout_2.addWidget(self.kleinanzeigen_checkbox, 1, 1, 1, 1)
        self.booking_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.booking_checkbox.setEnabled(False)
        self.booking_checkbox.setObjectName("booking_checkbox")
        self.gridLayout_2.addWidget(self.booking_checkbox, 1, 2, 1, 1)
        self.uber_eats_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.uber_eats_checkbox.setEnabled(False)
        self.uber_eats_checkbox.setObjectName("uber_eats_checkbox")
        self.gridLayout_2.addWidget(self.uber_eats_checkbox, 1, 3, 1, 1)
        self.dh_gate_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.dh_gate_checkbox.setEnabled(False)
        self.dh_gate_checkbox.setObjectName("dh_gate_checkbox")
        self.gridLayout_2.addWidget(self.dh_gate_checkbox, 1, 4, 1, 1)
        self.checkBox_humble = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Furore")
        self.checkBox_humble.setFont(font)
        self.checkBox_humble.setStyleSheet("")
        self.checkBox_humble.setObjectName("checkBox_humble")
        self.gridLayout_2.addWidget(self.checkBox_humble, 2, 0, 1, 1)
        self.temu_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.temu_checkbox.setEnabled(False)
        self.temu_checkbox.setObjectName("temu_checkbox")
        self.gridLayout_2.addWidget(self.temu_checkbox, 2, 1, 1, 1)
        self.fiverr_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.fiverr_checkbox.setEnabled(False)
        self.fiverr_checkbox.setObjectName("fiverr_checkbox")
        self.gridLayout_2.addWidget(self.fiverr_checkbox, 2, 2, 1, 1)
        self.zillow_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.zillow_checkbox.setEnabled(False)
        self.zillow_checkbox.setObjectName("zillow_checkbox")
        self.gridLayout_2.addWidget(self.zillow_checkbox, 2, 3, 1, 1)
        self.instacart_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.instacart_checkbox.setEnabled(False)
        self.instacart_checkbox.setObjectName("instacart_checkbox")
        self.gridLayout_2.addWidget(self.instacart_checkbox, 2, 4, 1, 1)
        self.google_play_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.google_play_checkbox.setObjectName("google_play_checkbox")
        self.gridLayout_2.addWidget(self.google_play_checkbox, 3, 0, 1, 1)
        self.vinted_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.vinted_checkbox.setEnabled(False)
        self.vinted_checkbox.setObjectName("vinted_checkbox")
        self.gridLayout_2.addWidget(self.vinted_checkbox, 3, 1, 1, 1)
        self.walmart_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.walmart_checkbox.setEnabled(False)
        self.walmart_checkbox.setObjectName("walmart_checkbox")
        self.gridLayout_2.addWidget(self.walmart_checkbox, 3, 2, 1, 1)
        self.inbox_tab_widget.addTab(self.shopping_tab, "")
        self.daiting_tab = QtWidgets.QWidget()
        self.daiting_tab.setObjectName("daiting_tab")
        self.widget4 = QtWidgets.QWidget(self.daiting_tab)
        self.widget4.setGeometry(QtCore.QRect(20, 0, 751, 221))
        self.widget4.setObjectName("widget4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ashley_madison_checkbox = QtWidgets.QCheckBox(self.widget4)
        self.ashley_madison_checkbox.setEnabled(False)
        self.ashley_madison_checkbox.setObjectName("ashley_madison_checkbox")
        self.gridLayout_5.addWidget(self.ashley_madison_checkbox, 0, 0, 1, 1)
        self.zoosk_checkbox = QtWidgets.QCheckBox(self.widget4)
        self.zoosk_checkbox.setEnabled(False)
        self.zoosk_checkbox.setObjectName("zoosk_checkbox")
        self.gridLayout_5.addWidget(self.zoosk_checkbox, 0, 1, 1, 1)
        self.meetme_checkbox = QtWidgets.QCheckBox(self.widget4)
        self.meetme_checkbox.setEnabled(False)
        self.meetme_checkbox.setObjectName("meetme_checkbox")
        self.gridLayout_5.addWidget(self.meetme_checkbox, 0, 2, 1, 1)
        self.eharmony_checkbox = QtWidgets.QCheckBox(self.widget4)
        self.eharmony_checkbox.setEnabled(False)
        self.eharmony_checkbox.setObjectName("eharmony_checkbox")
        self.gridLayout_5.addWidget(self.eharmony_checkbox, 1, 0, 1, 1)
        self.tinder_checkbox = QtWidgets.QCheckBox(self.widget4)
        self.tinder_checkbox.setEnabled(False)
        self.tinder_checkbox.setObjectName("tinder_checkbox")
        self.gridLayout_5.addWidget(self.tinder_checkbox, 1, 1, 1, 1)
        self.christan_mingle_checkbox = QtWidgets.QCheckBox(self.widget4)
        self.christan_mingle_checkbox.setEnabled(False)
        self.christan_mingle_checkbox.setObjectName("christan_mingle_checkbox")
        self.gridLayout_5.addWidget(self.christan_mingle_checkbox, 1, 2, 1, 1)
        self.inbox_tab_widget.addTab(self.daiting_tab, "")
        self.number_of_label = QtWidgets.QLabel(self.centralwidget)
        self.number_of_label.setGeometry(QtCore.QRect(540, 280, 71, 31))
        self.number_of_label.setObjectName("number_of_label")
        self.files_label = QtWidgets.QLabel(self.centralwidget)
        self.files_label.setGeometry(QtCore.QRect(540, 310, 71, 31))
        self.files_label.setObjectName("files_label")
        self.folders_label = QtWidgets.QLabel(self.centralwidget)
        self.folders_label.setGeometry(QtCore.QRect(540, 340, 71, 31))
        self.folders_label.setObjectName("folders_label")
        self.cookies_label = QtWidgets.QLabel(self.centralwidget)
        self.cookies_label.setGeometry(QtCore.QRect(540, 380, 71, 21))
        self.cookies_label.setObjectName("cookies_label")
        self.cookie_stats_label = QtWidgets.QLabel(self.centralwidget)
        self.cookie_stats_label.setGeometry(QtCore.QRect(700, 290, 81, 21))
        self.cookie_stats_label.setObjectName("cookie_stats_label")
        self.live_label = QtWidgets.QLabel(self.centralwidget)
        self.live_label.setGeometry(QtCore.QRect(700, 320, 71, 21))
        self.live_label.setObjectName("live_label")
        self.dead_label = QtWidgets.QLabel(self.centralwidget)
        self.dead_label.setGeometry(QtCore.QRect(700, 350, 71, 21))
        self.dead_label.setObjectName("dead_label")
        self.errors_label = QtWidgets.QLabel(self.centralwidget)
        self.errors_label.setGeometry(QtCore.QRect(700, 380, 71, 21))
        self.errors_label.setObjectName("errors_label")
        self.stats_box.raise_()
        self.lineEdit_dir.raise_()
        self.lineEdit_proxy.raise_()
        self.lineEdit_ua.raise_()
        self.checkBox_ua.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.progressBar.raise_()
        self.pushButton_dir_logs.raise_()
        self.pushButton_proxies_files.raise_()
        self.pushButton_useragents_file.raise_()
        self.textEdit_console.raise_()
        self.social_network_label.raise_()
        self.spinBox_thr.raise_()
        self.label_lgbt.raise_()
        self.comboBox_proxy.raise_()
        self.inbox_tab_widget.raise_()
        self.number_of_label.raise_()
        self.files_label.raise_()
        self.folders_label.raise_()
        self.cookies_label.raise_()
        self.cookie_stats_label.raise_()
        self.live_label.raise_()
        self.dead_label.raise_()
        self.errors_label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.inbox_tab_widget.setCurrentIndex(0)
        self.pushButton_proxies_files.clicked.connect(MainWindow.proxies_file) # type: ignore
        self.pushButton_dir_logs.clicked.connect(MainWindow.dir_logs) # type: ignore
        self.pushButton_useragents_file.clicked.connect(MainWindow.useragents_file) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_dir.setText(_translate("MainWindow", "The path to the logs"))
        self.lineEdit_proxy.setText(_translate("MainWindow", "The path to the proxy"))
        self.lineEdit_ua.setText(_translate("MainWindow", "The path to user agents"))
        self.checkBox_ua.setText(_translate("MainWindow", "Enable"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_dir_logs.setText(_translate("MainWindow", "Choose a path"))
        self.pushButton_proxies_files.setText(_translate("MainWindow", "Choose a path"))
        self.pushButton_useragents_file.setText(_translate("MainWindow", "Choose a path"))
        self.textEdit_console.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_console.setPlaceholderText(_translate("MainWindow", "Diamond Checker - A Cookie Checker Brought To You By DiamondSorter - An Opensourced.Pro Project"))
        self.social_network_label.setText(_translate("MainWindow", "Threads"))
        self.comboBox_proxy.setItemText(0, _translate("MainWindow", "off"))
        self.comboBox_proxy.setItemText(1, _translate("MainWindow", "socks4"))
        self.comboBox_proxy.setItemText(2, _translate("MainWindow", "socks5"))
        self.comboBox_proxy.setItemText(3, _translate("MainWindow", "http"))
        self.gmail_inbox_checkbox.setText(_translate("MainWindow", "Gmail"))
        self.yandex_checkbox.setText(_translate("MainWindow", "Yandex"))
        self.yahoo_checkbox.setText(_translate("MainWindow", "Yahoo"))
        self.outlook_checkbox.setText(_translate("MainWindow", "Outlook"))
        self.webmail_checkbox.setText(_translate("MainWindow", "Webmail"))
        self.mailru_checkbox.setText(_translate("MainWindow", "Mail.Ru"))
        self.cpanel_checkbox.setText(_translate("MainWindow", "Cpanel"))
        self.office_checkbox.setText(_translate("MainWindow", "Office"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.inbox_tab), _translate("MainWindow", "Inbox"))
        self.bing_ads_checkbox.setText(_translate("MainWindow", "Bing Ads"))
        self.reddit_ads__checkbox.setText(_translate("MainWindow", "Reddit Ads"))
        self.ahref_checkbox.setText(_translate("MainWindow", "AHref SEO"))
        self.snapchat_ads_checkbox.setText(_translate("MainWindow", "Snapchat Ads"))
        self.tinder_ads_checkbox.setText(_translate("MainWindow", "Tinder Ads"))
        self.twitter_ads_checkbox.setText(_translate("MainWindow", "Twitter Ads"))
        self.sem_rush_checkbox.setText(_translate("MainWindow", "SEM Rush"))
        self.craigslist_ads_checkbox.setText(_translate("MainWindow", "Craigslist Ads"))
        self.facebookads__checkbox.setText(_translate("MainWindow", "Facebook Ads"))
        self.microsoft_ads_checkbox.setText(_translate("MainWindow", "Microsoft Ads"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.ads_tab), _translate("MainWindow", "Ads"))
        self.checkBox_steam.setText(_translate("MainWindow", "Steam"))
        self.checkBox_pathofexile.setText(_translate("MainWindow", "PathofExile"))
        self.checkBox_roblox.setText(_translate("MainWindow", "Roblox"))
        self.checkBox_battlenet.setText(_translate("MainWindow", "BattleNet"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.game_tab), _translate("MainWindow", "Games"))
        self.checkBox_instagram.setText(_translate("MainWindow", "Instagram"))
        self.myspace_checkbox.setText(_translate("MainWindow", "Myspace"))
        self.reddit_checkbox.setText(_translate("MainWindow", "Reddit"))
        self.checkBox_discord.setText(_translate("MainWindow", "Discord"))
        self.kick_checkbox.setText(_translate("MainWindow", "Kick"))
        self.checkBox_facebook_ads.setText(_translate("MainWindow", "Facebook"))
        self.checkBox_tiktok.setText(_translate("MainWindow", "TikTok"))
        self.pintrest_checkbox.setText(_translate("MainWindow", "Pintrest"))
        self.checkBox_youtube.setText(_translate("MainWindow", "YouTube"))
        self.vimeo_checkbox.setText(_translate("MainWindow", "Vimeo"))
        self.rumble_checkbox.setText(_translate("MainWindow", "Rumble"))
        self.localsapp_checkbox.setText(_translate("MainWindow", "Locals"))
        self.snapchat_checkbox.setText(_translate("MainWindow", "Snapchat"))
        self.patreon_checkbox.setText(_translate("MainWindow", "Patreon"))
        self.checkBox_netflix.setText(_translate("MainWindow", "Netflix"))
        self.checkBox_vk.setText(_translate("MainWindow", "VK"))
        self.twitch_checkbox.setText(_translate("MainWindow", "Twitch"))
        self.linkedin_checkbox.setText(_translate("MainWindow", "LinkedIn"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.social_network_tab), _translate("MainWindow", "Social network"))
        self.checkBox_coinbase.setText(_translate("MainWindow", "CoinBase"))
        self.checkBox_kryptex.setText(_translate("MainWindow", "Kryptex"))
        self.checkBox_hitbtc.setText(_translate("MainWindow", "HitBTC"))
        self.checkBox_freebitcoin.setText(_translate("MainWindow", "FreeBitcoin"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.crypto_wallets_tab), _translate("MainWindow", "Crypto wallet"))
        self.checkBox_amazon.setText(_translate("MainWindow", "Amazon"))
        self.ebay_checkbox.setText(_translate("MainWindow", "Ebay"))
        self.airbnb_checkbox.setText(_translate("MainWindow", "AirBNB"))
        self.envato_checkbox.setText(_translate("MainWindow", "Envato Elements"))
        self.flipkart_checkbox.setText(_translate("MainWindow", "Flipkart"))
        self.checkBox_funpay.setText(_translate("MainWindow", "FunPay"))
        self.kleinanzeigen_checkbox.setText(_translate("MainWindow", "Kleinanzeigen"))
        self.booking_checkbox.setText(_translate("MainWindow", "Booking.com"))
        self.uber_eats_checkbox.setText(_translate("MainWindow", "Uber Eats"))
        self.dh_gate_checkbox.setText(_translate("MainWindow", "DH Gate"))
        self.checkBox_humble.setText(_translate("MainWindow", "Humble"))
        self.temu_checkbox.setText(_translate("MainWindow", "Temu"))
        self.fiverr_checkbox.setText(_translate("MainWindow", "Fiverr"))
        self.zillow_checkbox.setText(_translate("MainWindow", "Zillow"))
        self.instacart_checkbox.setText(_translate("MainWindow", "Instacart"))
        self.google_play_checkbox.setText(_translate("MainWindow", "Google Play"))
        self.vinted_checkbox.setText(_translate("MainWindow", "Vinted"))
        self.walmart_checkbox.setText(_translate("MainWindow", "Walmart"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.shopping_tab), _translate("MainWindow", "Shop"))
        self.ashley_madison_checkbox.setText(_translate("MainWindow", "AshleyMaddison"))
        self.zoosk_checkbox.setText(_translate("MainWindow", "Zoosk"))
        self.meetme_checkbox.setText(_translate("MainWindow", "MeetMe"))
        self.eharmony_checkbox.setText(_translate("MainWindow", "EHarmony"))
        self.tinder_checkbox.setText(_translate("MainWindow", "Tinder"))
        self.christan_mingle_checkbox.setText(_translate("MainWindow", "ChristanMingle"))
        self.inbox_tab_widget.setTabText(self.inbox_tab_widget.indexOf(self.daiting_tab), _translate("MainWindow", "Daiting"))
        self.number_of_label.setText(_translate("MainWindow", "Number of:"))
        self.files_label.setText(_translate("MainWindow", "Files:"))
        self.folders_label.setText(_translate("MainWindow", "Folders:"))
        self.cookies_label.setText(_translate("MainWindow", "Cookies:"))
        self.cookie_stats_label.setText(_translate("MainWindow", "Cookie Stats:"))
        self.live_label.setText(_translate("MainWindow", "Live:"))
        self.dead_label.setText(_translate("MainWindow", "Dead:"))
        self.errors_label.setText(_translate("MainWindow", "Errors:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
