from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5 import QtWidgets

class Ui_CookieWindow(object):
    def setupUi(self, CookieWindow):
        CookieWindow.setObjectName("CookieWindow")
        CookieWindow.resize(974, 640)
        CookieWindow.setStyleSheet("QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QTreeView,\n"
"QListView,\n"
"QLineEdit,\n"
"QComboBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.dockWidget_2 = QtWidgets.QDockWidget(CookieWindow)
        self.dockWidget_2.setGeometry(QtCore.QRect(0, 0, 91, 625))
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.combos = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.combos.setGeometry(QtCore.QRect(0, 0, 80, 24))
        self.combos.setObjectName("combos")
        self.pushButton_19 = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButton_19.setGeometry(QtCore.QRect(0, 90, 81, 24))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 210, 71, 24))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButton_21.setGeometry(QtCore.QRect(0, 540, 81, 24))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButton_22.setGeometry(QtCore.QRect(0, 570, 81, 24))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 60, 81, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 30, 81, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        self.columnView = QtWidgets.QColumnView(CookieWindow)
        self.columnView.setGeometry(QtCore.QRect(110, 10, 811, 261))
        self.columnView.setObjectName("columnView")
        self.tabWidget = QtWidgets.QTabWidget(CookieWindow)
        self.tabWidget.setGeometry(QtCore.QRect(110, 280, 851, 331))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(240, 0, 301, 21))
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(100, 0, 101, 20))
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 0, 80, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(110, 30, 301, 21))
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(80, 30, 31, 20))
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 30, 72, 24))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 180, 771, 111))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.checkBox_5 = QtWidgets.QCheckBox(self.page)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 0, 91, 22))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.page)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 20, 101, 22))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_8 = QtWidgets.QCheckBox(self.page)
        self.checkBox_8.setGeometry(QtCore.QRect(10, 40, 61, 22))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.page)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 60, 71, 22))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_12 = QtWidgets.QCheckBox(self.page)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 80, 131, 22))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.page)
        self.checkBox_13.setGeometry(QtCore.QRect(290, 0, 111, 22))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.page)
        self.checkBox_14.setGeometry(QtCore.QRect(290, 20, 111, 22))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_16 = QtWidgets.QCheckBox(self.page)
        self.checkBox_16.setGeometry(QtCore.QRect(290, 40, 111, 22))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_18 = QtWidgets.QCheckBox(self.page)
        self.checkBox_18.setGeometry(QtCore.QRect(290, 80, 111, 22))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.page)
        self.checkBox_19.setGeometry(QtCore.QRect(290, 60, 111, 22))
        self.checkBox_19.setObjectName("checkBox_19")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.checkBox_20 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_20.setGeometry(QtCore.QRect(10, 10, 101, 22))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_28 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_28.setGeometry(QtCore.QRect(10, 30, 101, 22))
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_37 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_37.setGeometry(QtCore.QRect(10, 50, 131, 22))
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_39 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_39.setGeometry(QtCore.QRect(200, 10, 181, 22))
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_40 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_40.setGeometry(QtCore.QRect(200, 30, 171, 22))
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_41 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_41.setGeometry(QtCore.QRect(200, 50, 171, 22))
        self.checkBox_41.setObjectName("checkBox_41")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(170, 0, 211, 20))
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.page_3)
        self.textEdit_3.setGeometry(QtCore.QRect(110, 20, 331, 21))
        self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.label_5.setObjectName("label_5")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.page_3)
        self.commandLinkButton.setGeometry(QtCore.QRect(10, 60, 131, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.page_3)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(160, 60, 131, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.page_3)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(300, 60, 151, 41))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.columnView_2 = QtWidgets.QColumnView(self.page_3)
        self.columnView_2.setGeometry(QtCore.QRect(450, 10, 311, 81))
        self.columnView_2.setAlternatingRowColors(True)
        self.columnView_2.setObjectName("columnView_2")
        self.stackedWidget.addWidget(self.page_3)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(250, 150, 231, 20))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(-10, 10, 841, 261))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(100, 0, 111, 221))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_10 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_2.addWidget(self.checkBox_10, 5, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 2, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_2.addWidget(self.checkBox_7, 3, 0, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_2.addWidget(self.checkBox_11, 7, 0, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_2.addWidget(self.checkBox_15, 6, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_2.addWidget(self.checkBox_17, 4, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 8, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 9, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(200, 10, 91, 220))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_29 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_3.addWidget(self.checkBox_29, 6, 0, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_3.addWidget(self.checkBox_24, 8, 0, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_3.addWidget(self.checkBox_25, 2, 0, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_3.addWidget(self.checkBox_22, 7, 0, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_3.addWidget(self.checkBox_23, 5, 0, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_3.addWidget(self.checkBox_26, 3, 0, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_3.addWidget(self.checkBox_21, 4, 0, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_3.addWidget(self.checkBox_27, 1, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(290, 10, 131, 220))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_33 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_4.addWidget(self.checkBox_33, 2, 0, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout_4.addWidget(self.checkBox_30, 1, 0, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_4.addWidget(self.checkBox_31, 5, 0, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_4.addWidget(self.checkBox_32, 3, 0, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout_4.addWidget(self.checkBox_35, 7, 0, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout_4.addWidget(self.checkBox_36, 8, 0, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout_4.addWidget(self.checkBox_34, 0, 0, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_38.setObjectName("checkBox_38")
        self.gridLayout_4.addWidget(self.checkBox_38, 4, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(430, 10, 131, 211))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_49 = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.checkBox_49.setObjectName("checkBox_49")
        self.gridLayout_6.addWidget(self.checkBox_49, 4, 0, 1, 1)
        self.checkBox_50 = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.checkBox_50.setObjectName("checkBox_50")
        self.gridLayout_6.addWidget(self.checkBox_50, 2, 0, 1, 1)
        self.checkBox_48 = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.checkBox_48.setObjectName("checkBox_48")
        self.gridLayout_6.addWidget(self.checkBox_48, 1, 0, 1, 1)
        self.checkBox_51 = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.checkBox_51.setObjectName("checkBox_51")
        self.gridLayout_6.addWidget(self.checkBox_51, 5, 0, 1, 1)
        self.checkBox_52 = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.checkBox_52.setObjectName("checkBox_52")
        self.gridLayout_6.addWidget(self.checkBox_52, 0, 0, 1, 1)
        self.checkBox_56 = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.checkBox_56.setObjectName("checkBox_56")
        self.gridLayout_6.addWidget(self.checkBox_56, 3, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(570, 10, 121, 220))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_58 = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_58.setObjectName("checkBox_58")
        self.gridLayout_7.addWidget(self.checkBox_58, 4, 0, 1, 1)
        self.checkBox_60 = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_60.setObjectName("checkBox_60")
        self.gridLayout_7.addWidget(self.checkBox_60, 5, 0, 1, 1)
        self.checkBox_59 = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_59.setObjectName("checkBox_59")
        self.gridLayout_7.addWidget(self.checkBox_59, 2, 0, 1, 1)
        self.checkBox_57 = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_57.setObjectName("checkBox_57")
        self.gridLayout_7.addWidget(self.checkBox_57, 1, 0, 1, 1)
        self.checkBox_62 = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_62.setObjectName("checkBox_62")
        self.gridLayout_7.addWidget(self.checkBox_62, 7, 0, 1, 1)
        self.checkBox_61 = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_61.setObjectName("checkBox_61")
        self.gridLayout_7.addWidget(self.checkBox_61, 0, 0, 1, 1)
        self.checkBox_64 = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_64.setObjectName("checkBox_64")
        self.gridLayout_7.addWidget(self.checkBox_64, 6, 0, 1, 1)
        self.checkBox_65 = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_65.setObjectName("checkBox_65")
        self.gridLayout_7.addWidget(self.checkBox_65, 3, 0, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 0, 76, 220))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox_66 = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.checkBox_66.setObjectName("checkBox_66")
        self.gridLayout_8.addWidget(self.checkBox_66, 0, 0, 1, 1)
        self.checkBox_68 = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.checkBox_68.setObjectName("checkBox_68")
        self.gridLayout_8.addWidget(self.checkBox_68, 1, 0, 1, 1)
        self.checkBox_67 = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.checkBox_67.setObjectName("checkBox_67")
        self.gridLayout_8.addWidget(self.checkBox_67, 3, 0, 1, 1)
        self.checkBox_69 = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.checkBox_69.setObjectName("checkBox_69")
        self.gridLayout_8.addWidget(self.checkBox_69, 4, 0, 1, 1)
        self.checkBox_74 = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.checkBox_74.setObjectName("checkBox_74")
        self.gridLayout_8.addWidget(self.checkBox_74, 2, 0, 1, 1)
        self.checkBox_73 = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.checkBox_73.setObjectName("checkBox_73")
        self.gridLayout_8.addWidget(self.checkBox_73, 5, 0, 1, 1)
        self.checkBox_72 = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.checkBox_72.setObjectName("checkBox_72")
        self.gridLayout_8.addWidget(self.checkBox_72, 7, 0, 1, 1)
        self.checkBox_71 = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.checkBox_71.setObjectName("checkBox_71")
        self.gridLayout_8.addWidget(self.checkBox_71, 6, 0, 1, 1)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(700, 10, 121, 220))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.checkBox_63 = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.checkBox_63.setObjectName("checkBox_63")
        self.gridLayout_9.addWidget(self.checkBox_63, 4, 0, 1, 1)
        self.checkBox_89 = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.checkBox_89.setObjectName("checkBox_89")
        self.gridLayout_9.addWidget(self.checkBox_89, 5, 0, 1, 1)
        self.checkBox_90 = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.checkBox_90.setObjectName("checkBox_90")
        self.gridLayout_9.addWidget(self.checkBox_90, 2, 0, 1, 1)
        self.checkBox_91 = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.checkBox_91.setObjectName("checkBox_91")
        self.gridLayout_9.addWidget(self.checkBox_91, 1, 0, 1, 1)
        self.checkBox_92 = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.checkBox_92.setObjectName("checkBox_92")
        self.gridLayout_9.addWidget(self.checkBox_92, 7, 0, 1, 1)
        self.checkBox_93 = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.checkBox_93.setObjectName("checkBox_93")
        self.gridLayout_9.addWidget(self.checkBox_93, 0, 0, 1, 1)
        self.checkBox_94 = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.checkBox_94.setObjectName("checkBox_94")
        self.gridLayout_9.addWidget(self.checkBox_94, 6, 0, 1, 1)
        self.checkBox_95 = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.checkBox_95.setObjectName("checkBox_95")
        self.gridLayout_9.addWidget(self.checkBox_95, 3, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(20, 10, 637, 24))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gridLayoutWidget_9)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_81 = QtWidgets.QCheckBox(self.gridLayoutWidget_9)
        self.checkBox_81.setObjectName("checkBox_81")
        self.horizontalLayout.addWidget(self.checkBox_81)
        self.checkBox_80 = QtWidgets.QCheckBox(self.gridLayoutWidget_9)
        self.checkBox_80.setObjectName("checkBox_80")
        self.horizontalLayout.addWidget(self.checkBox_80)
        self.checkBox_79 = QtWidgets.QCheckBox(self.gridLayoutWidget_9)
        self.checkBox_79.setObjectName("checkBox_79")
        self.horizontalLayout.addWidget(self.checkBox_79)
        self.checkBox_78 = QtWidgets.QCheckBox(self.gridLayoutWidget_9)
        self.checkBox_78.setObjectName("checkBox_78")
        self.horizontalLayout.addWidget(self.checkBox_78)
        self.checkBox_77 = QtWidgets.QCheckBox(self.gridLayoutWidget_9)
        self.checkBox_77.setObjectName("checkBox_77")
        self.horizontalLayout.addWidget(self.checkBox_77)
        self.checkBox_76 = QtWidgets.QCheckBox(self.gridLayoutWidget_9)
        self.checkBox_76.setObjectName("checkBox_76")
        self.horizontalLayout.addWidget(self.checkBox_76)
        self.checkBox_75 = QtWidgets.QCheckBox(self.gridLayoutWidget_9)
        self.checkBox_75.setObjectName("checkBox_75")
        self.horizontalLayout.addWidget(self.checkBox_75)
        self.checkBox_70 = QtWidgets.QCheckBox(self.gridLayoutWidget_9)
        self.checkBox_70.setObjectName("checkBox_70")
        self.horizontalLayout.addWidget(self.checkBox_70)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.checkBox_84 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_84.setGeometry(QtCore.QRect(20, 60, 171, 21))
        self.checkBox_84.setObjectName("checkBox_84")
        self.checkBox_85 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_85.setGeometry(QtCore.QRect(20, 80, 151, 21))
        self.checkBox_85.setObjectName("checkBox_85")
        self.checkBox_86 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_86.setGeometry(QtCore.QRect(200, 16, 151, 21))
        self.checkBox_86.setObjectName("checkBox_86")
        self.checkBox_87 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_87.setGeometry(QtCore.QRect(200, 40, 151, 31))
        self.checkBox_87.setText("")
        self.checkBox_87.setObjectName("checkBox_87")
        self.comboBox = QtWidgets.QComboBox(self.tab_7)
        self.comboBox.setGeometry(QtCore.QRect(220, 40, 131, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.checkBox_88 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_88.setGeometry(QtCore.QRect(200, 70, 151, 21))
        self.checkBox_88.setObjectName("checkBox_88")
        self.checkBox_82 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_82.setGeometry(QtCore.QRect(20, 17, 111, 20))
        self.checkBox_82.setObjectName("checkBox_82")
        self.checkBox_83 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_83.setGeometry(QtCore.QRect(20, 40, 111, 21))
        self.checkBox_83.setObjectName("checkBox_83")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(CookieWindow)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CookieWindow)

    def retranslateUi(self, CookieWindow):
        _translate = QtCore.QCoreApplication.translate
        CookieWindow.setWindowTitle(_translate("CookieWindow", "Dialog"))
        self.combos.setText(_translate("CookieWindow", "Combos"))
        self.pushButton_19.setText(_translate("CookieWindow", "Logs"))
        self.pushButton_20.setText(_translate("CookieWindow", "IPs"))
        self.pushButton_21.setText(_translate("CookieWindow", "Request"))
        self.pushButton_22.setText(_translate("CookieWindow", "Contact"))
        self.pushButton.setText(_translate("CookieWindow", "CFGs"))
        self.pushButton_2.setText(_translate("CookieWindow", "Cookies"))
        self.label.setText(_translate("CookieWindow", "Domain in Cookies"))
        self.pushButton_3.setText(_translate("CookieWindow", "Load Cookies"))
        self.label_2.setText(_translate("CookieWindow", "URL:"))
        self.comboBox_2.setItemText(0, _translate("CookieWindow", "GET"))
        self.comboBox_2.setItemText(1, _translate("CookieWindow", "POST"))
        self.checkBox_5.setText(_translate("CookieWindow", "User Agent:"))
        self.checkBox_6.setText(_translate("CookieWindow", "Content Type:"))
        self.checkBox_8.setText(_translate("CookieWindow", "Accept:"))
        self.checkBox_9.setText(_translate("CookieWindow", "Referrer:"))
        self.checkBox_12.setText(_translate("CookieWindow", "X-Requested-With:"))
        self.checkBox_13.setText(_translate("CookieWindow", "NAME1=VALUE1"))
        self.checkBox_14.setText(_translate("CookieWindow", "NAME2=VALUE2"))
        self.checkBox_16.setText(_translate("CookieWindow", "NAME3=VALUE3"))
        self.checkBox_18.setText(_translate("CookieWindow", "NAME5=VALUE5"))
        self.checkBox_19.setText(_translate("CookieWindow", "NAME4=VALUE4"))
        self.checkBox_20.setText(_translate("CookieWindow", "Custom HWID:"))
        self.checkBox_28.setText(_translate("CookieWindow", "Geolocation:"))
        self.checkBox_37.setText(_translate("CookieWindow", "Browser Resolution:"))
        self.checkBox_39.setText(_translate("CookieWindow", "Renew Cookie Expiration Date"))
        self.checkBox_40.setText(_translate("CookieWindow", "Force Clean IP/Socks"))
        self.checkBox_41.setText(_translate("CookieWindow", "Report Back Cookie Values"))
        self.label_4.setText(_translate("CookieWindow", "URL / Network Tools & Services"))
        self.label_5.setText(_translate("CookieWindow", "Website Domain:"))
        self.commandLinkButton.setText(_translate("CookieWindow", "Scan SubDomains"))
        self.commandLinkButton_2.setText(_translate("CookieWindow", "Check Cloudflare"))
        self.commandLinkButton_3.setText(_translate("CookieWindow", "Find Element Values"))
        self.columnView_2.setWhatsThis(_translate("CookieWindow", "Displays your URL Network results and settings."))
        self.label_3.setText(_translate("CookieWindow", "Request Headers: (Inspect Element Tool)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CookieWindow", "Cookie Config Creator"))
        self.checkBox_10.setText(_translate("CookieWindow", "VK"))
        self.checkBox.setText(_translate("CookieWindow", "Youtube"))
        self.checkBox_7.setText(_translate("CookieWindow", "Snapchat"))
        self.checkBox_11.setText(_translate("CookieWindow", "Twitter"))
        self.checkBox_15.setText(_translate("CookieWindow", "Tiktok"))
        self.checkBox_17.setText(_translate("CookieWindow", "Instagram"))
        self.checkBox_4.setText(_translate("CookieWindow", "Pintrest"))
        self.checkBox_2.setText(_translate("CookieWindow", "Myspace"))
        self.checkBox_3.setText(_translate("CookieWindow", "Facebook"))
        self.checkBox_29.setText(_translate("CookieWindow", "Vimeo"))
        self.checkBox_24.setText(_translate("CookieWindow", "Rumble"))
        self.checkBox_25.setText(_translate("CookieWindow", "Spotify"))
        self.checkBox_22.setText(_translate("CookieWindow", "Locals"))
        self.checkBox_23.setText(_translate("CookieWindow", "Kick"))
        self.checkBox_26.setText(_translate("CookieWindow", "Reddit"))
        self.checkBox_21.setText(_translate("CookieWindow", "Twitch"))
        self.checkBox_27.setText(_translate("CookieWindow", "LinkedIn"))
        self.checkBox_33.setText(_translate("CookieWindow", "Kleinanzeigen"))
        self.checkBox_30.setText(_translate("CookieWindow", "Ebay"))
        self.checkBox_31.setText(_translate("CookieWindow", "Google Play"))
        self.checkBox_32.setText(_translate("CookieWindow", "Temu"))
        self.checkBox_35.setText(_translate("CookieWindow", "Google Account"))
        self.checkBox_36.setText(_translate("CookieWindow", "CheckBox"))
        self.checkBox_34.setText(_translate("CookieWindow", "Amazon"))
        self.checkBox_38.setText(_translate("CookieWindow", "Vinted"))
        self.checkBox_49.setText(_translate("CookieWindow", "MeetMe"))
        self.checkBox_50.setText(_translate("CookieWindow", "AshleyMaddison"))
        self.checkBox_48.setText(_translate("CookieWindow", "EHarmony"))
        self.checkBox_51.setText(_translate("CookieWindow", "ChristanMingle"))
        self.checkBox_52.setText(_translate("CookieWindow", "Tinder"))
        self.checkBox_56.setText(_translate("CookieWindow", "Zoosk"))
        self.checkBox_58.setText(_translate("CookieWindow", "Craigslist Ads"))
        self.checkBox_60.setText(_translate("CookieWindow", "Bing Ads"))
        self.checkBox_59.setText(_translate("CookieWindow", "Tinder Ads"))
        self.checkBox_57.setText(_translate("CookieWindow", "Microsoft Ads"))
        self.checkBox_62.setText(_translate("CookieWindow", "SEM Rush"))
        self.checkBox_61.setText(_translate("CookieWindow", "Facebook Ads"))
        self.checkBox_64.setText(_translate("CookieWindow", "Snapchat Ads"))
        self.checkBox_65.setText(_translate("CookieWindow", "Reddit Ads"))
        self.checkBox_66.setText(_translate("CookieWindow", "Gmail"))
        self.checkBox_68.setText(_translate("CookieWindow", "Outlook"))
        self.checkBox_67.setText(_translate("CookieWindow", "Webmail"))
        self.checkBox_69.setText(_translate("CookieWindow", "Cpanel"))
        self.checkBox_74.setText(_translate("CookieWindow", "Office"))
        self.checkBox_73.setText(_translate("CookieWindow", "Yahoo"))
        self.checkBox_72.setText(_translate("CookieWindow", "Yandex"))
        self.checkBox_71.setText(_translate("CookieWindow", "Mail.Ru"))
        self.checkBox_63.setText(_translate("CookieWindow", "Custom Project 5"))
        self.checkBox_89.setText(_translate("CookieWindow", "Custom Project 6"))
        self.checkBox_90.setText(_translate("CookieWindow", "Custom Project 3"))
        self.checkBox_91.setText(_translate("CookieWindow", "Custom Project 2"))
        self.checkBox_92.setText(_translate("CookieWindow", "Custom Project 8"))
        self.checkBox_93.setText(_translate("CookieWindow", "Custom Project 1"))
        self.checkBox_94.setText(_translate("CookieWindow", "Custom Project 7"))
        self.checkBox_95.setText(_translate("CookieWindow", "Custom Project 4"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("CookieWindow", "Main Logs"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("CookieWindow", "Shopping"))
        self.checkBox_81.setText(_translate("CookieWindow", "Crypto.com"))
        self.checkBox_80.setText(_translate("CookieWindow", "BTC.me"))
        self.checkBox_79.setText(_translate("CookieWindow", "Binance"))
        self.checkBox_78.setText(_translate("CookieWindow", "KuCoin"))
        self.checkBox_77.setText(_translate("CookieWindow", "Freebitcoin.io"))
        self.checkBox_76.setText(_translate("CookieWindow", "Kryptex"))
        self.checkBox_75.setText(_translate("CookieWindow", "Paxful"))
        self.checkBox_70.setText(_translate("CookieWindow", "Coinbase"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("CookieWindow", "Crypto Sites"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("CookieWindow", "Wallets"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("CookieWindow", "File Captures"))
        self.checkBox_84.setText(_translate("CookieWindow", "Sort Phone Numbers Leads"))
        self.checkBox_85.setText(_translate("CookieWindow", "Sort Business Email Leads"))
        self.checkBox_86.setText(_translate("CookieWindow", "Email Hosting Data"))
        self.comboBox.setItemText(0, _translate("CookieWindow", "Normal Fullz"))
        self.comboBox.setItemText(1, _translate("CookieWindow", "CC Fullz"))
        self.comboBox.setItemText(2, _translate("CookieWindow", "Banking Fullz"))
        self.comboBox.setItemText(3, _translate("CookieWindow", "Banking w/ Security Q&A"))
        self.checkBox_88.setText(_translate("CookieWindow", "Server / RDP / VPS  Data"))
        self.checkBox_82.setText(_translate("CookieWindow", "Sort User:Pass"))
        self.checkBox_83.setText(_translate("CookieWindow", "Sort Email:Pass"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("CookieWindow", "Text Options"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CookieWindow", "Cookie Work Mode Settings"))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    CookieWindow = QtWidgets.QDialog()
    ui = Ui_CookieWindow()
    ui.setupUi(CookieWindow)
    CookieWindow.show()
    sys.exit(app.exec_())

