# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChatItemWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatItemWidget(object):
    def setupUi(self, ChatItemWidget):
        ChatItemWidget.setObjectName("ChatItemWidget")
        ChatItemWidget.resize(270, 72)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ChatItemWidget.sizePolicy().hasHeightForWidth())
        ChatItemWidget.setSizePolicy(sizePolicy)
        ChatItemWidget.setMinimumSize(QtCore.QSize(0, 72))
        ChatItemWidget.setMaximumSize(QtCore.QSize(16777215, 72))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(ChatItemWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AvatarWidget = AvatarWidget(ChatItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AvatarWidget.sizePolicy().hasHeightForWidth())
        self.AvatarWidget.setSizePolicy(sizePolicy)
        self.AvatarWidget.setMinimumSize(QtCore.QSize(70, 70))
        self.AvatarWidget.setMaximumSize(QtCore.QSize(70, 70))
        self.AvatarWidget.setObjectName("AvatarWidget")
        self.horizontalLayout.addWidget(self.AvatarWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lb_name = StrongBodyLabel(ChatItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_name.sizePolicy().hasHeightForWidth())
        self.lb_name.setSizePolicy(sizePolicy)
        self.lb_name.setMinimumSize(QtCore.QSize(150, 21))
        self.lb_name.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.lb_name.setFont(font)
        self.lb_name.setObjectName("lb_name")
        self.verticalLayout.addWidget(self.lb_name)
        self.lb_message = BodyLabel(ChatItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_message.sizePolicy().hasHeightForWidth())
        self.lb_message.setSizePolicy(sizePolicy)
        self.lb_message.setMinimumSize(QtCore.QSize(150, 17))
        self.lb_message.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        self.lb_message.setFont(font)
        self.lb_message.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lb_message.setObjectName("lb_message")
        self.verticalLayout.addWidget(self.lb_message)
        spacerItem1 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(ChatItemWidget)
        QtCore.QMetaObject.connectSlotsByName(ChatItemWidget)

    def retranslateUi(self, ChatItemWidget):
        _translate = QtCore.QCoreApplication.translate
        ChatItemWidget.setWindowTitle(_translate("ChatItemWidget", "Form"))
        self.lb_name.setText(_translate("ChatItemWidget", "Strong body label"))
        self.lb_message.setText(_translate("ChatItemWidget", "Body label"))
from qfluentwidgets import AvatarWidget, BodyLabel, StrongBodyLabel


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChatItemWidget = QtWidgets.QWidget()
    ui = Ui_ChatItemWidget()
    ui.setupUi(ChatItemWidget)
    ChatItemWidget.show()
    sys.exit(app.exec_())
