# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Desktop\pyqtQQ\ui\RequestItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RequestItem(object):
    def setupUi(self, RequestItem):
        RequestItem.setObjectName("RequestItem")
        RequestItem.resize(288, 78)
        RequestItem.setMinimumSize(QtCore.QSize(288, 78))
        RequestItem.setMaximumSize(QtCore.QSize(16777215, 78))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(RequestItem)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.avatar = ImageLabel(RequestItem)
        self.avatar.setMinimumSize(QtCore.QSize(60, 60))
        self.avatar.setMaximumSize(QtCore.QSize(60, 60))
        self.avatar.setObjectName("avatar")
        self.horizontalLayout_2.addWidget(self.avatar)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_nickname = StrongBodyLabel(RequestItem)
        self.lb_nickname.setObjectName("lb_nickname")
        self.horizontalLayout.addWidget(self.lb_nickname)
        self.lb_username = BodyLabel(RequestItem)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setItalic(True)
        self.lb_username.setFont(font)
        self.lb_username.setObjectName("lb_username")
        self.horizontalLayout.addWidget(self.lb_username)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lb_body = BodyLabel(RequestItem)
        self.lb_body.setObjectName("lb_body")
        self.verticalLayout.addWidget(self.lb_body)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(RequestItem)
        QtCore.QMetaObject.connectSlotsByName(RequestItem)

    def retranslateUi(self, RequestItem):
        _translate = QtCore.QCoreApplication.translate
        RequestItem.setWindowTitle(_translate("RequestItem", "💎 Chat"))
        self.lb_nickname.setText(_translate("RequestItem", "Strong body label"))
        self.lb_username.setText(_translate("RequestItem", "Body label"))
        self.lb_body.setText(_translate("RequestItem", "Body label"))
from qfluentwidgets import BodyLabel, ImageLabel, StrongBodyLabel
