# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'url_tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UrlToolsWindow(object):
    def setupUi(self, UrlToolsWindow):
        UrlToolsWindow.setObjectName("UrlToolsWindow")
        UrlToolsWindow.resize(1149, 655)
        UrlToolsWindow.setMinimumSize(QtCore.QSize(1149, 655))
        UrlToolsWindow.setMaximumSize(QtCore.QSize(1149, 655))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        UrlToolsWindow.setPalette(palette)
        UrlToolsWindow.setStyleSheet("QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QTreeView,\n"
"QListView,\n"
"QLineEdit,\n"
"QComboBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.url_target_textedit = QtWidgets.QTextEdit(UrlToolsWindow)
        self.url_target_textedit.setGeometry(QtCore.QRect(510, 10, 351, 31))
        self.url_target_textedit.setToolTip("")
        self.url_target_textedit.setStatusTip("")
        self.url_target_textedit.setAccessibleName("")
        self.url_target_textedit.setAccessibleDescription("")
        self.url_target_textedit.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.url_target_textedit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_target_textedit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_target_textedit.setTabChangesFocus(True)
        self.url_target_textedit.setDocumentTitle("")
        self.url_target_textedit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.url_target_textedit.setMarkdown("")
        self.url_target_textedit.setObjectName("url_target_textedit")
        self.analytics_and_config_tab_widget = QtWidgets.QTabWidget(UrlToolsWindow)
        self.analytics_and_config_tab_widget.setEnabled(True)
        self.analytics_and_config_tab_widget.setGeometry(QtCore.QRect(490, 380, 641, 271))
        self.analytics_and_config_tab_widget.setStyleSheet("QTabWidget::pane {\n"
"    background-color: black;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: left;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 2px solid teal;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: teal;\n"
"    border-color: teal;\n"
"}")
        self.analytics_and_config_tab_widget.setObjectName("analytics_and_config_tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.captcha_button = QtWidgets.QPushButton(self.tab)
        self.captcha_button.setEnabled(True)
        self.captcha_button.setGeometry(QtCore.QRect(470, 40, 61, 24))
        self.captcha_button.setObjectName("captcha_button")
        self.cloudflare_button = QtWidgets.QPushButton(self.tab)
        self.cloudflare_button.setEnabled(True)
        self.cloudflare_button.setGeometry(QtCore.QRect(550, 40, 80, 24))
        self.cloudflare_button.setObjectName("cloudflare_button")
        self.akamai_button = QtWidgets.QPushButton(self.tab)
        self.akamai_button.setEnabled(True)
        self.akamai_button.setGeometry(QtCore.QRect(390, 40, 61, 24))
        self.akamai_button.setObjectName("akamai_button")
        self.http_request_button = QtWidgets.QPushButton(self.tab)
        self.http_request_button.setEnabled(True)
        self.http_request_button.setGeometry(QtCore.QRect(420, 10, 161, 24))
        self.http_request_button.setObjectName("http_request_button")
        self.alternatives_button = QtWidgets.QPushButton(self.tab)
        self.alternatives_button.setEnabled(True)
        self.alternatives_button.setGeometry(QtCore.QRect(0, 70, 81, 24))
        self.alternatives_button.setObjectName("alternatives_button")
        self.seo_data_details_button = QtWidgets.QPushButton(self.tab)
        self.seo_data_details_button.setEnabled(True)
        self.seo_data_details_button.setGeometry(QtCore.QRect(30, 10, 161, 24))
        self.seo_data_details_button.setObjectName("seo_data_details_button")
        self.sub_domains_button = QtWidgets.QPushButton(self.tab)
        self.sub_domains_button.setEnabled(True)
        self.sub_domains_button.setGeometry(QtCore.QRect(160, 40, 80, 24))
        self.sub_domains_button.setWhatsThis("")
        self.sub_domains_button.setObjectName("sub_domains_button")
        self.simalar_web_button = QtWidgets.QPushButton(self.tab)
        self.simalar_web_button.setEnabled(True)
        self.simalar_web_button.setGeometry(QtCore.QRect(0, 40, 80, 24))
        self.simalar_web_button.setObjectName("simalar_web_button")
        self.traffic_button = QtWidgets.QPushButton(self.tab)
        self.traffic_button.setEnabled(True)
        self.traffic_button.setGeometry(QtCore.QRect(90, 40, 61, 24))
        self.traffic_button.setObjectName("traffic_button")
        self.link_diver_button = QtWidgets.QPushButton(self.tab)
        self.link_diver_button.setEnabled(True)
        self.link_diver_button.setGeometry(QtCore.QRect(380, 140, 80, 61))
        self.link_diver_button.setObjectName("link_diver_button")
        self.xpath_scraper_button = QtWidgets.QPushButton(self.tab)
        self.xpath_scraper_button.setEnabled(False)
        self.xpath_scraper_button.setGeometry(QtCore.QRect(530, 360, 81, 24))
        self.xpath_scraper_button.setObjectName("xpath_scraper_button")
        self.analyze_csp = QtWidgets.QPushButton(self.tab)
        self.analyze_csp.setEnabled(False)
        self.analyze_csp.setGeometry(QtCore.QRect(330, 360, 191, 24))
        self.analyze_csp.setObjectName("analyze_csp")
        self.check_url_login_directories = QtWidgets.QPushButton(self.tab)
        self.check_url_login_directories.setEnabled(True)
        self.check_url_login_directories.setGeometry(QtCore.QRect(160, 70, 101, 24))
        self.check_url_login_directories.setObjectName("check_url_login_directories")
        self.check_api_login_directories = QtWidgets.QPushButton(self.tab)
        self.check_api_login_directories.setEnabled(True)
        self.check_api_login_directories.setGeometry(QtCore.QRect(160, 100, 91, 24))
        self.check_api_login_directories.setObjectName("check_api_login_directories")
        self.website_bf_hidden_content_button = QtWidgets.QPushButton(self.tab)
        self.website_bf_hidden_content_button.setEnabled(True)
        self.website_bf_hidden_content_button.setGeometry(QtCore.QRect(20, 140, 161, 24))
        self.website_bf_hidden_content_button.setObjectName("website_bf_hidden_content_button")
        self.analytics_and_config_tab_widget.addTab(self.tab, "")
        self.Config_Functions_Tab = QtWidgets.QWidget()
        self.Config_Functions_Tab.setObjectName("Config_Functions_Tab")
        self.http_request_get_button = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_get_button.setEnabled(True)
        self.http_request_get_button.setGeometry(QtCore.QRect(440, 20, 80, 24))
        self.http_request_get_button.setObjectName("http_request_get_button")
        self.http_request_post_button = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_post_button.setEnabled(True)
        self.http_request_post_button.setGeometry(QtCore.QRect(550, 20, 80, 24))
        self.http_request_post_button.setObjectName("http_request_post_button")
        self.http_request_headers_button = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_headers_button.setEnabled(True)
        self.http_request_headers_button.setGeometry(QtCore.QRect(440, 70, 80, 24))
        self.http_request_headers_button.setObjectName("http_request_headers_button")
        self.http_request_parse_button = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_parse_button.setEnabled(True)
        self.http_request_parse_button.setGeometry(QtCore.QRect(550, 70, 80, 24))
        self.http_request_parse_button.setObjectName("http_request_parse_button")
        self.http_request_html_button = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_html_button.setEnabled(True)
        self.http_request_html_button.setGeometry(QtCore.QRect(440, 110, 80, 24))
        self.http_request_html_button.setObjectName("http_request_html_button")
        self.http_request_css_button = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_css_button.setEnabled(True)
        self.http_request_css_button.setGeometry(QtCore.QRect(550, 110, 80, 24))
        self.http_request_css_button.setObjectName("http_request_css_button")
        self.http_request_referrer_button = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_referrer_button.setEnabled(True)
        self.http_request_referrer_button.setGeometry(QtCore.QRect(440, 150, 80, 24))
        self.http_request_referrer_button.setObjectName("http_request_referrer_button")
        self.http_request_headers_button_2 = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_headers_button_2.setEnabled(True)
        self.http_request_headers_button_2.setGeometry(QtCore.QRect(330, 20, 80, 24))
        self.http_request_headers_button_2.setObjectName("http_request_headers_button_2")
        self.http_request_headers_button_3 = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_headers_button_3.setEnabled(True)
        self.http_request_headers_button_3.setGeometry(QtCore.QRect(330, 70, 80, 24))
        self.http_request_headers_button_3.setObjectName("http_request_headers_button_3")
        self.http_request_headers_button_4 = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_headers_button_4.setEnabled(True)
        self.http_request_headers_button_4.setGeometry(QtCore.QRect(10, 20, 80, 24))
        self.http_request_headers_button_4.setObjectName("http_request_headers_button_4")
        self.http_request_headers_button_5 = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_headers_button_5.setEnabled(True)
        self.http_request_headers_button_5.setGeometry(QtCore.QRect(110, 20, 80, 24))
        self.http_request_headers_button_5.setObjectName("http_request_headers_button_5")
        self.http_request_headers_button_6 = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_headers_button_6.setEnabled(True)
        self.http_request_headers_button_6.setGeometry(QtCore.QRect(210, 20, 80, 24))
        self.http_request_headers_button_6.setObjectName("http_request_headers_button_6")
        self.http_request_headers_button_7 = QtWidgets.QPushButton(self.Config_Functions_Tab)
        self.http_request_headers_button_7.setEnabled(True)
        self.http_request_headers_button_7.setGeometry(QtCore.QRect(10, 60, 80, 24))
        self.http_request_headers_button_7.setObjectName("http_request_headers_button_7")
        self.analytics_and_config_tab_widget.addTab(self.Config_Functions_Tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.javascript_links_button = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button.setEnabled(True)
        self.javascript_links_button.setGeometry(QtCore.QRect(20, 30, 111, 24))
        self.javascript_links_button.setObjectName("javascript_links_button")
        self.css_links_button = QtWidgets.QPushButton(self.tab_3)
        self.css_links_button.setEnabled(True)
        self.css_links_button.setGeometry(QtCore.QRect(150, 30, 81, 24))
        self.css_links_button.setObjectName("css_links_button")
        self.scrape_website_fonts_button = QtWidgets.QPushButton(self.tab_3)
        self.scrape_website_fonts_button.setEnabled(True)
        self.scrape_website_fonts_button.setGeometry(QtCore.QRect(250, 30, 111, 24))
        self.scrape_website_fonts_button.setObjectName("scrape_website_fonts_button")
        self.scrape_external_links_button = QtWidgets.QPushButton(self.tab_3)
        self.scrape_external_links_button.setEnabled(True)
        self.scrape_external_links_button.setGeometry(QtCore.QRect(380, 30, 111, 24))
        self.scrape_external_links_button.setObjectName("scrape_external_links_button")
        self.scrape_imagesbutton = QtWidgets.QPushButton(self.tab_3)
        self.scrape_imagesbutton.setEnabled(True)
        self.scrape_imagesbutton.setGeometry(QtCore.QRect(520, 30, 81, 24))
        self.scrape_imagesbutton.setObjectName("scrape_imagesbutton")
        self.javascript_links_button_2 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_2.setEnabled(True)
        self.javascript_links_button_2.setGeometry(QtCore.QRect(20, 70, 81, 24))
        self.javascript_links_button_2.setObjectName("javascript_links_button_2")
        self.javascript_links_button_3 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_3.setEnabled(True)
        self.javascript_links_button_3.setGeometry(QtCore.QRect(130, 110, 111, 24))
        self.javascript_links_button_3.setObjectName("javascript_links_button_3")
        self.javascript_links_button_4 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_4.setEnabled(True)
        self.javascript_links_button_4.setGeometry(QtCore.QRect(10, 110, 111, 24))
        self.javascript_links_button_4.setObjectName("javascript_links_button_4")
        self.javascript_links_button_5 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_5.setEnabled(True)
        self.javascript_links_button_5.setGeometry(QtCore.QRect(260, 110, 111, 24))
        self.javascript_links_button_5.setObjectName("javascript_links_button_5")
        self.javascript_links_button_6 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_6.setEnabled(True)
        self.javascript_links_button_6.setGeometry(QtCore.QRect(390, 110, 111, 24))
        self.javascript_links_button_6.setObjectName("javascript_links_button_6")
        self.javascript_links_button_7 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_7.setEnabled(True)
        self.javascript_links_button_7.setGeometry(QtCore.QRect(520, 110, 111, 24))
        self.javascript_links_button_7.setObjectName("javascript_links_button_7")
        self.javascript_links_button_8 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_8.setEnabled(True)
        self.javascript_links_button_8.setGeometry(QtCore.QRect(450, 70, 91, 24))
        self.javascript_links_button_8.setObjectName("javascript_links_button_8")
        self.javascript_links_button_9 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_9.setEnabled(True)
        self.javascript_links_button_9.setGeometry(QtCore.QRect(330, 70, 111, 24))
        self.javascript_links_button_9.setObjectName("javascript_links_button_9")
        self.javascript_links_button_10 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_10.setEnabled(False)
        self.javascript_links_button_10.setGeometry(QtCore.QRect(10, 360, 111, 24))
        self.javascript_links_button_10.setObjectName("javascript_links_button_10")
        self.javascript_links_button_11 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_11.setEnabled(True)
        self.javascript_links_button_11.setGeometry(QtCore.QRect(230, 70, 91, 24))
        self.javascript_links_button_11.setObjectName("javascript_links_button_11")
        self.javascript_links_button_12 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_12.setEnabled(True)
        self.javascript_links_button_12.setGeometry(QtCore.QRect(110, 70, 111, 24))
        self.javascript_links_button_12.setObjectName("javascript_links_button_12")
        self.javascript_links_button_13 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_13.setEnabled(True)
        self.javascript_links_button_13.setGeometry(QtCore.QRect(10, 150, 111, 24))
        self.javascript_links_button_13.setObjectName("javascript_links_button_13")
        self.javascript_links_button_14 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_14.setEnabled(True)
        self.javascript_links_button_14.setGeometry(QtCore.QRect(410, 150, 111, 24))
        self.javascript_links_button_14.setObjectName("javascript_links_button_14")
        self.javascript_links_button_15 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_15.setEnabled(True)
        self.javascript_links_button_15.setGeometry(QtCore.QRect(140, 150, 111, 24))
        self.javascript_links_button_15.setObjectName("javascript_links_button_15")
        self.javascript_links_button_16 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_16.setEnabled(True)
        self.javascript_links_button_16.setGeometry(QtCore.QRect(530, 150, 101, 24))
        self.javascript_links_button_16.setObjectName("javascript_links_button_16")
        self.javascript_links_button_17 = QtWidgets.QPushButton(self.tab_3)
        self.javascript_links_button_17.setEnabled(True)
        self.javascript_links_button_17.setGeometry(QtCore.QRect(270, 150, 111, 24))
        self.javascript_links_button_17.setObjectName("javascript_links_button_17")
        self.analytics_and_config_tab_widget.addTab(self.tab_3, "")
        self.results_textwindow_label = QtWidgets.QLabel(UrlToolsWindow)
        self.results_textwindow_label.setGeometry(QtCore.QRect(180, 10, 91, 51))
        font = QtGui.QFont()
        font.setFamily("HACKED")
        font.setPointSize(20)
        self.results_textwindow_label.setFont(font)
        self.results_textwindow_label.setObjectName("results_textwindow_label")
        self.connection_label = QtWidgets.QLabel(UrlToolsWindow)
        self.connection_label.setGeometry(QtCore.QRect(1010, 280, 131, 20))
        font = QtGui.QFont()
        font.setFamily("HACKED")
        font.setPointSize(11)
        self.connection_label.setFont(font)
        self.connection_label.setObjectName("connection_label")
        self.connection_widget = QtWidgets.QWidget(UrlToolsWindow)
        self.connection_widget.setGeometry(QtCore.QRect(1000, 10, 141, 261))
        self.connection_widget.setObjectName("connection_widget")
        self.results_window_textedit_2 = QtWidgets.QTextEdit(self.connection_widget)
        self.results_window_textedit_2.setGeometry(QtCore.QRect(0, 0, 141, 261))
        self.results_window_textedit_2.setObjectName("results_window_textedit_2")
        self.textEdit_2 = QtWidgets.QTextEdit(UrlToolsWindow)
        self.textEdit_2.setGeometry(QtCore.QRect(50, 370, 331, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(UrlToolsWindow)
        self.buttonBox.setGeometry(QtCore.QRect(90, 410, 221, 24))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Save|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.link_diver_client_button = QtWidgets.QPushButton(UrlToolsWindow)
        self.link_diver_client_button.setGeometry(QtCore.QRect(240, 520, 91, 51))
        self.link_diver_client_button.setObjectName("link_diver_client_button")
        self.url_blaster_client_button_2 = QtWidgets.QPushButton(UrlToolsWindow)
        self.url_blaster_client_button_2.setGeometry(QtCore.QRect(130, 520, 91, 51))
        self.url_blaster_client_button_2.setObjectName("url_blaster_client_button_2")
        self.QTabWidget = QtWidgets.QTabWidget(UrlToolsWindow)
        self.QTabWidget.setGeometry(QtCore.QRect(530, 40, 431, 321))
        self.QTabWidget.setStyleSheet("QTabWidget::pane {\n"
"    background-color: black;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: left;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 2px solid teal;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: teal;\n"
"    border-color: teal;\n"
"}")
        self.QTabWidget.setObjectName("QTabWidget")
        self.WebsiteSourceCodeTab = QtWidgets.QWidget()
        self.WebsiteSourceCodeTab.setObjectName("WebsiteSourceCodeTab")
        self.console_data = QtWidgets.QTextEdit(self.WebsiteSourceCodeTab)
        self.console_data.setGeometry(QtCore.QRect(0, 0, 431, 291))
        self.console_data.setStyleSheet("QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QTreeView,\n"
"QListView,\n"
"QLineEdit,\n"
"QComboBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        self.console_data.setObjectName("console_data")
        self.QTabWidget.addTab(self.WebsiteSourceCodeTab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.treeView = QtWidgets.QTreeView(self.tab_5)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 431, 281))
        self.treeView.setObjectName("treeView")
        self.QTabWidget.addTab(self.tab_5, "")
        self.results_window_textedit_3 = QtWidgets.QTextEdit(UrlToolsWindow)
        self.results_window_textedit_3.setGeometry(QtCore.QRect(20, 70, 431, 291))
        self.results_window_textedit_3.setObjectName("results_window_textedit_3")
        self.save_results_path_checkbox = QtWidgets.QCheckBox(UrlToolsWindow)
        self.save_results_path_checkbox.setGeometry(QtCore.QRect(20, 620, 111, 22))
        self.save_results_path_checkbox.setObjectName("save_results_path_checkbox")
        self.google_mode_button = QtWidgets.QPushButton(UrlToolsWindow)
        self.google_mode_button.setGeometry(QtCore.QRect(30, 520, 91, 51))
        self.google_mode_button.setObjectName("google_mode_button")
        self.scadamode_button = QtWidgets.QPushButton(UrlToolsWindow)
        self.scadamode_button.setGeometry(QtCore.QRect(30, 460, 91, 51))
        self.scadamode_button.setObjectName("scadamode_button")
        self.scadamode2_button = QtWidgets.QPushButton(UrlToolsWindow)
        self.scadamode2_button.setGeometry(QtCore.QRect(130, 460, 91, 51))
        self.scadamode2_button.setObjectName("scadamode2_button")
        self.scadamode3_button = QtWidgets.QPushButton(UrlToolsWindow)
        self.scadamode3_button.setGeometry(QtCore.QRect(240, 460, 91, 51))
        self.scadamode3_button.setObjectName("scadamode3_button")
        self.tor_mode_button = QtWidgets.QPushButton(UrlToolsWindow)
        self.tor_mode_button.setGeometry(QtCore.QRect(340, 460, 91, 51))
        self.tor_mode_button.setObjectName("tor_mode_button")
        self.save_results_path_textedit = QtWidgets.QTextEdit(UrlToolsWindow)
        self.save_results_path_textedit.setGeometry(QtCore.QRect(130, 619, 351, 31))
        self.save_results_path_textedit.setTabChangesFocus(True)
        self.save_results_path_textedit.setObjectName("save_results_path_textedit")

        self.retranslateUi(UrlToolsWindow)
        self.analytics_and_config_tab_widget.setCurrentIndex(0)
        self.QTabWidget.setCurrentIndex(0)
        self.simalar_web_button.clicked['bool'].connect(self.results_textwindow_label.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UrlToolsWindow)

    def retranslateUi(self, UrlToolsWindow):
        _translate = QtCore.QCoreApplication.translate
        UrlToolsWindow.setWindowTitle(_translate("UrlToolsWindow", "Dialog"))
        self.url_target_textedit.setWhatsThis(_translate("UrlToolsWindow", "URL Target"))
        self.url_target_textedit.setPlaceholderText(_translate("UrlToolsWindow", "https://website-request.com/ or http://request.website.com"))
        self.captcha_button.setText(_translate("UrlToolsWindow", "Captcha"))
        self.cloudflare_button.setText(_translate("UrlToolsWindow", "Cloudflare"))
        self.akamai_button.setText(_translate("UrlToolsWindow", "Akamai"))
        self.http_request_button.setToolTip(_translate("UrlToolsWindow", "Display a HTTP Request Client to see live time stats and info."))
        self.http_request_button.setText(_translate("UrlToolsWindow", "HTTP Request Client"))
        self.alternatives_button.setToolTip(_translate("UrlToolsWindow", "Discover simalar websites and alternatives"))
        self.alternatives_button.setText(_translate("UrlToolsWindow", "Alternatives"))
        self.seo_data_details_button.setToolTip(_translate("UrlToolsWindow", "Get the basic information and stats of your request by SEO"))
        self.seo_data_details_button.setText(_translate("UrlToolsWindow", "SEO Data and Details"))
        self.sub_domains_button.setToolTip(_translate("UrlToolsWindow", "Scan for any related subdomains of the requested website"))
        self.sub_domains_button.setText(_translate("UrlToolsWindow", "Sub Domains"))
        self.simalar_web_button.setToolTip(_translate("UrlToolsWindow", "Find websites simalar to the one based on your request"))
        self.simalar_web_button.setText(_translate("UrlToolsWindow", "Simalar Web"))
        self.traffic_button.setToolTip(_translate("UrlToolsWindow", "Display any traffic stats based on your target"))
        self.traffic_button.setText(_translate("UrlToolsWindow", "Traffic"))
        self.link_diver_button.setText(_translate("UrlToolsWindow", "Link Diver CLI"))
        self.xpath_scraper_button.setText(_translate("UrlToolsWindow", "XPath Scraper"))
        self.analyze_csp.setText(_translate("UrlToolsWindow", "Analyze Content-Security-Policy"))
        self.check_url_login_directories.setToolTip(_translate("UrlToolsWindow", "This will scan the requested website for any possible URL Login pages"))
        self.check_url_login_directories.setText(_translate("UrlToolsWindow", "Check URL Logins"))
        self.check_api_login_directories.setToolTip(_translate("UrlToolsWindow", "This will scan your requested URL for any API endpoints"))
        self.check_api_login_directories.setText(_translate("UrlToolsWindow", "Check API Login"))
        self.website_bf_hidden_content_button.setToolTip(_translate("UrlToolsWindow", "Website bruteforcer to find hidden file and folder\n"
"Requires a wordlist to be used"))
        self.website_bf_hidden_content_button.setWhatsThis(_translate("UrlToolsWindow", "Website bruteforcer to find hidden file and folder\n"
"Requires a wordlist to be used"))
        self.website_bf_hidden_content_button.setText(_translate("UrlToolsWindow", "Website BF Hidden Content"))
        self.analytics_and_config_tab_widget.setTabText(self.analytics_and_config_tab_widget.indexOf(self.tab), _translate("UrlToolsWindow", "Analytics"))
        self.http_request_get_button.setText(_translate("UrlToolsWindow", "GET"))
        self.http_request_post_button.setText(_translate("UrlToolsWindow", "POST"))
        self.http_request_headers_button.setText(_translate("UrlToolsWindow", "HEADERS"))
        self.http_request_parse_button.setText(_translate("UrlToolsWindow", "PARSE"))
        self.http_request_html_button.setText(_translate("UrlToolsWindow", "HTML"))
        self.http_request_css_button.setText(_translate("UrlToolsWindow", "CSS"))
        self.http_request_referrer_button.setText(_translate("UrlToolsWindow", "Referrer"))
        self.http_request_headers_button_2.setText(_translate("UrlToolsWindow", "PUT"))
        self.http_request_headers_button_3.setText(_translate("UrlToolsWindow", "DELETE"))
        self.http_request_headers_button_4.setText(_translate("UrlToolsWindow", "CONNECT"))
        self.http_request_headers_button_5.setText(_translate("UrlToolsWindow", "OPTIONS"))
        self.http_request_headers_button_6.setText(_translate("UrlToolsWindow", "TRACE"))
        self.http_request_headers_button_7.setText(_translate("UrlToolsWindow", "PATCH"))
        self.analytics_and_config_tab_widget.setTabText(self.analytics_and_config_tab_widget.indexOf(self.Config_Functions_Tab), _translate("UrlToolsWindow", "Config Functions"))
        self.javascript_links_button.setText(_translate("UrlToolsWindow", "Javascript Links"))
        self.css_links_button.setText(_translate("UrlToolsWindow", "CSS Links"))
        self.scrape_website_fonts_button.setText(_translate("UrlToolsWindow", "Grab Website Font"))
        self.scrape_external_links_button.setText(_translate("UrlToolsWindow", "External Links"))
        self.scrape_imagesbutton.setText(_translate("UrlToolsWindow", "Images"))
        self.javascript_links_button_2.setText(_translate("UrlToolsWindow", "Get Core"))
        self.javascript_links_button_3.setText(_translate("UrlToolsWindow", "Page Details"))
        self.javascript_links_button_4.setText(_translate("UrlToolsWindow", "Javascript Links"))
        self.javascript_links_button_5.setText(_translate("UrlToolsWindow", "WhoIs"))
        self.javascript_links_button_6.setText(_translate("UrlToolsWindow", "Get Emails"))
        self.javascript_links_button_7.setText(_translate("UrlToolsWindow", "Get links"))
        self.javascript_links_button_8.setText(_translate("UrlToolsWindow", "Get Images Files"))
        self.javascript_links_button_9.setText(_translate("UrlToolsWindow", "Get CSS Files"))
        self.javascript_links_button_10.setText(_translate("UrlToolsWindow", "Get Cookies"))
        self.javascript_links_button_11.setText(_translate("UrlToolsWindow", "Get js files"))
        self.javascript_links_button_12.setText(_translate("UrlToolsWindow", "Get Headers"))
        self.javascript_links_button_13.setText(_translate("UrlToolsWindow", "Robots"))
        self.javascript_links_button_14.setText(_translate("UrlToolsWindow", "Detect-Fonts"))
        self.javascript_links_button_15.setText(_translate("UrlToolsWindow", "Virus Total"))
        self.javascript_links_button_16.setText(_translate("UrlToolsWindow", "Extract-Colors"))
        self.javascript_links_button_17.setText(_translate("UrlToolsWindow", "IP Location"))
        self.analytics_and_config_tab_widget.setTabText(self.analytics_and_config_tab_widget.indexOf(self.tab_3), _translate("UrlToolsWindow", "Website Source Code Content"))
        self.results_textwindow_label.setText(_translate("UrlToolsWindow", "Results"))
        self.connection_label.setText(_translate("UrlToolsWindow", "Connection Details"))
        self.link_diver_client_button.setText(_translate("UrlToolsWindow", "Link Diver"))
        self.url_blaster_client_button_2.setText(_translate("UrlToolsWindow", "URL Blaster"))
        self.QTabWidget.setTabText(self.QTabWidget.indexOf(self.WebsiteSourceCodeTab), _translate("UrlToolsWindow", "Website Source Code"))
        self.QTabWidget.setTabText(self.QTabWidget.indexOf(self.tab_5), _translate("UrlToolsWindow", "Website API"))
        self.save_results_path_checkbox.setText(_translate("UrlToolsWindow", "Save Results?"))
        self.google_mode_button.setText(_translate("UrlToolsWindow", "Google Mode"))
        self.scadamode_button.setText(_translate("UrlToolsWindow", "Sacada Mode"))
        self.scadamode2_button.setText(_translate("UrlToolsWindow", "Sacada 2 Mode"))
        self.scadamode3_button.setText(_translate("UrlToolsWindow", "Sacada 3 Mode"))
        self.tor_mode_button.setText(_translate("UrlToolsWindow", "TOR Mode"))
        self.save_results_path_textedit.setPlaceholderText(_translate("UrlToolsWindow", "Saved File Directory Path"))
