import sys
from PyQt5 import QtCore, QtGui, QtWidgets, uic


class DomainSorter(QMainWindow):
    def __init__(self):
        super().__init__()
        DomainSorter.setObjectName("DomainSorter")
        DomainSorter.resize(1287, 774)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(DomainSorter)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(DomainSorter)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1287, 774))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setStyleSheet("QSplitter::handle:horizontal {\n"
"margin: 4px 0px;\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"stop:0 rgba(255, 255, 255, 0), \n"
"stop:0.5 rgba(100, 100, 100, 100), \n"
"stop:1 rgba(255, 255, 255, 0));\n"
"image: url(:/icons/icons/splitter_handle_vertical.svg);\n"
"}")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(6)
        self.splitter.setObjectName("splitter")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.web3_tab = QtWidgets.QTabWidget(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.web3_tab.sizePolicy().hasHeightForWidth())
        self.web3_tab.setSizePolicy(sizePolicy)
        self.web3_tab.setStyleSheet("QTabWidget::pane { border: 0; }")
        self.web3_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.web3_tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.web3_tab.setObjectName("web3_tab")
        self.tab_proto = QtWidgets.QWidget()
        self.tab_proto.setObjectName("tab_proto")
        self.select_all_checkbox = QtWidgets.QCheckBox(self.tab_proto)
        self.select_all_checkbox.setGeometry(QtCore.QRect(160, 0, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.select_all_checkbox.setFont(font)
        self.select_all_checkbox.setCheckable(False)
        self.select_all_checkbox.setObjectName("select_all_checkbox")
        self.country_domain_tab = QtWidgets.QTabWidget(self.tab_proto)
        self.country_domain_tab.setGeometry(QtCore.QRect(10, 10, 461, 521))
        self.country_domain_tab.setObjectName("country_domain_tab")
        self.domain_page_one = QtWidgets.QWidget()
        self.domain_page_one.setObjectName("domain_page_one")
        self.checkBox_31 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_31.setGeometry(QtCore.QRect(200, 180, 78, 22))
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_23 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_23.setGeometry(QtCore.QRect(390, 180, 78, 22))
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_38 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_38.setGeometry(QtCore.QRect(110, 180, 78, 22))
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_51 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_51.setGeometry(QtCore.QRect(200, 270, 78, 22))
        self.checkBox_51.setObjectName("checkBox_51")
        self.checkBox_52 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_52.setGeometry(QtCore.QRect(110, 230, 78, 22))
        self.checkBox_52.setObjectName("checkBox_52")
        self.checkBox_40 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_40.setGeometry(QtCore.QRect(110, 160, 78, 22))
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_35 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_35.setGeometry(QtCore.QRect(290, 180, 78, 22))
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_57 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_57.setGeometry(QtCore.QRect(10, 270, 78, 22))
        self.checkBox_57.setObjectName("checkBox_57")
        self.checkBox_10 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_10.setGeometry(QtCore.QRect(200, 70, 78, 22))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_90 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_90.setGeometry(QtCore.QRect(390, 390, 78, 22))
        self.checkBox_90.setObjectName("checkBox_90")
        self.checkBox_102 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_102.setGeometry(QtCore.QRect(10, 410, 78, 22))
        self.checkBox_102.setObjectName("checkBox_102")
        self.checkBox_33 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_33.setGeometry(QtCore.QRect(390, 141, 78, 21))
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_93 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_93.setGeometry(QtCore.QRect(390, 411, 78, 21))
        self.checkBox_93.setObjectName("checkBox_93")
        self.checkBox_77 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_77.setGeometry(QtCore.QRect(10, 360, 78, 22))
        self.checkBox_77.setObjectName("checkBox_77")
        self.checkBox_26 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_26.setGeometry(QtCore.QRect(390, 160, 78, 22))
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_91 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_91.setGeometry(QtCore.QRect(200, 450, 78, 22))
        self.checkBox_91.setObjectName("checkBox_91")
        self.checkBox_9 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 70, 78, 22))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_4 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_4.setGeometry(QtCore.QRect(390, 30, 78, 22))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_15 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_15.setGeometry(QtCore.QRect(200, 90, 78, 22))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_100 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_100.setGeometry(QtCore.QRect(110, 430, 78, 22))
        self.checkBox_100.setObjectName("checkBox_100")
        self.checkBox_42 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_42.setGeometry(QtCore.QRect(10, 140, 78, 22))
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_59 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_59.setGeometry(QtCore.QRect(200, 210, 78, 22))
        self.checkBox_59.setObjectName("checkBox_59")
        self.checkBox_41 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_41.setGeometry(QtCore.QRect(290, 140, 78, 22))
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_53 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_53.setGeometry(QtCore.QRect(390, 231, 78, 21))
        self.checkBox_53.setObjectName("checkBox_53")
        self.checkBox_47 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_47.setGeometry(QtCore.QRect(290, 210, 78, 22))
        self.checkBox_47.setObjectName("checkBox_47")
        self.checkBox_78 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_78.setGeometry(QtCore.QRect(110, 360, 78, 22))
        self.checkBox_78.setObjectName("checkBox_78")
        self.checkBox_39 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_39.setGeometry(QtCore.QRect(200, 120, 78, 22))
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_89 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_89.setGeometry(QtCore.QRect(200, 410, 78, 22))
        self.checkBox_89.setObjectName("checkBox_89")
        self.checkBox_50 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_50.setGeometry(QtCore.QRect(390, 210, 78, 22))
        self.checkBox_50.setObjectName("checkBox_50")
        self.checkBox_25 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_25.setGeometry(QtCore.QRect(290, 160, 78, 22))
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_63 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_63.setGeometry(QtCore.QRect(390, 360, 78, 22))
        self.checkBox_63.setObjectName("checkBox_63")
        self.checkBox_6 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_6.setGeometry(QtCore.QRect(110, 30, 78, 22))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_65 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_65.setGeometry(QtCore.QRect(290, 340, 78, 22))
        self.checkBox_65.setObjectName("checkBox_65")
        self.checkBox_81 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_81.setGeometry(QtCore.QRect(290, 320, 78, 22))
        self.checkBox_81.setObjectName("checkBox_81")
        self.checkBox_86 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_86.setGeometry(QtCore.QRect(390, 430, 78, 22))
        self.checkBox_86.setObjectName("checkBox_86")
        self.checkBox_74 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_74.setGeometry(QtCore.QRect(110, 300, 78, 22))
        self.checkBox_74.setObjectName("checkBox_74")
        self.checkBox_66 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_66.setGeometry(QtCore.QRect(390, 340, 78, 22))
        self.checkBox_66.setObjectName("checkBox_66")
        self.checkBox_88 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_88.setGeometry(QtCore.QRect(10, 430, 78, 22))
        self.checkBox_88.setObjectName("checkBox_88")
        self.checkBox_75 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_75.setGeometry(QtCore.QRect(290, 360, 78, 22))
        self.checkBox_75.setObjectName("checkBox_75")
        self.checkBox_7 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_7.setGeometry(QtCore.QRect(10, 30, 78, 22))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_95 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_95.setGeometry(QtCore.QRect(290, 450, 78, 22))
        self.checkBox_95.setObjectName("checkBox_95")
        self.checkBox_61 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_61.setGeometry(QtCore.QRect(290, 230, 78, 22))
        self.checkBox_61.setObjectName("checkBox_61")
        self.checkBox_5 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_5.setGeometry(QtCore.QRect(200, 30, 78, 22))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_8 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_8.setGeometry(QtCore.QRect(110, 70, 78, 22))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_82 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_82.setGeometry(QtCore.QRect(10, 320, 78, 22))
        self.checkBox_82.setObjectName("checkBox_82")
        self.checkBox_96 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_96.setGeometry(QtCore.QRect(10, 390, 78, 22))
        self.checkBox_96.setObjectName("checkBox_96")
        self.checkBox_68 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_68.setGeometry(QtCore.QRect(10, 340, 78, 22))
        self.checkBox_68.setObjectName("checkBox_68")
        self.checkBox_28 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_28.setGeometry(QtCore.QRect(10, 160, 78, 22))
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_94 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_94.setGeometry(QtCore.QRect(110, 390, 78, 22))
        self.checkBox_94.setObjectName("checkBox_94")
        self.checkBox_34 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_34.setGeometry(QtCore.QRect(110, 120, 78, 22))
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_84 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_84.setGeometry(QtCore.QRect(200, 430, 78, 22))
        self.checkBox_84.setObjectName("checkBox_84")
        self.checkBox_24 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_24.setGeometry(QtCore.QRect(200, 160, 78, 22))
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_16 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_16.setGeometry(QtCore.QRect(390, 90, 78, 22))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_71 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_71.setGeometry(QtCore.QRect(200, 360, 78, 22))
        self.checkBox_71.setObjectName("checkBox_71")
        self.checkBox_56 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_56.setGeometry(QtCore.QRect(10, 210, 78, 22))
        self.checkBox_56.setObjectName("checkBox_56")
        self.checkBox_54 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_54.setGeometry(QtCore.QRect(110, 210, 78, 22))
        self.checkBox_54.setObjectName("checkBox_54")
        self.checkBox_97 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_97.setGeometry(QtCore.QRect(10, 450, 78, 22))
        self.checkBox_97.setObjectName("checkBox_97")
        self.checkBox_12 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_12.setGeometry(QtCore.QRect(290, 70, 78, 22))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_64 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_64.setGeometry(QtCore.QRect(200, 340, 78, 22))
        self.checkBox_64.setObjectName("checkBox_64")
        self.checkBox_62 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_62.setGeometry(QtCore.QRect(10, 230, 78, 22))
        self.checkBox_62.setObjectName("checkBox_62")
        self.checkBox_87 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_87.setGeometry(QtCore.QRect(290, 390, 78, 22))
        self.checkBox_87.setObjectName("checkBox_87")
        self.checkBox_11 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_11.setGeometry(QtCore.QRect(390, 70, 78, 22))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_55 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_55.setGeometry(QtCore.QRect(290, 270, 78, 22))
        self.checkBox_55.setObjectName("checkBox_55")
        self.checkBox_49 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_49.setGeometry(QtCore.QRect(200, 230, 78, 22))
        self.checkBox_49.setObjectName("checkBox_49")
        self.checkBox_3 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_3.setGeometry(QtCore.QRect(290, 30, 78, 22))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_72 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_72.setGeometry(QtCore.QRect(110, 320, 78, 22))
        self.checkBox_72.setObjectName("checkBox_72")
        self.checkBox_45 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_45.setGeometry(QtCore.QRect(290, 250, 78, 22))
        self.checkBox_45.setObjectName("checkBox_45")
        self.checkBox_83 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_83.setGeometry(QtCore.QRect(390, 450, 78, 22))
        self.checkBox_83.setObjectName("checkBox_83")
        self.checkBox_99 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_99.setGeometry(QtCore.QRect(200, 390, 78, 22))
        self.checkBox_99.setObjectName("checkBox_99")
        self.checkBox_32 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_32.setGeometry(QtCore.QRect(110, 140, 78, 22))
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkBox_20 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_20.setGeometry(QtCore.QRect(200, 50, 78, 22))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_79 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_79.setGeometry(QtCore.QRect(200, 300, 78, 22))
        self.checkBox_79.setObjectName("checkBox_79")
        self.checkBox_101 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_101.setGeometry(QtCore.QRect(290, 410, 78, 22))
        self.checkBox_101.setObjectName("checkBox_101")
        self.checkBox_73 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_73.setGeometry(QtCore.QRect(390, 321, 78, 21))
        self.checkBox_73.setObjectName("checkBox_73")
        self.checkBox_58 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_58.setGeometry(QtCore.QRect(110, 270, 78, 22))
        self.checkBox_58.setObjectName("checkBox_58")
        self.checkBox_30 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_30.setGeometry(QtCore.QRect(390, 120, 78, 22))
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkBox_46 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_46.setGeometry(QtCore.QRect(390, 250, 78, 22))
        self.checkBox_46.setObjectName("checkBox_46")
        self.checkBox_27 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_27.setGeometry(QtCore.QRect(290, 120, 78, 22))
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_67 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_67.setGeometry(QtCore.QRect(290, 300, 78, 22))
        self.checkBox_67.setObjectName("checkBox_67")
        self.checkBox_76 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_76.setGeometry(QtCore.QRect(10, 300, 78, 22))
        self.checkBox_76.setObjectName("checkBox_76")
        self.checkBox_48 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_48.setGeometry(QtCore.QRect(10, 250, 78, 22))
        self.checkBox_48.setObjectName("checkBox_48")
        self.checkBox_92 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_92.setGeometry(QtCore.QRect(110, 410, 78, 22))
        self.checkBox_92.setObjectName("checkBox_92")
        self.checkBox_98 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_98.setGeometry(QtCore.QRect(110, 450, 78, 22))
        self.checkBox_98.setObjectName("checkBox_98")
        self.checkBox_36 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_36.setGeometry(QtCore.QRect(10, 120, 78, 22))
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_70 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_70.setGeometry(QtCore.QRect(390, 300, 78, 22))
        self.checkBox_70.setObjectName("checkBox_70")
        self.checkBox_18 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_18.setGeometry(QtCore.QRect(110, 50, 78, 22))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_21 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_21.setGeometry(QtCore.QRect(390, 51, 78, 21))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_17 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_17.setGeometry(QtCore.QRect(290, 90, 78, 22))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_43 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_43.setGeometry(QtCore.QRect(390, 270, 78, 22))
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_60 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_60.setGeometry(QtCore.QRect(110, 250, 78, 22))
        self.checkBox_60.setObjectName("checkBox_60")
        self.checkBox_69 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_69.setGeometry(QtCore.QRect(200, 320, 78, 22))
        self.checkBox_69.setObjectName("checkBox_69")
        self.checkBox_14 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_14.setGeometry(QtCore.QRect(10, 90, 78, 22))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_29 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_29.setGeometry(QtCore.QRect(200, 140, 78, 22))
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_13 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_13.setGeometry(QtCore.QRect(110, 90, 78, 22))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_22 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_22.setGeometry(QtCore.QRect(290, 50, 78, 22))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_85 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_85.setGeometry(QtCore.QRect(290, 430, 78, 22))
        self.checkBox_85.setObjectName("checkBox_85")
        self.checkBox_19 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_19.setGeometry(QtCore.QRect(10, 50, 78, 22))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_80 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_80.setGeometry(QtCore.QRect(110, 340, 78, 22))
        self.checkBox_80.setObjectName("checkBox_80")
        self.checkBox_44 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_44.setGeometry(QtCore.QRect(200, 250, 78, 22))
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkBox_37 = QtWidgets.QCheckBox(self.domain_page_one)
        self.checkBox_37.setGeometry(QtCore.QRect(10, 180, 78, 22))
        self.checkBox_37.setObjectName("checkBox_37")
        self.country_domain_tab.addTab(self.domain_page_one, "")
        self.domain_page_two = QtWidgets.QWidget()
        self.domain_page_two.setObjectName("domain_page_two")
        self.checkBox_103 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_103.setGeometry(QtCore.QRect(200, 170, 78, 22))
        self.checkBox_103.setObjectName("checkBox_103")
        self.checkBox_104 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_104.setGeometry(QtCore.QRect(390, 170, 78, 22))
        self.checkBox_104.setObjectName("checkBox_104")
        self.checkBox_105 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_105.setGeometry(QtCore.QRect(110, 170, 78, 22))
        self.checkBox_105.setObjectName("checkBox_105")
        self.checkBox_106 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_106.setGeometry(QtCore.QRect(200, 260, 78, 22))
        self.checkBox_106.setObjectName("checkBox_106")
        self.checkBox_107 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_107.setGeometry(QtCore.QRect(110, 220, 78, 22))
        self.checkBox_107.setObjectName("checkBox_107")
        self.checkBox_108 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_108.setGeometry(QtCore.QRect(110, 150, 78, 22))
        self.checkBox_108.setObjectName("checkBox_108")
        self.checkBox_109 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_109.setGeometry(QtCore.QRect(290, 170, 78, 22))
        self.checkBox_109.setObjectName("checkBox_109")
        self.checkBox_110 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_110.setGeometry(QtCore.QRect(10, 260, 78, 22))
        self.checkBox_110.setObjectName("checkBox_110")
        self.checkBox_111 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_111.setGeometry(QtCore.QRect(200, 60, 78, 22))
        self.checkBox_111.setObjectName("checkBox_111")
        self.checkBox_112 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_112.setGeometry(QtCore.QRect(390, 380, 78, 22))
        self.checkBox_112.setObjectName("checkBox_112")
        self.checkBox_113 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_113.setGeometry(QtCore.QRect(10, 400, 78, 22))
        self.checkBox_113.setObjectName("checkBox_113")
        self.checkBox_114 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_114.setGeometry(QtCore.QRect(390, 131, 78, 21))
        self.checkBox_114.setObjectName("checkBox_114")
        self.checkBox_115 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_115.setGeometry(QtCore.QRect(390, 401, 78, 21))
        self.checkBox_115.setObjectName("checkBox_115")
        self.checkBox_116 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_116.setGeometry(QtCore.QRect(10, 350, 78, 22))
        self.checkBox_116.setObjectName("checkBox_116")
        self.checkBox_117 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_117.setGeometry(QtCore.QRect(390, 150, 78, 22))
        self.checkBox_117.setObjectName("checkBox_117")
        self.checkBox_118 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_118.setGeometry(QtCore.QRect(200, 440, 78, 22))
        self.checkBox_118.setObjectName("checkBox_118")
        self.checkBox_119 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_119.setGeometry(QtCore.QRect(10, 60, 78, 22))
        self.checkBox_119.setObjectName("checkBox_119")
        self.checkBox_120 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_120.setGeometry(QtCore.QRect(390, 20, 78, 22))
        self.checkBox_120.setObjectName("checkBox_120")
        self.checkBox_121 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_121.setGeometry(QtCore.QRect(200, 80, 78, 22))
        self.checkBox_121.setObjectName("checkBox_121")
        self.checkBox_122 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_122.setGeometry(QtCore.QRect(110, 420, 78, 22))
        self.checkBox_122.setObjectName("checkBox_122")
        self.checkBox_123 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_123.setGeometry(QtCore.QRect(10, 130, 78, 22))
        self.checkBox_123.setObjectName("checkBox_123")
        self.checkBox_124 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_124.setGeometry(QtCore.QRect(200, 200, 78, 22))
        self.checkBox_124.setObjectName("checkBox_124")
        self.checkBox_125 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_125.setGeometry(QtCore.QRect(290, 130, 78, 22))
        self.checkBox_125.setObjectName("checkBox_125")
        self.checkBox_126 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_126.setGeometry(QtCore.QRect(390, 221, 78, 21))
        self.checkBox_126.setObjectName("checkBox_126")
        self.checkBox_127 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_127.setGeometry(QtCore.QRect(290, 200, 78, 22))
        self.checkBox_127.setObjectName("checkBox_127")
        self.checkBox_128 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_128.setGeometry(QtCore.QRect(110, 350, 78, 22))
        self.checkBox_128.setObjectName("checkBox_128")
        self.checkBox_129 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_129.setGeometry(QtCore.QRect(200, 110, 78, 22))
        self.checkBox_129.setObjectName("checkBox_129")
        self.checkBox_130 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_130.setGeometry(QtCore.QRect(200, 400, 78, 22))
        self.checkBox_130.setObjectName("checkBox_130")
        self.checkBox_131 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_131.setGeometry(QtCore.QRect(390, 200, 78, 22))
        self.checkBox_131.setObjectName("checkBox_131")
        self.checkBox_132 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_132.setGeometry(QtCore.QRect(290, 150, 78, 22))
        self.checkBox_132.setObjectName("checkBox_132")
        self.checkBox_133 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_133.setGeometry(QtCore.QRect(390, 350, 78, 22))
        self.checkBox_133.setObjectName("checkBox_133")
        self.checkBox_134 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_134.setGeometry(QtCore.QRect(110, 20, 78, 22))
        self.checkBox_134.setObjectName("checkBox_134")
        self.checkBox_135 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_135.setGeometry(QtCore.QRect(290, 330, 78, 22))
        self.checkBox_135.setObjectName("checkBox_135")
        self.checkBox_136 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_136.setGeometry(QtCore.QRect(290, 310, 78, 22))
        self.checkBox_136.setObjectName("checkBox_136")
        self.checkBox_137 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_137.setGeometry(QtCore.QRect(390, 420, 78, 22))
        self.checkBox_137.setObjectName("checkBox_137")
        self.checkBox_138 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_138.setGeometry(QtCore.QRect(110, 290, 78, 22))
        self.checkBox_138.setObjectName("checkBox_138")
        self.checkBox_139 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_139.setGeometry(QtCore.QRect(390, 330, 78, 22))
        self.checkBox_139.setObjectName("checkBox_139")
        self.checkBox_140 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_140.setGeometry(QtCore.QRect(10, 420, 78, 22))
        self.checkBox_140.setObjectName("checkBox_140")
        self.checkBox_141 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_141.setGeometry(QtCore.QRect(290, 350, 78, 22))
        self.checkBox_141.setObjectName("checkBox_141")
        self.checkBox_142 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_142.setGeometry(QtCore.QRect(10, 20, 78, 22))
        self.checkBox_142.setObjectName("checkBox_142")
        self.checkBox_143 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_143.setGeometry(QtCore.QRect(290, 440, 78, 22))
        self.checkBox_143.setObjectName("checkBox_143")
        self.checkBox_144 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_144.setGeometry(QtCore.QRect(290, 220, 78, 22))
        self.checkBox_144.setObjectName("checkBox_144")
        self.checkBox_145 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_145.setGeometry(QtCore.QRect(200, 20, 78, 22))
        self.checkBox_145.setObjectName("checkBox_145")
        self.checkBox_146 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_146.setGeometry(QtCore.QRect(110, 60, 78, 22))
        self.checkBox_146.setObjectName("checkBox_146")
        self.checkBox_147 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_147.setGeometry(QtCore.QRect(10, 310, 78, 22))
        self.checkBox_147.setObjectName("checkBox_147")
        self.checkBox_148 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_148.setGeometry(QtCore.QRect(10, 380, 78, 22))
        self.checkBox_148.setObjectName("checkBox_148")
        self.checkBox_149 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_149.setGeometry(QtCore.QRect(10, 330, 78, 22))
        self.checkBox_149.setObjectName("checkBox_149")
        self.checkBox_150 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_150.setGeometry(QtCore.QRect(10, 150, 78, 22))
        self.checkBox_150.setObjectName("checkBox_150")
        self.checkBox_151 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_151.setGeometry(QtCore.QRect(110, 380, 78, 22))
        self.checkBox_151.setObjectName("checkBox_151")
        self.checkBox_152 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_152.setGeometry(QtCore.QRect(110, 110, 78, 22))
        self.checkBox_152.setObjectName("checkBox_152")
        self.checkBox_153 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_153.setGeometry(QtCore.QRect(200, 420, 78, 22))
        self.checkBox_153.setObjectName("checkBox_153")
        self.checkBox_154 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_154.setGeometry(QtCore.QRect(200, 150, 78, 22))
        self.checkBox_154.setObjectName("checkBox_154")
        self.checkBox_155 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_155.setGeometry(QtCore.QRect(390, 80, 78, 22))
        self.checkBox_155.setObjectName("checkBox_155")
        self.checkBox_156 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_156.setGeometry(QtCore.QRect(200, 350, 78, 22))
        self.checkBox_156.setObjectName("checkBox_156")
        self.checkBox_157 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_157.setGeometry(QtCore.QRect(10, 200, 78, 22))
        self.checkBox_157.setObjectName("checkBox_157")
        self.checkBox_158 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_158.setGeometry(QtCore.QRect(110, 200, 78, 22))
        self.checkBox_158.setObjectName("checkBox_158")
        self.checkBox_159 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_159.setGeometry(QtCore.QRect(10, 440, 78, 22))
        self.checkBox_159.setObjectName("checkBox_159")
        self.checkBox_160 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_160.setGeometry(QtCore.QRect(290, 60, 78, 22))
        self.checkBox_160.setObjectName("checkBox_160")
        self.checkBox_161 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_161.setGeometry(QtCore.QRect(200, 330, 78, 22))
        self.checkBox_161.setObjectName("checkBox_161")
        self.checkBox_162 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_162.setGeometry(QtCore.QRect(10, 220, 78, 22))
        self.checkBox_162.setObjectName("checkBox_162")
        self.checkBox_163 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_163.setGeometry(QtCore.QRect(290, 380, 78, 22))
        self.checkBox_163.setObjectName("checkBox_163")
        self.checkBox_164 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_164.setGeometry(QtCore.QRect(390, 60, 78, 22))
        self.checkBox_164.setObjectName("checkBox_164")
        self.checkBox_165 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_165.setGeometry(QtCore.QRect(290, 260, 78, 22))
        self.checkBox_165.setObjectName("checkBox_165")
        self.checkBox_166 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_166.setGeometry(QtCore.QRect(200, 220, 78, 22))
        self.checkBox_166.setObjectName("checkBox_166")
        self.checkBox_167 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_167.setGeometry(QtCore.QRect(290, 20, 78, 22))
        self.checkBox_167.setObjectName("checkBox_167")
        self.checkBox_168 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_168.setGeometry(QtCore.QRect(110, 310, 78, 22))
        self.checkBox_168.setObjectName("checkBox_168")
        self.checkBox_169 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_169.setGeometry(QtCore.QRect(290, 240, 78, 22))
        self.checkBox_169.setObjectName("checkBox_169")
        self.checkBox_170 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_170.setGeometry(QtCore.QRect(390, 440, 78, 22))
        self.checkBox_170.setObjectName("checkBox_170")
        self.checkBox_171 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_171.setGeometry(QtCore.QRect(200, 380, 78, 22))
        self.checkBox_171.setObjectName("checkBox_171")
        self.checkBox_172 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_172.setGeometry(QtCore.QRect(110, 130, 78, 22))
        self.checkBox_172.setObjectName("checkBox_172")
        self.checkBox_173 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_173.setGeometry(QtCore.QRect(200, 40, 78, 22))
        self.checkBox_173.setObjectName("checkBox_173")
        self.checkBox_174 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_174.setGeometry(QtCore.QRect(200, 290, 78, 22))
        self.checkBox_174.setObjectName("checkBox_174")
        self.checkBox_175 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_175.setGeometry(QtCore.QRect(290, 400, 78, 22))
        self.checkBox_175.setObjectName("checkBox_175")
        self.checkBox_176 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_176.setGeometry(QtCore.QRect(390, 311, 78, 21))
        self.checkBox_176.setObjectName("checkBox_176")
        self.checkBox_177 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_177.setGeometry(QtCore.QRect(110, 260, 78, 22))
        self.checkBox_177.setObjectName("checkBox_177")
        self.checkBox_178 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_178.setGeometry(QtCore.QRect(390, 110, 78, 22))
        self.checkBox_178.setObjectName("checkBox_178")
        self.checkBox_179 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_179.setGeometry(QtCore.QRect(390, 240, 78, 22))
        self.checkBox_179.setObjectName("checkBox_179")
        self.checkBox_180 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_180.setGeometry(QtCore.QRect(290, 110, 78, 22))
        self.checkBox_180.setObjectName("checkBox_180")
        self.checkBox_181 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_181.setGeometry(QtCore.QRect(290, 290, 78, 22))
        self.checkBox_181.setObjectName("checkBox_181")
        self.checkBox_182 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_182.setGeometry(QtCore.QRect(10, 290, 78, 22))
        self.checkBox_182.setObjectName("checkBox_182")
        self.checkBox_183 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_183.setGeometry(QtCore.QRect(10, 240, 78, 22))
        self.checkBox_183.setObjectName("checkBox_183")
        self.checkBox_184 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_184.setGeometry(QtCore.QRect(110, 400, 78, 22))
        self.checkBox_184.setObjectName("checkBox_184")
        self.checkBox_185 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_185.setGeometry(QtCore.QRect(110, 440, 78, 22))
        self.checkBox_185.setObjectName("checkBox_185")
        self.checkBox_186 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_186.setGeometry(QtCore.QRect(10, 110, 78, 22))
        self.checkBox_186.setObjectName("checkBox_186")
        self.checkBox_187 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_187.setGeometry(QtCore.QRect(390, 290, 78, 22))
        self.checkBox_187.setObjectName("checkBox_187")
        self.checkBox_188 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_188.setGeometry(QtCore.QRect(110, 40, 78, 22))
        self.checkBox_188.setObjectName("checkBox_188")
        self.checkBox_189 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_189.setGeometry(QtCore.QRect(390, 41, 78, 21))
        self.checkBox_189.setObjectName("checkBox_189")
        self.checkBox_190 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_190.setGeometry(QtCore.QRect(290, 80, 78, 22))
        self.checkBox_190.setObjectName("checkBox_190")
        self.checkBox_191 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_191.setGeometry(QtCore.QRect(390, 260, 78, 22))
        self.checkBox_191.setObjectName("checkBox_191")
        self.checkBox_192 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_192.setGeometry(QtCore.QRect(110, 240, 78, 22))
        self.checkBox_192.setObjectName("checkBox_192")
        self.checkBox_193 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_193.setGeometry(QtCore.QRect(200, 310, 78, 22))
        self.checkBox_193.setObjectName("checkBox_193")
        self.checkBox_194 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_194.setGeometry(QtCore.QRect(10, 80, 78, 22))
        self.checkBox_194.setObjectName("checkBox_194")
        self.checkBox_195 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_195.setGeometry(QtCore.QRect(200, 130, 78, 22))
        self.checkBox_195.setObjectName("checkBox_195")
        self.checkBox_196 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_196.setGeometry(QtCore.QRect(110, 80, 78, 22))
        self.checkBox_196.setObjectName("checkBox_196")
        self.checkBox_197 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_197.setGeometry(QtCore.QRect(290, 40, 78, 22))
        self.checkBox_197.setObjectName("checkBox_197")
        self.checkBox_198 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_198.setGeometry(QtCore.QRect(290, 420, 78, 22))
        self.checkBox_198.setObjectName("checkBox_198")
        self.checkBox_199 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_199.setGeometry(QtCore.QRect(10, 40, 78, 22))
        self.checkBox_199.setObjectName("checkBox_199")
        self.checkBox_200 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_200.setGeometry(QtCore.QRect(110, 330, 78, 22))
        self.checkBox_200.setObjectName("checkBox_200")
        self.checkBox_201 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_201.setGeometry(QtCore.QRect(200, 240, 78, 22))
        self.checkBox_201.setObjectName("checkBox_201")
        self.checkBox_202 = QtWidgets.QCheckBox(self.domain_page_two)
        self.checkBox_202.setGeometry(QtCore.QRect(10, 170, 78, 22))
        self.checkBox_202.setObjectName("checkBox_202")
        self.country_domain_tab.addTab(self.domain_page_two, "")
        self.country_domain_tab.raise_()
        self.select_all_checkbox.raise_()
        self.web3_tab.addTab(self.tab_proto, "")
        self.tab_pauses = QtWidgets.QWidget()
        self.tab_pauses.setObjectName("tab_pauses")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_pauses)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.popular_domains_grid = QtWidgets.QGridLayout()
        self.popular_domains_grid.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.popular_domains_grid.setSpacing(10)
        self.popular_domains_grid.setObjectName("popular_domains_grid")
        self.checkBox_211 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_211.setObjectName("checkBox_211")
        self.popular_domains_grid.addWidget(self.checkBox_211, 6, 2, 1, 1)
        self.checkBox_207 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_207.setObjectName("checkBox_207")
        self.popular_domains_grid.addWidget(self.checkBox_207, 5, 0, 1, 1)
        self.checkBox_215 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_215.setObjectName("checkBox_215")
        self.popular_domains_grid.addWidget(self.checkBox_215, 2, 1, 1, 1)
        self.checkBox_212 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_212.setObjectName("checkBox_212")
        self.popular_domains_grid.addWidget(self.checkBox_212, 6, 4, 1, 1)
        self.checkBox_214 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_214.setObjectName("checkBox_214")
        self.popular_domains_grid.addWidget(self.checkBox_214, 1, 1, 1, 1)
        self.checkBox_216 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_216.setObjectName("checkBox_216")
        self.popular_domains_grid.addWidget(self.checkBox_216, 3, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox.setObjectName("checkBox")
        self.popular_domains_grid.addWidget(self.checkBox, 0, 4, 1, 1)
        self.checkBox_205 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_205.setObjectName("checkBox_205")
        self.popular_domains_grid.addWidget(self.checkBox_205, 6, 1, 1, 1)
        self.checkBox_210 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_210.setObjectName("checkBox_210")
        self.popular_domains_grid.addWidget(self.checkBox_210, 5, 4, 1, 1)
        self.checkBox_204 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_204.setObjectName("checkBox_204")
        self.popular_domains_grid.addWidget(self.checkBox_204, 0, 0, 1, 1)
        self.checkBox_208 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_208.setObjectName("checkBox_208")
        self.popular_domains_grid.addWidget(self.checkBox_208, 5, 1, 1, 1)
        self.checkBox_209 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_209.setObjectName("checkBox_209")
        self.popular_domains_grid.addWidget(self.checkBox_209, 5, 2, 1, 1)
        self.checkBox_206 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_206.setObjectName("checkBox_206")
        self.popular_domains_grid.addWidget(self.checkBox_206, 6, 0, 1, 1)
        self.checkBox_213 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_213.setObjectName("checkBox_213")
        self.popular_domains_grid.addWidget(self.checkBox_213, 0, 2, 1, 1)
        self.checkBox_203 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_203.setObjectName("checkBox_203")
        self.popular_domains_grid.addWidget(self.checkBox_203, 0, 1, 1, 1)
        self.checkBox_217 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_217.setObjectName("checkBox_217")
        self.popular_domains_grid.addWidget(self.checkBox_217, 4, 1, 1, 1)
        self.checkBox_218 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_218.setObjectName("checkBox_218")
        self.popular_domains_grid.addWidget(self.checkBox_218, 1, 0, 1, 1)
        self.checkBox_219 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_219.setObjectName("checkBox_219")
        self.popular_domains_grid.addWidget(self.checkBox_219, 1, 2, 1, 1)
        self.checkBox_220 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_220.setObjectName("checkBox_220")
        self.popular_domains_grid.addWidget(self.checkBox_220, 1, 4, 1, 1)
        self.checkBox_221 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_221.setObjectName("checkBox_221")
        self.popular_domains_grid.addWidget(self.checkBox_221, 2, 0, 1, 1)
        self.checkBox_222 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_222.setObjectName("checkBox_222")
        self.popular_domains_grid.addWidget(self.checkBox_222, 2, 2, 1, 1)
        self.checkBox_223 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_223.setObjectName("checkBox_223")
        self.popular_domains_grid.addWidget(self.checkBox_223, 2, 3, 1, 1)
        self.checkBox_224 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_224.setObjectName("checkBox_224")
        self.popular_domains_grid.addWidget(self.checkBox_224, 2, 4, 1, 1)
        self.checkBox_225 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_225.setObjectName("checkBox_225")
        self.popular_domains_grid.addWidget(self.checkBox_225, 1, 3, 1, 1)
        self.checkBox_226 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_226.setObjectName("checkBox_226")
        self.popular_domains_grid.addWidget(self.checkBox_226, 0, 3, 1, 1)
        self.checkBox_227 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_227.setObjectName("checkBox_227")
        self.popular_domains_grid.addWidget(self.checkBox_227, 3, 0, 1, 1)
        self.checkBox_228 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_228.setObjectName("checkBox_228")
        self.popular_domains_grid.addWidget(self.checkBox_228, 3, 2, 1, 1)
        self.checkBox_229 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_229.setObjectName("checkBox_229")
        self.popular_domains_grid.addWidget(self.checkBox_229, 3, 3, 1, 1)
        self.checkBox_230 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_230.setObjectName("checkBox_230")
        self.popular_domains_grid.addWidget(self.checkBox_230, 3, 4, 1, 1)
        self.checkBox_231 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_231.setObjectName("checkBox_231")
        self.popular_domains_grid.addWidget(self.checkBox_231, 4, 0, 1, 1)
        self.checkBox_232 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_232.setObjectName("checkBox_232")
        self.popular_domains_grid.addWidget(self.checkBox_232, 4, 2, 1, 1)
        self.checkBox_233 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_233.setObjectName("checkBox_233")
        self.popular_domains_grid.addWidget(self.checkBox_233, 4, 3, 1, 1)
        self.checkBox_234 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_234.setObjectName("checkBox_234")
        self.popular_domains_grid.addWidget(self.checkBox_234, 5, 3, 1, 1)
        self.checkBox_235 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_235.setObjectName("checkBox_235")
        self.popular_domains_grid.addWidget(self.checkBox_235, 6, 3, 1, 1)
        self.checkBox_236 = QtWidgets.QCheckBox(self.tab_pauses)
        self.checkBox_236.setObjectName("checkBox_236")
        self.popular_domains_grid.addWidget(self.checkBox_236, 4, 4, 1, 1)
        self.gridLayout_5.addLayout(self.popular_domains_grid, 0, 0, 1, 1)
        self.web3_tab.addTab(self.tab_pauses, "")
        self.Web3_Domain_Manager = QtWidgets.QWidget()
        self.Web3_Domain_Manager.setObjectName("Web3_Domain_Manager")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Web3_Domain_Manager)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 450, 479, 85))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.stackedWidgetFuzzing_2 = QtWidgets.QStackedWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidgetFuzzing_2.sizePolicy().hasHeightForWidth())
        self.stackedWidgetFuzzing_2.setSizePolicy(sizePolicy)
        self.stackedWidgetFuzzing_2.setObjectName("stackedWidgetFuzzing_2")
        self.pageFuzzingUI_2 = QtWidgets.QWidget()
        self.pageFuzzingUI_2.setObjectName("pageFuzzingUI_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.pageFuzzingUI_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnFuzz_2 = QtWidgets.QPushButton(self.pageFuzzingUI_2)
        self.btnFuzz_2.setObjectName("btnFuzz_2")
        self.horizontalLayout_5.addWidget(self.btnFuzz_2)
        self.rBSuccessive_2 = QtWidgets.QRadioButton(self.pageFuzzingUI_2)
        self.rBSuccessive_2.setChecked(True)
        self.rBSuccessive_2.setObjectName("rBSuccessive_2")
        self.horizontalLayout_5.addWidget(self.rBSuccessive_2)
        self.rbConcurrent_2 = QtWidgets.QRadioButton(self.pageFuzzingUI_2)
        self.rbConcurrent_2.setObjectName("rbConcurrent_2")
        self.horizontalLayout_5.addWidget(self.rbConcurrent_2)
        self.rBExhaustive_2 = QtWidgets.QRadioButton(self.pageFuzzingUI_2)
        self.rBExhaustive_2.setObjectName("rBExhaustive_2")
        self.horizontalLayout_5.addWidget(self.rBExhaustive_2)
        self.stackedWidgetFuzzing_2.addWidget(self.pageFuzzingUI_2)
        self.pageFuzzingProgressBar_2 = QtWidgets.QWidget()
        self.pageFuzzingProgressBar_2.setObjectName("pageFuzzingProgressBar_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.pageFuzzingProgressBar_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.progressBarFuzzing_2 = QtWidgets.QProgressBar(self.pageFuzzingProgressBar_2)
        self.progressBarFuzzing_2.setProperty("value", 24)
        self.progressBarFuzzing_2.setObjectName("progressBarFuzzing_2")
        self.horizontalLayout_9.addWidget(self.progressBarFuzzing_2)
        self.stackedWidgetFuzzing_2.addWidget(self.pageFuzzingProgressBar_2)
        self.horizontalLayout_8.addWidget(self.stackedWidgetFuzzing_2)
        self.web3_tab.addTab(self.Web3_Domain_Manager, "")
        self.tab_fuzzing = QtWidgets.QWidget()
        self.tab_fuzzing.setObjectName("tab_fuzzing")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_fuzzing)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.listViewProtoLabels = GeneratorListView(self.tab_fuzzing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewProtoLabels.sizePolicy().hasHeightForWidth())
        self.listViewProtoLabels.setSizePolicy(sizePolicy)
        self.listViewProtoLabels.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listViewProtoLabels.setObjectName("listViewProtoLabels")
        self.verticalLayout_9.addWidget(self.listViewProtoLabels)
        self.bottomCorpDomains = QtWidgets.QGroupBox(self.tab_fuzzing)
        self.bottomCorpDomains.setObjectName("bottomCorpDomains")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.bottomCorpDomains)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stackedWidgetFuzzing = QtWidgets.QStackedWidget(self.bottomCorpDomains)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidgetFuzzing.sizePolicy().hasHeightForWidth())
        self.stackedWidgetFuzzing.setSizePolicy(sizePolicy)
        self.stackedWidgetFuzzing.setObjectName("stackedWidgetFuzzing")
        self.pageFuzzingUI = QtWidgets.QWidget()
        self.pageFuzzingUI.setObjectName("pageFuzzingUI")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.pageFuzzingUI)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RunCorp_Valid_CheckButton = QtWidgets.QPushButton(self.pageFuzzingUI)
        self.RunCorp_Valid_CheckButton.setObjectName("RunCorp_Valid_CheckButton")
        self.horizontalLayout_4.addWidget(self.RunCorp_Valid_CheckButton)
        self.one_after_anotherConncurnet = QtWidgets.QRadioButton(self.pageFuzzingUI)
        self.one_after_anotherConncurnet.setChecked(True)
        self.one_after_anotherConncurnet.setObjectName("one_after_anotherConncurnet")
        self.horizontalLayout_4.addWidget(self.one_after_anotherConncurnet)
        self.check_multiple_domainsConcurrent = QtWidgets.QRadioButton(self.pageFuzzingUI)
        self.check_multiple_domainsConcurrent.setObjectName("check_multiple_domainsConcurrent")
        self.horizontalLayout_4.addWidget(self.check_multiple_domainsConcurrent)
        self.multi_thread_multi_domainConcurrent = QtWidgets.QRadioButton(self.pageFuzzingUI)
        self.multi_thread_multi_domainConcurrent.setObjectName("multi_thread_multi_domainConcurrent")
        self.horizontalLayout_4.addWidget(self.multi_thread_multi_domainConcurrent)
        self.stackedWidgetFuzzing.addWidget(self.pageFuzzingUI)
        self.pageFuzzingProgressBar = QtWidgets.QWidget()
        self.pageFuzzingProgressBar.setObjectName("pageFuzzingProgressBar")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.pageFuzzingProgressBar)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.DomainBarFuzzing = QtWidgets.QProgressBar(self.pageFuzzingProgressBar)
        self.DomainBarFuzzing.setProperty("value", 24)
        self.DomainBarFuzzing.setObjectName("DomainBarFuzzing")
        self.horizontalLayout_7.addWidget(self.DomainBarFuzzing)
        self.stackedWidgetFuzzing.addWidget(self.pageFuzzingProgressBar)
        self.horizontalLayout_6.addWidget(self.stackedWidgetFuzzing)
        self.verticalLayout_9.addWidget(self.bottomCorpDomains)
        self.web3_tab.addTab(self.tab_fuzzing, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.web3_tab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.web3_tab.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.web3_tab)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.modulationLayout_2 = QtWidgets.QGridLayout()
        self.modulationLayout_2.setObjectName("modulationLayout_2")
        self.lBitLength = QtWidgets.QLabel(self.layoutWidget_2)
        self.lBitLength.setObjectName("lBitLength")
        self.modulationLayout_2.addWidget(self.lBitLength, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        self.label.setObjectName("label")
        self.modulationLayout_2.addWidget(self.label, 2, 2, 1, 1)
        self.lEncodingValue = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lEncodingValue.sizePolicy().hasHeightForWidth())
        self.lEncodingValue.setSizePolicy(sizePolicy)
        self.lEncodingValue.setObjectName("lEncodingValue")
        self.modulationLayout_2.addWidget(self.lEncodingValue, 0, 1, 1, 1)
        self.lSampleRateValue = QtWidgets.QLabel(self.layoutWidget_2)
        self.lSampleRateValue.setObjectName("lSampleRateValue")
        self.modulationLayout_2.addWidget(self.lSampleRateValue, 0, 3, 1, 1)
        self.lBitLenValue = QtWidgets.QLabel(self.layoutWidget_2)
        self.lBitLenValue.setObjectName("lBitLenValue")
        self.modulationLayout_2.addWidget(self.lBitLenValue, 3, 1, 1, 1)
        self.lCarrierPhaseValue = QtWidgets.QLabel(self.layoutWidget_2)
        self.lCarrierPhaseValue.setObjectName("lCarrierPhaseValue")
        self.modulationLayout_2.addWidget(self.lCarrierPhaseValue, 2, 1, 1, 1)
        self.lCarrierFrequency = QtWidgets.QLabel(self.layoutWidget_2)
        self.lCarrierFrequency.setObjectName("lCarrierFrequency")
        self.modulationLayout_2.addWidget(self.lCarrierFrequency, 1, 0, 1, 1)
        self.lModTypeValue = QtWidgets.QLabel(self.layoutWidget_2)
        self.lModTypeValue.setObjectName("lModTypeValue")
        self.modulationLayout_2.addWidget(self.lModTypeValue, 1, 3, 1, 1)
        self.label_carrier_phase = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_carrier_phase.setObjectName("label_carrier_phase")
        self.modulationLayout_2.addWidget(self.label_carrier_phase, 2, 0, 1, 1)
        self.labelBitsPerSymbol = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelBitsPerSymbol.setObjectName("labelBitsPerSymbol")
        self.modulationLayout_2.addWidget(self.labelBitsPerSymbol, 2, 3, 1, 1)
        self.lSampleRate = QtWidgets.QLabel(self.layoutWidget_2)
        self.lSampleRate.setObjectName("lSampleRate")
        self.modulationLayout_2.addWidget(self.lSampleRate, 0, 2, 1, 1)
        self.lModType = QtWidgets.QLabel(self.layoutWidget_2)
        self.lModType.setObjectName("lModType")
        self.modulationLayout_2.addWidget(self.lModType, 1, 2, 1, 1)
        self.lParamCaption = QtWidgets.QLabel(self.layoutWidget_2)
        self.lParamCaption.setObjectName("lParamCaption")
        self.modulationLayout_2.addWidget(self.lParamCaption, 3, 2, 1, 1)
        self.TotalSelected = QtWidgets.QLabel(self.layoutWidget_2)
        self.TotalSelected.setObjectName("TotalSelected")
        self.modulationLayout_2.addWidget(self.TotalSelected, 0, 0, 1, 1)
        self.lCarrierFreqValue = QtWidgets.QLabel(self.layoutWidget_2)
        self.lCarrierFreqValue.setObjectName("lCarrierFreqValue")
        self.modulationLayout_2.addWidget(self.lCarrierFreqValue, 1, 1, 1, 1)
        self.labelParameterValues = ElidedLabel(self.layoutWidget_2)
        self.labelParameterValues.setObjectName("labelParameterValues")
        self.modulationLayout_2.addWidget(self.labelParameterValues, 3, 3, 1, 1)
        self.gridLayout_6.addLayout(self.modulationLayout_2, 0, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.layoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 1, 0, 1, 3)
        self.cBoxModulations = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cBoxModulations.setObjectName("cBoxModulations")
        self.cBoxModulations.addItem("")
        self.cBoxModulations.addItem("")
        self.gridLayout_6.addWidget(self.cBoxModulations, 2, 1, 1, 1)
        self.prBarGeneration = QtWidgets.QProgressBar(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prBarGeneration.sizePolicy().hasHeightForWidth())
        self.prBarGeneration.setSizePolicy(sizePolicy)
        self.prBarGeneration.setProperty("value", 0)
        self.prBarGeneration.setObjectName("prBarGeneration")
        self.gridLayout_6.addWidget(self.prBarGeneration, 5, 0, 1, 1)
        self.btnSend = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnSend.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.btnSend.setIcon(icon)
        self.btnSend.setObjectName("btnSend")
        self.gridLayout_6.addWidget(self.btnSend, 5, 2, 1, 1)
        self.btnEditModulation = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnEditModulation.setObjectName("btnEditModulation")
        self.gridLayout_6.addWidget(self.btnEditModulation, 2, 2, 1, 1)
        self.lModulation = QtWidgets.QLabel(self.layoutWidget_2)
        self.lModulation.setObjectName("lModulation")
        self.gridLayout_6.addWidget(self.lModulation, 2, 0, 1, 1)
        self.btnGenerate = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnGenerate.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.btnGenerate.setIcon(icon)
        self.btnGenerate.setObjectName("btnGenerate")
        self.gridLayout_6.addWidget(self.btnGenerate, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.report_tabel_for_results = GeneratorTableView(self.layoutWidget)
        self.report_tabel_for_results.setAcceptDrops(True)
        self.report_tabel_for_results.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.report_tabel_for_results.setDragEnabled(False)
        self.report_tabel_for_results.setDragDropOverwriteMode(False)
        self.report_tabel_for_results.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.report_tabel_for_results.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.report_tabel_for_results.setAlternatingRowColors(True)
        self.report_tabel_for_results.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.report_tabel_for_results.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.report_tabel_for_results.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.report_tabel_for_results.setShowGrid(False)
        self.report_tabel_for_results.setObjectName("report_tabel_for_results")
        self.report_tabel_for_results.horizontalHeader().setHighlightSections(False)
        self.report_tabel_for_results.verticalHeader().setHighlightSections(False)
        self.gridLayout_2.addWidget(self.report_tabel_for_results, 1, 0, 1, 8)
        self.btnNetworkSDRSend = QtWidgets.QPushButton(self.layoutWidget)
        icon = QtGui.QIcon.fromTheme("network-wired")
        self.btnNetworkSDRSend.setIcon(icon)
        self.btnNetworkSDRSend.setCheckable(True)
        self.btnNetworkSDRSend.setObjectName("btnNetworkSDRSend")
        self.gridLayout_2.addWidget(self.btnNetworkSDRSend, 2, 0, 1, 1)
        self.cbViewType = QtWidgets.QComboBox(self.layoutWidget)
        self.cbViewType.setObjectName("cbViewType")
        self.cbViewType.addItem("")
        self.cbViewType.addItem("")
        self.cbViewType.addItem("")
        self.gridLayout_2.addWidget(self.cbViewType, 2, 7, 1, 1)
        self.lViewType = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lViewType.sizePolicy().hasHeightForWidth())
        self.lViewType.setSizePolicy(sizePolicy)
        self.lViewType.setObjectName("lViewType")
        self.gridLayout_2.addWidget(self.lViewType, 2, 6, 1, 1)
        self.btnRfCatSend = QtWidgets.QPushButton(self.layoutWidget)
        icon = QtGui.QIcon.fromTheme("network-wireless")
        self.btnRfCatSend.setIcon(icon)
        self.btnRfCatSend.setObjectName("btnRfCatSend")
        self.gridLayout_2.addWidget(self.btnRfCatSend, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Domain_Results_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Domain_Results_label.sizePolicy().hasHeightForWidth())
        self.Domain_Results_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.Domain_Results_label.setFont(font)
        self.Domain_Results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Domain_Results_label.setObjectName("Domain_Results_label")
        self.horizontalLayout.addWidget(self.Domain_Results_label)
        self.btnSave = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.btnSave.setIcon(icon)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnOpen = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpen.sizePolicy().hasHeightForWidth())
        self.btnOpen.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btnOpen.setIcon(icon)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout.addWidget(self.btnOpen)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 8)
        self.lEstimatedTime = QtWidgets.QLabel(self.layoutWidget)
        self.lEstimatedTime.setObjectName("lEstimatedTime")
        self.gridLayout_2.addWidget(self.lEstimatedTime, 2, 3, 1, 1)
        self.btnFZSave = QtWidgets.QPushButton(self.layoutWidget)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.btnFZSave.setIcon(icon)
        self.btnFZSave.setObjectName("btnFZSave")
        self.gridLayout_2.addWidget(self.btnFZSave, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(38, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.splitter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.retranslateUi(DomainSorter)
        self.web3_tab.setCurrentIndex(0)
        self.country_domain_tab.setCurrentIndex(0)
        self.stackedWidgetFuzzing_2.setCurrentIndex(0)
        self.stackedWidgetFuzzing.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DomainSorter)
        button.clicked.connect(self.pushButton)

    def pushButton(self):
        # Add your button function logic here
        print("Button clicked!")

    def button_clicked(self):
        # Add your button function logic here
        print("Button clicked!")






















    def retranslateUi(self, DomainSorter):
        _translate = QtCore.QCoreApplication.translate
        DomainSorter.setWindowTitle(_translate("DomainSorter", "Form"))
        self.select_all_checkbox.setText(_translate("DomainSorter", "Select All"))
        self.checkBox_31.setText(_translate("DomainSorter", ".ca"))
        self.checkBox_23.setText(_translate("DomainSorter", ".cd"))
        self.checkBox_38.setText(_translate("DomainSorter", ".bz"))
        self.checkBox_51.setText(_translate("DomainSorter", ".dm"))
        self.checkBox_52.setText(_translate("DomainSorter", ".cn"))
        self.checkBox_40.setText(_translate("DomainSorter", ".bs"))
        self.checkBox_35.setText(_translate("DomainSorter", ".cc"))
        self.checkBox_57.setText(_translate("DomainSorter", ".dj"))
        self.checkBox_10.setText(_translate("DomainSorter", ".as"))
        self.checkBox_90.setText(_translate("DomainSorter", ".gn"))
        self.checkBox_102.setText(_translate("DomainSorter", ".gp"))
        self.checkBox_33.setText(_translate("DomainSorter", ".bo"))
        self.checkBox_93.setText(_translate("DomainSorter", ".gt"))
        self.checkBox_77.setText(_translate("DomainSorter", ".gb"))
        self.checkBox_26.setText(_translate("DomainSorter", ".bw"))
        self.checkBox_91.setText(_translate("DomainSorter", ".ht"))
        self.checkBox_9.setText(_translate("DomainSorter", ".aq"))
        self.checkBox_4.setText(_translate("DomainSorter", ".ag"))
        self.checkBox_15.setText(_translate("DomainSorter", ".az"))
        self.checkBox_100.setText(_translate("DomainSorter", ".gw"))
        self.checkBox_42.setText(_translate("DomainSorter", ".bi"))
        self.checkBox_59.setText(_translate("DomainSorter", ".ch"))
        self.checkBox_41.setText(_translate("DomainSorter", ".bn"))
        self.checkBox_53.setText(_translate("DomainSorter", ".cu"))
        self.checkBox_47.setText(_translate("DomainSorter", ".ci"))
        self.checkBox_78.setText(_translate("DomainSorter", ".gd"))
        self.checkBox_39.setText(_translate("DomainSorter", ".bf"))
        self.checkBox_89.setText(_translate("DomainSorter", ".gr"))
        self.checkBox_50.setText(_translate("DomainSorter", ".ck"))
        self.checkBox_25.setText(_translate("DomainSorter", ".bv"))
        self.checkBox_63.setText(_translate("DomainSorter", ".gg"))
        self.checkBox_6.setText(_translate("DomainSorter", ".ad"))
        self.checkBox_65.setText(_translate("DomainSorter", ".fr"))
        self.checkBox_81.setText(_translate("DomainSorter", ".fi"))
        self.checkBox_86.setText(_translate("DomainSorter", ".hm"))
        self.checkBox_74.setText(_translate("DomainSorter", ".edu"))
        self.checkBox_66.setText(_translate("DomainSorter", ".ga"))
        self.checkBox_88.setText(_translate("DomainSorter", ".gu"))
        self.checkBox_75.setText(_translate("DomainSorter", ".gf"))
        self.checkBox_7.setText(_translate("DomainSorter", ".ac"))
        self.checkBox_95.setText(_translate("DomainSorter", ".hu"))
        self.checkBox_61.setText(_translate("DomainSorter", ".cr"))
        self.checkBox_5.setText(_translate("DomainSorter", ".ae"))
        self.checkBox_8.setText(_translate("DomainSorter", ".ar"))
        self.checkBox_82.setText(_translate("DomainSorter", ".es"))
        self.checkBox_96.setText(_translate("DomainSorter", ".gh"))
        self.checkBox_68.setText(_translate("DomainSorter", ".fk"))
        self.checkBox_28.setText(_translate("DomainSorter", ".br"))
        self.checkBox_94.setText(_translate("DomainSorter", ".gi"))
        self.checkBox_34.setText(_translate("DomainSorter", ".be"))
        self.checkBox_84.setText(_translate("DomainSorter", ".gy"))
        self.checkBox_24.setText(_translate("DomainSorter", ".bt"))
        self.checkBox_16.setText(_translate("DomainSorter", ".bb"))
        self.checkBox_71.setText(_translate("DomainSorter", ".ge"))
        self.checkBox_56.setText(_translate("DomainSorter", ".cf"))
        self.checkBox_54.setText(_translate("DomainSorter", ".cg"))
        self.checkBox_97.setText(_translate("DomainSorter", ".hn"))
        self.checkBox_12.setText(_translate("DomainSorter", ".at"))
        self.checkBox_64.setText(_translate("DomainSorter", ".fo"))
        self.checkBox_62.setText(_translate("DomainSorter", ".cm"))
        self.checkBox_87.setText(_translate("DomainSorter", ".gm"))
        self.checkBox_11.setText(_translate("DomainSorter", ".au"))
        self.checkBox_55.setText(_translate("DomainSorter", ".do"))
        self.checkBox_49.setText(_translate("DomainSorter", ".co"))
        self.checkBox_3.setText(_translate("DomainSorter", ".af"))
        self.checkBox_72.setText(_translate("DomainSorter", ".et"))
        self.checkBox_45.setText(_translate("DomainSorter", ".cz"))
        self.checkBox_83.setText(_translate("DomainSorter", ".id"))
        self.checkBox_99.setText(_translate("DomainSorter", ".gl"))
        self.checkBox_32.setText(_translate("DomainSorter", ".bj"))
        self.checkBox_20.setText(_translate("DomainSorter", ".am"))
        self.checkBox_79.setText(_translate("DomainSorter", ".ee"))
        self.checkBox_101.setText(_translate("DomainSorter", ".gs"))
        self.checkBox_73.setText(_translate("DomainSorter", ".fj"))
        self.checkBox_58.setText(_translate("DomainSorter", ".dk"))
        self.checkBox_30.setText(_translate("DomainSorter", ".bh"))
        self.checkBox_46.setText(_translate("DomainSorter", ".de"))
        self.checkBox_27.setText(_translate("DomainSorter", ".bg"))
        self.checkBox_67.setText(_translate("DomainSorter", ".eg"))
        self.checkBox_76.setText(_translate("DomainSorter", ".ec"))
        self.checkBox_48.setText(_translate("DomainSorter", ".cv"))
        self.checkBox_92.setText(_translate("DomainSorter", ".gq"))
        self.checkBox_98.setText(_translate("DomainSorter", ".hr"))
        self.checkBox_36.setText(_translate("DomainSorter", ".bd"))
        self.checkBox_70.setText(_translate("DomainSorter", ".er"))
        self.checkBox_18.setText(_translate("DomainSorter", ".al"))
        self.checkBox_21.setText(_translate("DomainSorter", ".ao"))
        self.checkBox_17.setText(_translate("DomainSorter", ".ba"))
        self.checkBox_43.setText(_translate("DomainSorter", ".dz"))
        self.checkBox_60.setText(_translate("DomainSorter", ".cx"))
        self.checkBox_69.setText(_translate("DomainSorter", ".eu"))
        self.checkBox_14.setText(_translate("DomainSorter", ".aw"))
        self.checkBox_29.setText(_translate("DomainSorter", ".bm"))
        self.checkBox_13.setText(_translate("DomainSorter", ".ax"))
        self.checkBox_22.setText(_translate("DomainSorter", ".an"))
        self.checkBox_85.setText(_translate("DomainSorter", ".hk"))
        self.checkBox_19.setText(_translate("DomainSorter", ".ai"))
        self.checkBox_80.setText(_translate("DomainSorter", ".fm"))
        self.checkBox_44.setText(_translate("DomainSorter", ".cy"))
        self.checkBox_37.setText(_translate("DomainSorter", ".by"))
        self.country_domain_tab.setTabText(self.country_domain_tab.indexOf(self.domain_page_one), _translate("DomainSorter", "Page 1"))
        self.checkBox_103.setText(_translate("DomainSorter", ".ca"))
        self.checkBox_104.setText(_translate("DomainSorter", ".cd"))
        self.checkBox_105.setText(_translate("DomainSorter", ".bz"))
        self.checkBox_106.setText(_translate("DomainSorter", ".dm"))
        self.checkBox_107.setText(_translate("DomainSorter", ".cn"))
        self.checkBox_108.setText(_translate("DomainSorter", ".bs"))
        self.checkBox_109.setText(_translate("DomainSorter", ".cc"))
        self.checkBox_110.setText(_translate("DomainSorter", ".dj"))
        self.checkBox_111.setText(_translate("DomainSorter", ".as"))
        self.checkBox_112.setText(_translate("DomainSorter", ".gn"))
        self.checkBox_113.setText(_translate("DomainSorter", ".gp"))
        self.checkBox_114.setText(_translate("DomainSorter", ".bo"))
        self.checkBox_115.setText(_translate("DomainSorter", ".gt"))
        self.checkBox_116.setText(_translate("DomainSorter", ".gb"))
        self.checkBox_117.setText(_translate("DomainSorter", ".bw"))
        self.checkBox_118.setText(_translate("DomainSorter", ".ht"))
        self.checkBox_119.setText(_translate("DomainSorter", ".aq"))
        self.checkBox_120.setText(_translate("DomainSorter", ".ag"))
        self.checkBox_121.setText(_translate("DomainSorter", ".az"))
        self.checkBox_122.setText(_translate("DomainSorter", ".gw"))
        self.checkBox_123.setText(_translate("DomainSorter", ".bi"))
        self.checkBox_124.setText(_translate("DomainSorter", ".ch"))
        self.checkBox_125.setText(_translate("DomainSorter", ".bn"))
        self.checkBox_126.setText(_translate("DomainSorter", ".cu"))
        self.checkBox_127.setText(_translate("DomainSorter", ".ci"))
        self.checkBox_128.setText(_translate("DomainSorter", ".gd"))
        self.checkBox_129.setText(_translate("DomainSorter", ".bf"))
        self.checkBox_130.setText(_translate("DomainSorter", ".gr"))
        self.checkBox_131.setText(_translate("DomainSorter", ".ck"))
        self.checkBox_132.setText(_translate("DomainSorter", ".bv"))
        self.checkBox_133.setText(_translate("DomainSorter", ".gg"))
        self.checkBox_134.setText(_translate("DomainSorter", ".ad"))
        self.checkBox_135.setText(_translate("DomainSorter", ".fr"))
        self.checkBox_136.setText(_translate("DomainSorter", ".fi"))
        self.checkBox_137.setText(_translate("DomainSorter", ".hm"))
        self.checkBox_138.setText(_translate("DomainSorter", ".edu"))
        self.checkBox_139.setText(_translate("DomainSorter", ".ga"))
        self.checkBox_140.setText(_translate("DomainSorter", ".gu"))
        self.checkBox_141.setText(_translate("DomainSorter", ".gf"))
        self.checkBox_142.setText(_translate("DomainSorter", ".ac"))
        self.checkBox_143.setText(_translate("DomainSorter", ".hu"))
        self.checkBox_144.setText(_translate("DomainSorter", ".cr"))
        self.checkBox_145.setText(_translate("DomainSorter", ".ae"))
        self.checkBox_146.setText(_translate("DomainSorter", ".ar"))
        self.checkBox_147.setText(_translate("DomainSorter", ".es"))
        self.checkBox_148.setText(_translate("DomainSorter", ".gh"))
        self.checkBox_149.setText(_translate("DomainSorter", ".fk"))
        self.checkBox_150.setText(_translate("DomainSorter", ".br"))
        self.checkBox_151.setText(_translate("DomainSorter", ".gi"))
        self.checkBox_152.setText(_translate("DomainSorter", ".be"))
        self.checkBox_153.setText(_translate("DomainSorter", ".gy"))
        self.checkBox_154.setText(_translate("DomainSorter", ".bt"))
        self.checkBox_155.setText(_translate("DomainSorter", ".bb"))
        self.checkBox_156.setText(_translate("DomainSorter", ".ge"))
        self.checkBox_157.setText(_translate("DomainSorter", ".cf"))
        self.checkBox_158.setText(_translate("DomainSorter", ".cg"))
        self.checkBox_159.setText(_translate("DomainSorter", ".hn"))
        self.checkBox_160.setText(_translate("DomainSorter", ".at"))
        self.checkBox_161.setText(_translate("DomainSorter", ".fo"))
        self.checkBox_162.setText(_translate("DomainSorter", ".cm"))
        self.checkBox_163.setText(_translate("DomainSorter", ".gm"))
        self.checkBox_164.setText(_translate("DomainSorter", ".au"))
        self.checkBox_165.setText(_translate("DomainSorter", ".do"))
        self.checkBox_166.setText(_translate("DomainSorter", ".co"))
        self.checkBox_167.setText(_translate("DomainSorter", ".af"))
        self.checkBox_168.setText(_translate("DomainSorter", ".et"))
        self.checkBox_169.setText(_translate("DomainSorter", ".cz"))
        self.checkBox_170.setText(_translate("DomainSorter", ".id"))
        self.checkBox_171.setText(_translate("DomainSorter", ".gl"))
        self.checkBox_172.setText(_translate("DomainSorter", ".bj"))
        self.checkBox_173.setText(_translate("DomainSorter", ".am"))
        self.checkBox_174.setText(_translate("DomainSorter", ".ee"))
        self.checkBox_175.setText(_translate("DomainSorter", ".gs"))
        self.checkBox_176.setText(_translate("DomainSorter", ".fj"))
        self.checkBox_177.setText(_translate("DomainSorter", ".dk"))
        self.checkBox_178.setText(_translate("DomainSorter", ".bh"))
        self.checkBox_179.setText(_translate("DomainSorter", ".de"))
        self.checkBox_180.setText(_translate("DomainSorter", ".bg"))
        self.checkBox_181.setText(_translate("DomainSorter", ".eg"))
        self.checkBox_182.setText(_translate("DomainSorter", ".ec"))
        self.checkBox_183.setText(_translate("DomainSorter", ".cv"))
        self.checkBox_184.setText(_translate("DomainSorter", ".gq"))
        self.checkBox_185.setText(_translate("DomainSorter", ".hr"))
        self.checkBox_186.setText(_translate("DomainSorter", ".bd"))
        self.checkBox_187.setText(_translate("DomainSorter", ".er"))
        self.checkBox_188.setText(_translate("DomainSorter", ".al"))
        self.checkBox_189.setText(_translate("DomainSorter", ".ao"))
        self.checkBox_190.setText(_translate("DomainSorter", ".ba"))
        self.checkBox_191.setText(_translate("DomainSorter", ".dz"))
        self.checkBox_192.setText(_translate("DomainSorter", ".cx"))
        self.checkBox_193.setText(_translate("DomainSorter", ".eu"))
        self.checkBox_194.setText(_translate("DomainSorter", ".aw"))
        self.checkBox_195.setText(_translate("DomainSorter", ".bm"))
        self.checkBox_196.setText(_translate("DomainSorter", ".ax"))
        self.checkBox_197.setText(_translate("DomainSorter", ".an"))
        self.checkBox_198.setText(_translate("DomainSorter", ".hk"))
        self.checkBox_199.setText(_translate("DomainSorter", ".ai"))
        self.checkBox_200.setText(_translate("DomainSorter", ".fm"))
        self.checkBox_201.setText(_translate("DomainSorter", ".cy"))
        self.checkBox_202.setText(_translate("DomainSorter", ".by"))
        self.country_domain_tab.setTabText(self.country_domain_tab.indexOf(self.domain_page_two), _translate("DomainSorter", "Page 2"))
        self.web3_tab.setTabText(self.web3_tab.indexOf(self.tab_proto), _translate("DomainSorter", "Countries"))
        self.checkBox_211.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_207.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_215.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_212.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_214.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_216.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox.setText(_translate("DomainSorter", ".eu"))
        self.checkBox_205.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_210.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_204.setText(_translate("DomainSorter", ".com"))
        self.checkBox_208.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_209.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_206.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_213.setText(_translate("DomainSorter", ".shop"))
        self.checkBox_203.setText(_translate("DomainSorter", ".biz"))
        self.checkBox_217.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_218.setText(_translate("DomainSorter", ".xyz"))
        self.checkBox_219.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_220.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_221.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_222.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_223.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_224.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_225.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_226.setText(_translate("DomainSorter", ".link"))
        self.checkBox_227.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_228.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_229.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_230.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_231.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_232.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_233.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_234.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_235.setText(_translate("DomainSorter", "CheckBox"))
        self.checkBox_236.setText(_translate("DomainSorter", "CheckBox"))
        self.web3_tab.setTabText(self.web3_tab.indexOf(self.tab_pauses), _translate("DomainSorter", "Domains"))
        self.groupBox_2.setTitle(_translate("DomainSorter", "Add fuzzing values to generated data"))
        self.btnFuzz_2.setText(_translate("DomainSorter", "Fuzz"))
        self.rBSuccessive_2.setToolTip(_translate("DomainSorter", "<html><head/><body><p>For multiple labels per message the fuzzed values are inserted <span style=\" font-weight:600;\">one-by-one</span>.</p></body></html>"))
        self.rBSuccessive_2.setText(_translate("DomainSorter", "S&uccessive"))
        self.rbConcurrent_2.setToolTip(_translate("DomainSorter", "<html><head/><body><p>For multiple labels per message the labels are fuzzed <span style=\" font-weight:600;\">at the same time</span>.</p></body></html>"))
        self.rbConcurrent_2.setText(_translate("DomainSorter", "&Concurrent"))
        self.rBExhaustive_2.setToolTip(_translate("DomainSorter", "<html><head/><body><p>For multiple labels per message the fuzzed values are inserted in <span style=\" font-weight:600;\">all possible combinations</span>.</p></body></html>"))
        self.rBExhaustive_2.setText(_translate("DomainSorter", "E&xhaustive"))
        self.progressBarFuzzing_2.setFormat(_translate("DomainSorter", "%v/%m"))
        self.web3_tab.setTabText(self.web3_tab.indexOf(self.Web3_Domain_Manager), _translate("DomainSorter", "Web3"))
        self.bottomCorpDomains.setTitle(_translate("DomainSorter", "Add fuzzing values to generated data"))
        self.RunCorp_Valid_CheckButton.setText(_translate("DomainSorter", "Fuzz"))
        self.one_after_anotherConncurnet.setToolTip(_translate("DomainSorter", "<html><head/><body><p>For multiple labels per message the fuzzed values are inserted <span style=\" font-weight:600;\">one-by-one</span>.</p></body></html>"))
        self.one_after_anotherConncurnet.setText(_translate("DomainSorter", "S&uccessive"))
        self.check_multiple_domainsConcurrent.setToolTip(_translate("DomainSorter", "<html><head/><body><p>For multiple labels per message the labels are fuzzed <span style=\" font-weight:600;\">at the same time</span>.</p></body></html>"))
        self.check_multiple_domainsConcurrent.setText(_translate("DomainSorter", "&Concurrent"))
        self.multi_thread_multi_domainConcurrent.setToolTip(_translate("DomainSorter", "<html><head/><body><p>For multiple labels per message the fuzzed values are inserted in <span style=\" font-weight:600;\">all possible combinations</span>.</p></body></html>"))
        self.multi_thread_multi_domainConcurrent.setText(_translate("DomainSorter", "E&xhaustive"))
        self.DomainBarFuzzing.setFormat(_translate("DomainSorter", "%v/%m"))
        self.web3_tab.setTabText(self.web3_tab.indexOf(self.tab_fuzzing), _translate("DomainSorter", "Corperations"))
        self.web3_tab.setTabText(self.web3_tab.indexOf(self.tab_2), _translate("DomainSorter", "Bussiness"))
        self.web3_tab.setTabText(self.web3_tab.indexOf(self.tab_3), _translate("DomainSorter", "Franchise"))
        self.lBitLength.setText(_translate("DomainSorter", "Symbol Length:"))
        self.label.setText(_translate("DomainSorter", "Bits per Symbol:"))
        self.lEncodingValue.setText(_translate("DomainSorter", "-"))
        self.lSampleRateValue.setText(_translate("DomainSorter", "TextLabel"))
        self.lBitLenValue.setText(_translate("DomainSorter", "TextLabel"))
        self.lCarrierPhaseValue.setText(_translate("DomainSorter", "TextLabel"))
        self.lCarrierFrequency.setText(_translate("DomainSorter", "Carrier Frequency:"))
        self.lModTypeValue.setText(_translate("DomainSorter", "TextLabel"))
        self.label_carrier_phase.setText(_translate("DomainSorter", "Carrier Phase:"))
        self.labelBitsPerSymbol.setText(_translate("DomainSorter", "TextLabel"))
        self.lSampleRate.setText(_translate("DomainSorter", "Sample Rate:"))
        self.lModType.setText(_translate("DomainSorter", "Modulation Type:"))
        self.lParamCaption.setText(_translate("DomainSorter", "Amplitudes:"))
        self.TotalSelected.setText(_translate("DomainSorter", "otal Selected"))
        self.lCarrierFreqValue.setText(_translate("DomainSorter", "TextLabel"))
        self.labelParameterValues.setText(_translate("DomainSorter", "0/100"))
        self.cBoxModulations.setItemText(0, _translate("DomainSorter", "Email Validation"))
        self.cBoxModulations.setItemText(1, _translate("DomainSorter", "Email Scraping"))
        self.prBarGeneration.setFormat(_translate("DomainSorter", "Work Task %p%"))
        self.btnSend.setText(_translate("DomainSorter", "Send data..."))
        self.btnEditModulation.setText(_translate("DomainSorter", "Edit ..."))
        self.lModulation.setText(_translate("DomainSorter", "Work Function:"))
        self.btnGenerate.setToolTip(_translate("DomainSorter", "Generate the complex file of the modulated signal, after tuning all parameters above."))
        self.btnGenerate.setText(_translate("DomainSorter", "Generate file..."))
        self.btnNetworkSDRSend.setToolTip(_translate("DomainSorter", "<html><head/><body><p><span style=\" font-weight:600;\">Send encoded data to your external application via TCP.</span></p></body></html>"))
        self.btnNetworkSDRSend.setText(_translate("DomainSorter", "Send via Network"))
        self.cbViewType.setItemText(0, _translate("DomainSorter", "View Only"))
        self.cbViewType.setItemText(1, _translate("DomainSorter", "View and Save"))
        self.cbViewType.setItemText(2, _translate("DomainSorter", "View and Save and Record"))
        self.lViewType.setText(_translate("DomainSorter", "Viewtype:"))
        self.btnRfCatSend.setToolTip(_translate("DomainSorter", "<html><head/><body><p><span style=\" font-weight:600;\">Send encoded data via RfCat. </span></p><p><span style=\" font-style:italic;\">Hit again for stopping the sending process. Note that you can set the number of repetitions (from 1 to infinite) in:</span></p><p><span style=\" font-style:italic;\">Edit-&gt;Options-&gt;Device-&gt;\'Device sending repetitions\'</span></p></body></html>"))
        self.btnRfCatSend.setText(_translate("DomainSorter", "Send via RfCat"))
        self.Domain_Results_label.setText(_translate("DomainSorter", "Stats & Details"))
        self.btnSave.setToolTip(_translate("DomainSorter", "Save current fuzz profile."))
        self.btnSave.setText(_translate("DomainSorter", "..."))
        self.btnOpen.setToolTip(_translate("DomainSorter", "Load a fuzz profile."))
        self.btnOpen.setText(_translate("DomainSorter", "..."))
        self.lEstimatedTime.setToolTip(_translate("DomainSorter", "<html><head/><body><p>The estimated average time is based on the average number of bits per message and average sample rate, you set for the modulations.</p></body></html>"))
        self.lEstimatedTime.setText(_translate("DomainSorter", "Estimated Time: "))
        self.btnFZSave.setText(_translate("DomainSorter", "Save as FlipperZero SubGHz"))
from urh.ui.ElidedLabel import ElidedLabel
from urh.ui.views.GeneratorListView import GeneratorListView
from urh.ui.views.GeneratorTableView import GeneratorTableView


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = DomainSorter()
    window.show()
    sys.exit(app.exec_())