# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUi3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1027, 610)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-60, -80, 991, 681))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgba(85, 98, 112, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
"    color: rgba(131, 96, 53, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(91, 88, 53, 255);\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.backdrop_holder_label = QtWidgets.QLabel(self.widget)
        self.backdrop_holder_label.setGeometry(QtCore.QRect(100, 210, 531, 481))
        self.backdrop_holder_label.setStyleSheet("border-image: url(:/images/background.gif);\n"
"border-top-left-radius: 50px;")
        self.backdrop_holder_label.setText("")
        self.backdrop_holder_label.setObjectName("backdrop_holder_label")
        self.backdrop_holder = QtWidgets.QLabel(self.widget)
        self.backdrop_holder.setGeometry(QtCore.QRect(100, 70, 531, 611))
        self.backdrop_holder.setStyleSheet("background-color:rgba(0, 0, 0, 80);\n"
"border-top-left-radius: 50px;")
        self.backdrop_holder.setText("")
        self.backdrop_holder.setObjectName("backdrop_holder")
        self.program_backdrop = QtWidgets.QLabel(self.widget)
        self.program_backdrop.setGeometry(QtCore.QRect(110, 80, 521, 130))
        self.program_backdrop.setStyleSheet("background-color:rgba(0, 0, 0, 75);")
        self.program_backdrop.setText("")
        self.program_backdrop.setObjectName("program_backdrop")
        self.program_title = QtWidgets.QLabel(self.widget)
        self.program_title.setGeometry(QtCore.QRect(380, 90, 231, 40))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.program_title.setFont(font)
        self.program_title.setStyleSheet("color:rgba(255, 255, 255, 200);")
        self.program_title.setObjectName("program_title")
        self.program_description = QtWidgets.QLabel(self.widget)
        self.program_description.setGeometry(QtCore.QRect(119, 140, 481, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.program_description.setFont(font)
        self.program_description.setStyleSheet("color:rgba(255, 255, 255, 170);")
        self.program_description.setObjectName("program_description")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(570, 0, 451, 611))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.login_backdrop = QtWidgets.QLabel(self.tab)
        self.login_backdrop.setGeometry(QtCore.QRect(-30, 0, 441, 591))
        self.login_backdrop.setStyleSheet("background-color:rgba(255, 255, 255, 255);\n"
"border-bottom-right-radius: 50px;")
        self.login_backdrop.setText("")
        self.login_backdrop.setObjectName("login_backdrop")
        self.username_lineedit = QtWidgets.QLineEdit(self.tab)
        self.username_lineedit.setGeometry(QtCore.QRect(95, 180, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_lineedit.setFont(font)
        self.username_lineedit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.username_lineedit.setObjectName("username_lineedit")
        self.password_lineedit = QtWidgets.QLineEdit(self.tab)
        self.password_lineedit.setGeometry(QtCore.QRect(95, 245, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_lineedit.setFont(font)
        self.password_lineedit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineedit.setObjectName("password_lineedit")
        self.i_label_button = QtWidgets.QPushButton(self.tab)
        self.i_label_button.setGeometry(QtCore.QRect(267, 411, 30, 30))
        self.i_label_button.setMaximumSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.i_label_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.i_label_button.setFont(font)
        self.i_label_button.setMouseTracking(True)
        self.i_label_button.setCheckable(False)
        self.i_label_button.setObjectName("i_label_button")
        self.l_label_button = QtWidgets.QPushButton(self.tab)
        self.l_label_button.setGeometry(QtCore.QRect(145, 411, 30, 30))
        self.l_label_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.l_label_button.setFont(font)
        self.l_label_button.setCheckable(False)
        self.l_label_button.setChecked(False)
        self.l_label_button.setObjectName("l_label_button")
        self.p_label_button = QtWidgets.QPushButton(self.tab)
        self.p_label_button.setGeometry(QtCore.QRect(84, 411, 30, 30))
        self.p_label_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.p_label_button.setFont(font)
        self.p_label_button.setObjectName("p_label_button")
        self.login_button = QtWidgets.QPushButton(self.tab)
        self.login_button.setGeometry(QtCore.QRect(95, 325, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.login_label = QtWidgets.QLabel(self.tab)
        self.login_label.setGeometry(QtCore.QRect(140, 110, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.login_label.setFont(font)
        self.login_label.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.login_label.setObjectName("login_label")
        self.x_label_button = QtWidgets.QPushButton(self.tab)
        self.x_label_button.setGeometry(QtCore.QRect(23, 411, 30, 30))
        self.x_label_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.x_label_button.setFont(font)
        self.x_label_button.setObjectName("x_label_button")
        self.o_label_button = QtWidgets.QPushButton(self.tab)
        self.o_label_button.setGeometry(QtCore.QRect(206, 411, 30, 30))
        self.o_label_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.o_label_button.setFont(font)
        self.o_label_button.setObjectName("o_label_button")
        self.Forgot_username_label = QtWidgets.QLabel(self.tab)
        self.Forgot_username_label.setGeometry(QtCore.QRect(101, 375, 181, 16))
        self.Forgot_username_label.setStyleSheet("color:rgba(0, 0, 0, 210);")
        self.Forgot_username_label.setObjectName("Forgot_username_label")
        self.t_label_button = QtWidgets.QPushButton(self.tab)
        self.t_label_button.setGeometry(QtCore.QRect(328, 411, 30, 30))
        self.t_label_button.setMaximumSize(QtCore.QSize(30, 30))
        palette = QtGui.QPalette()
        self.t_label_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.t_label_button.setFont(font)
        self.t_label_button.setMouseTracking(True)
        self.t_label_button.setCheckable(False)
        self.t_label_button.setObjectName("t_label_button")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../OneDrive/Documents/New Structure/icons/exit-to-app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.information_tab2 = QtWidgets.QWidget()
        self.information_tab2.setObjectName("information_tab2")
        self.tab_2_widget_holder = QAxContainer.QAxWidget(self.information_tab2)
        self.tab_2_widget_holder.setProperty("geometry", QtCore.QRect(10, 170, 391, 391))
        self.tab_2_widget_holder.setObjectName("tab_2_widget_holder")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../OneDrive/Documents/New Structure/icons/go-back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.information_tab2, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.program_title.setText(_translate("Form", "DiamondSorter"))
        self.program_description.setText(_translate("Form", "Hi,\n"
"Welcome to my youtube channel.\n"
"Don\'t forget to subscribe."))
        self.username_lineedit.setPlaceholderText(_translate("Form", "  User Name"))
        self.password_lineedit.setPlaceholderText(_translate("Form", "  Password"))
        self.i_label_button.setText(_translate("Form", "I"))
        self.l_label_button.setText(_translate("Form", "L"))
        self.p_label_button.setText(_translate("Form", "P"))
        self.login_button.setText(_translate("Form", "L o g  I n"))
        self.login_label.setText(_translate("Form", "Log In"))
        self.x_label_button.setText(_translate("Form", "X"))
        self.o_label_button.setText(_translate("Form", "O"))
        self.Forgot_username_label.setText(_translate("Form", "Forgot your User Name or password?"))
        self.t_label_button.setText(_translate("Form", "T"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.information_tab2), _translate("Form", "Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Project Information + Updates"))
from PyQt5 import QAxContainer
import resource_rc
